#ifndef pOt_Strings__INC
#define pOt_Strings__INC
/* This code is generated by pOt. */





extern pOt_LONGINT pOt_Length_Strings pOt__ARGS((pOt__DynArr *));
extern void pOt_Append_Strings pOt__ARGS((pOt__DynArr *, pOt__DynArr *));
extern void pOt_FromLInt_Strings pOt__ARGS((pOt_LONGINT , pOt_SHORTINT , pOt__DynArr *));
extern void pOt_Strings__body pOt__ARGS((void));

#endif
