/* This code is generated by pOt. */
#line 42 "texts.mod"

#line 42 "texts.mod"
#include <pOtRTL.h>
#line 42 "texts.mod"
#include "Files.h"
#line 42 "texts.mod"
#include "Reals.h"
#line 42 "texts.mod"

#line 42 "texts.mod"
#include "Texts.hi"
#line 42 "texts.mod"

#line 42 "texts.mod"
typedef pOt_File_Files pOt_Text_Texts;
#line 42 "texts.mod"
typedef struct pOt__tag_1_Texts *pOt_Buffer_Texts;
#line 42 "texts.mod"
typedef struct pOt__tag_1_Texts pOt_BufDesc_Texts;
#line 42 "texts.mod"
typedef struct pOt__tag_2_Texts pOt_Reader_Texts;
#line 42 "texts.mod"
typedef struct pOt__tag_4_Texts pOt_Scanner_Texts;
#line 42 "texts.mod"
typedef struct pOt__tag_5_Texts pOt_Writer_Texts;
#line 42 "texts.mod"

#line 42 "texts.mod"
struct pOt__tag_0_Texts {
#line 42 "texts.mod"
  pOt__ArrTypDsc *td;
#line 42 "texts.mod"
  pOt_CHAR arr[0x200L];
#line 42 "texts.mod"
} ;
#line 42 "texts.mod"
pOt__ArrTypDsc pOt__td_0_Texts= {
#line 42 "texts.mod"
  1,
#line 42 "texts.mod"
  0x200L, sizeof(pOt_CHAR)
#line 42 "texts.mod"
};
#line 42 "texts.mod"
struct pOt__tag_1_Texts {
#line 42 "texts.mod"
  pOt__RecTypDsc *td;
#line 42 "texts.mod"
  pOt_Buffer_Texts pOt_next;
#line 42 "texts.mod"
  pOt_LONGINT pOt_len;
#line 42 "texts.mod"
  struct pOt__tag_0_Texts pOt_data;
#line 42 "texts.mod"
} ;
#line 42 "texts.mod"
struct {
#line 42 "texts.mod"
  pOt_INTEGER mode;
#line 42 "texts.mod"
  pOt_LONGINT size;
#line 42 "texts.mod"
  pOt_INTEGER extlev, nstr, nptr, npro;
#line 42 "texts.mod"
  pOt__RecTypDsc *base_td[pOt__MaxExts];
#line 42 "texts.mod"
  struct {pOt_LONGINT poffs; pOt__TypDsc *fld_td;} tab[0x2];
#line 42 "texts.mod"
} pOt__td_1_Texts= {
#line 42 "texts.mod"
  0,
#line 42 "texts.mod"
  sizeof(struct pOt__tag_1_Texts),
#line 42 "texts.mod"
  0x0, 0x1, 0x1, 0x0,
#line 42 "texts.mod"
  {pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL},
#line 42 "texts.mod"
  {
#line 42 "texts.mod"
    {(pOt_LONGINT)&((struct pOt__tag_1_Texts*)0)->pOt_data, (pOt__TypDsc*)&pOt__td_0_Texts},
#line 42 "texts.mod"
    {(pOt_LONGINT)&((struct pOt__tag_1_Texts*)0)->pOt_next, pOt_NIL}
#line 42 "texts.mod"
  }
#line 42 "texts.mod"
};
#line 42 "texts.mod"
struct pOt__tag_2_Texts {
#line 42 "texts.mod"
  struct pOt__tag_2_Files base;
#line 42 "texts.mod"
  pOt_BOOLEAN pOt_eot;
#line 42 "texts.mod"
} ;
#line 42 "texts.mod"
struct {
#line 42 "texts.mod"
  pOt_INTEGER mode;
#line 42 "texts.mod"
  pOt_LONGINT size;
#line 42 "texts.mod"
  pOt_INTEGER extlev, nstr, nptr, npro;
#line 42 "texts.mod"
  pOt__RecTypDsc *base_td[pOt__MaxExts];
#line 42 "texts.mod"
} pOt__td_2_Texts= {
#line 42 "texts.mod"
  0,
#line 42 "texts.mod"
  sizeof(struct pOt__tag_2_Texts),
#line 42 "texts.mod"
  0x1, 0x0, 0x0, 0x0,
#line 42 "texts.mod"
  {(pOt__RecTypDsc*)&pOt__td_2_Files, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL}
#line 42 "texts.mod"
};
#line 42 "texts.mod"
struct pOt__tag_3_Texts {
#line 42 "texts.mod"
  pOt__ArrTypDsc *td;
#line 42 "texts.mod"
  pOt_CHAR arr[0x20L];
#line 42 "texts.mod"
} ;
#line 42 "texts.mod"
pOt__ArrTypDsc pOt__td_3_Texts= {
#line 42 "texts.mod"
  1,
#line 42 "texts.mod"
  0x20L, sizeof(pOt_CHAR)
#line 42 "texts.mod"
};
#line 42 "texts.mod"
struct pOt__tag_4_Texts {
#line 42 "texts.mod"
  struct pOt__tag_2_Texts base;
#line 42 "texts.mod"
  pOt_CHAR pOt_nextCh;
#line 42 "texts.mod"
  pOt_INTEGER pOt_line, pOt_class;
#line 42 "texts.mod"
  pOt_LONGINT pOt_i;
#line 42 "texts.mod"
  pOt_REAL pOt_x;
#line 42 "texts.mod"
  pOt_LONGREAL pOt_y;
#line 42 "texts.mod"
  pOt_CHAR pOt_c;
#line 42 "texts.mod"
  pOt_SHORTINT pOt_len;
#line 42 "texts.mod"
  struct pOt__tag_3_Texts pOt_s;
#line 42 "texts.mod"
} ;
#line 42 "texts.mod"
struct {
#line 42 "texts.mod"
  pOt_INTEGER mode;
#line 42 "texts.mod"
  pOt_LONGINT size;
#line 42 "texts.mod"
  pOt_INTEGER extlev, nstr, nptr, npro;
#line 42 "texts.mod"
  pOt__RecTypDsc *base_td[pOt__MaxExts];
#line 42 "texts.mod"
  struct {pOt_LONGINT poffs; pOt__TypDsc *fld_td;} tab[0x1];
#line 42 "texts.mod"
} pOt__td_4_Texts= {
#line 42 "texts.mod"
  0,
#line 42 "texts.mod"
  sizeof(struct pOt__tag_4_Texts),
#line 42 "texts.mod"
  0x2, 0x1, 0x0, 0x0,
#line 42 "texts.mod"
  {(pOt__RecTypDsc*)&pOt__td_2_Files, (pOt__RecTypDsc*)&pOt__td_2_Texts, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL},
#line 42 "texts.mod"
  {
#line 42 "texts.mod"
    {(pOt_LONGINT)&((struct pOt__tag_4_Texts*)0)->pOt_s, (pOt__TypDsc*)&pOt__td_3_Texts}
#line 42 "texts.mod"
  }
#line 42 "texts.mod"
};
#line 42 "texts.mod"
struct pOt__tag_5_Texts {
#line 42 "texts.mod"
  pOt__RecTypDsc *td;
#line 42 "texts.mod"
  pOt_Buffer_Texts pOt_buf;
#line 42 "texts.mod"
} ;
#line 42 "texts.mod"
struct {
#line 42 "texts.mod"
  pOt_INTEGER mode;
#line 42 "texts.mod"
  pOt_LONGINT size;
#line 42 "texts.mod"
  pOt_INTEGER extlev, nstr, nptr, npro;
#line 42 "texts.mod"
  pOt__RecTypDsc *base_td[pOt__MaxExts];
#line 42 "texts.mod"
  struct {pOt_LONGINT poffs; pOt__TypDsc *fld_td;} tab[0x1];
#line 42 "texts.mod"
} pOt__td_5_Texts= {
#line 42 "texts.mod"
  0,
#line 42 "texts.mod"
  sizeof(struct pOt__tag_5_Texts),
#line 42 "texts.mod"
  0x0, 0x0, 0x1, 0x0,
#line 42 "texts.mod"
  {pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL},
#line 42 "texts.mod"
  {
#line 42 "texts.mod"
    {(pOt_LONGINT)&((struct pOt__tag_5_Texts*)0)->pOt_buf, pOt_NIL}
#line 42 "texts.mod"
  }
#line 42 "texts.mod"
};
#line 42 "texts.mod"

#line 42 "texts.mod"

#line 42 "texts.mod"
static struct {void *next, *vars[0x1];} pOt__gc_ptrs = {pOt_NIL,{
#line 42 "texts.mod"
  pOt_NIL
#line 42 "texts.mod"
}};
#line 42 "texts.mod"
static struct {void *next, *vars[0x1];} pOt__gc_strs = {&pOt__gc_ptrs,{
#line 42 "texts.mod"
  pOt_NIL
#line 42 "texts.mod"
}};
#line 42 "texts.mod"

#line 42 "texts.mod"

#line 44 "texts.mod"

#line 44 "texts.mod"

#line 44 "texts.mod"
static void pOt_RdString_Texts
#line 44 "texts.mod"
#if pOt__ANSI_C
#line 44 "texts.mod"
  (struct pOt__tag_2_Files *pOt_r, pOt__DynArr *pOt_s)
#line 44 "texts.mod"
#else
#line 44 "texts.mod"
  (pOt_r, pOt_s)
#line 44 "texts.mod"
  struct pOt__tag_2_Files *pOt_r;
#line 44 "texts.mod"
  pOt__DynArr *pOt_s;
#line 44 "texts.mod"

#line 44 "texts.mod"
#endif
#line 44 "texts.mod"
{
#line 44 "texts.mod"
  pOt_INTEGER pOt_i;
#line 44 "texts.mod"
  pOt_CHAR pOt_ch;
#line 44 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 44 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 44 "texts.mod"

#line 44 "texts.mod"
  pOt_i=(pOt_INTEGER)(0);
#line 44 "texts.mod"
  for(;;) {
    pOt_Read_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_BYTE_SYSTEM*)&pOt_ch);
#line 45 "texts.mod"
    (*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i)))))=pOt_ch;
#line 45 "texts.mod"
    pOt_i+=(1);
#line 45 "texts.mod"
    if(((((unsigned char)pOt_ch==(unsigned char)'\0'))||((((pOt_LONGINT)(pOt_i))==(*((pOt__ArrTypDsc**)&(*pOt_s)+0))->nofel)))) break;
#line 45 "texts.mod"
  }
#line 45 "texts.mod"
  for(;;) {
    if((!(*pOt_r).pOt_eof&&(((unsigned char)pOt_ch!=(unsigned char)'\0')))); else break;
#line 46 "texts.mod"
    pOt_Read_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_BYTE_SYSTEM*)&pOt_ch);
#line 46 "texts.mod"
  }
#line 46 "texts.mod"
  (*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i)))))='\0';
#line 48 "texts.mod"

#line 48 "texts.mod"
pOt__Epilogue:;
#line 48 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 48 "texts.mod"
}
#line 48 "texts.mod"

#line 48 "texts.mod"

#line 52 "texts.mod"

#line 52 "texts.mod"

#line 52 "texts.mod"
static void pOt_RdInt_Texts
#line 52 "texts.mod"
#if pOt__ANSI_C
#line 52 "texts.mod"
  (struct pOt__tag_2_Files *pOt_r, pOt_INTEGER *pOt_n)
#line 52 "texts.mod"
#else
#line 52 "texts.mod"
  (pOt_r, pOt_n)
#line 52 "texts.mod"
  struct pOt__tag_2_Files *pOt_r;
#line 52 "texts.mod"
  pOt_INTEGER *pOt_n;
#line 52 "texts.mod"

#line 52 "texts.mod"
#endif
#line 52 "texts.mod"
{
#line 52 "texts.mod"
  pOt_CHAR pOt_c0;
#line 52 "texts.mod"
  pOt_SHORTINT pOt_s1;
#line 52 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 52 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 52 "texts.mod"

#line 52 "texts.mod"
  pOt_Read_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_BYTE_SYSTEM*)&pOt_c0);
#line 52 "texts.mod"
  pOt_Read_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_BYTE_SYSTEM*)&pOt_s1);
#line 52 "texts.mod"
  (*pOt_n)=(pOt_INTEGER)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_SHORTINT)(pOt_s1)),(pOt_LONGINT)(256),5)),(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_c0)),5));
#line 54 "texts.mod"

#line 54 "texts.mod"
pOt__Epilogue:;
#line 54 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 54 "texts.mod"
}
#line 54 "texts.mod"

#line 54 "texts.mod"

#line 58 "texts.mod"

#line 58 "texts.mod"

#line 58 "texts.mod"
static void pOt_RdLong_Texts
#line 58 "texts.mod"
#if pOt__ANSI_C
#line 58 "texts.mod"
  (struct pOt__tag_2_Files *pOt_r, pOt_LONGINT *pOt_n)
#line 58 "texts.mod"
#else
#line 58 "texts.mod"
  (pOt_r, pOt_n)
#line 58 "texts.mod"
  struct pOt__tag_2_Files *pOt_r;
#line 58 "texts.mod"
  pOt_LONGINT *pOt_n;
#line 58 "texts.mod"

#line 58 "texts.mod"
#endif
#line 58 "texts.mod"
{
#line 58 "texts.mod"
  pOt_CHAR pOt_c0, pOt_c1, pOt_c2;
#line 58 "texts.mod"
  pOt_SHORTINT pOt_s3;
#line 58 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 58 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 58 "texts.mod"

#line 58 "texts.mod"
  pOt_Read_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_BYTE_SYSTEM*)&pOt_c0);
#line 58 "texts.mod"
  pOt_Read_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_BYTE_SYSTEM*)&pOt_c1);
#line 58 "texts.mod"
  pOt_Read_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_BYTE_SYSTEM*)&pOt_c2);
#line 58 "texts.mod"
  pOt_Read_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_BYTE_SYSTEM*)&pOt_s3);
#line 58 "texts.mod"
  (*pOt_n)=(pOt_LONGINT)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)(((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)(((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_SHORTINT)(pOt_s3)),(pOt_LONGINT)(256),5)),(pOt_LONGINT)((pOt_INTEGER)((pOt_INTEGER)((unsigned char)pOt_c2))),6))),(pOt_LONGINT)(256),6)),(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_c1)),6))),(pOt_LONGINT)(256),6)),(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_c0)),6));
#line 60 "texts.mod"

#line 60 "texts.mod"
pOt__Epilogue:;
#line 60 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 60 "texts.mod"
}
#line 60 "texts.mod"

#line 60 "texts.mod"

#line 65 "texts.mod"

#line 65 "texts.mod"

#line 65 "texts.mod"
static void pOt_WrtString_Texts
#line 65 "texts.mod"
#if pOt__ANSI_C
#line 65 "texts.mod"
  (struct pOt__tag_2_Files *pOt_r, pOt__DynArr *pOt_s)
#line 65 "texts.mod"
#else
#line 65 "texts.mod"
  (pOt_r, pOt_s)
#line 65 "texts.mod"
  struct pOt__tag_2_Files *pOt_r;
#line 65 "texts.mod"
  pOt__DynArr *pOt_s;
#line 65 "texts.mod"

#line 65 "texts.mod"
#endif
#line 65 "texts.mod"
{
#line 65 "texts.mod"
  pOt_INTEGER pOt_i;
#line 65 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 65 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 65 "texts.mod"

#line 65 "texts.mod"
  pOt_i=(pOt_INTEGER)(0);
#line 65 "texts.mod"
  for(;;) {
    pOt_i+=(1);
#line 66 "texts.mod"
    if(((unsigned char) (*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i)))))==(unsigned char)'\0')) break;
#line 66 "texts.mod"
  }
#line 66 "texts.mod"
  pOt_WriteBytes_Files((struct pOt__tag_2_Files*)&(*pOt_r),pOt__make_byte_arr((void*)&(*pOt_s),1,0),(pOt_LONGINT)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_i),(pOt_LONGINT)(1),5)));
#line 68 "texts.mod"

#line 68 "texts.mod"
pOt__Epilogue:;
#line 68 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 68 "texts.mod"
}
#line 68 "texts.mod"

#line 68 "texts.mod"

#line 71 "texts.mod"

#line 71 "texts.mod"

#line 71 "texts.mod"
static void pOt_WrtInt_Texts
#line 71 "texts.mod"
#if pOt__ANSI_C
#line 71 "texts.mod"
  (struct pOt__tag_2_Files *pOt_r, pOt_INTEGER pOt_n)
#line 71 "texts.mod"
#else
#line 71 "texts.mod"
  (pOt_r, pOt_n)
#line 71 "texts.mod"
  struct pOt__tag_2_Files *pOt_r;
#line 71 "texts.mod"
  pOt_INTEGER pOt_n;
#line 71 "texts.mod"

#line 71 "texts.mod"
#endif
#line 71 "texts.mod"
{
#line 71 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 71 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 71 "texts.mod"

#line 71 "texts.mod"
  pOt_Write_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_INTEGER)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(256),5))));
#line 71 "texts.mod"
  pOt_Write_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_INTEGER)pOt__rngchk_si(__FILE__,__LINE__,(pOt_INTEGER)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(256),5)));

#line 72 "texts.mod"
pOt__Epilogue:;
#line 72 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 72 "texts.mod"
}
#line 72 "texts.mod"

#line 72 "texts.mod"

#line 75 "texts.mod"

#line 75 "texts.mod"

#line 75 "texts.mod"
static void pOt_WrtLong_Texts
#line 75 "texts.mod"
#if pOt__ANSI_C
#line 75 "texts.mod"
  (struct pOt__tag_2_Files *pOt_r, pOt_LONGINT pOt_n)
#line 75 "texts.mod"
#else
#line 75 "texts.mod"
  (pOt_r, pOt_n)
#line 75 "texts.mod"
  struct pOt__tag_2_Files *pOt_r;
#line 75 "texts.mod"
  pOt_LONGINT pOt_n;
#line 75 "texts.mod"

#line 75 "texts.mod"
#endif
#line 75 "texts.mod"
{
#line 75 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 75 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 75 "texts.mod"

#line 75 "texts.mod"
  pOt_Write_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(256),6))));
#line 75 "texts.mod"
  pOt_Write_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(256),6)),(pOt_LONGINT)(256),6))));
#line 75 "texts.mod"
  pOt_Write_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(65536L),6)),(pOt_LONGINT)(256),6))));
  pOt_Write_Files((struct pOt__tag_2_Files*)&(*pOt_r),(pOt_INTEGER)pOt__rngchk_si(__FILE__,__LINE__,(pOt_LONGINT)pOt__rngchk_i(__FILE__,__LINE__,((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(16777216L),6)))));

#line 77 "texts.mod"
pOt__Epilogue:;
#line 77 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 77 "texts.mod"
}
#line 77 "texts.mod"

#line 77 "texts.mod"

#line 82 "texts.mod"

#line 82 "texts.mod"

#line 82 "texts.mod"
extern void pOt_OpenBuf_Texts
#line 82 "texts.mod"
#if pOt__ANSI_C
#line 82 "texts.mod"
  (pOt_Buffer_Texts *pOt_B)
#line 82 "texts.mod"
#else
#line 82 "texts.mod"
  (pOt_B)
#line 82 "texts.mod"
  pOt_Buffer_Texts *pOt_B;
#line 82 "texts.mod"

#line 82 "texts.mod"
#endif
#line 82 "texts.mod"
{
#line 82 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 82 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 82 "texts.mod"

#line 82 "texts.mod"
  pOt__new(__FILE__,__LINE__,(pOt__TypDsc***)&(*pOt_B),(pOt__TypDsc*)&pOt__td_1_Texts);
#line 82 "texts.mod"
  (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_B)))).pOt_next=(struct pOt__tag_1_Texts*)(pOt_NIL);
#line 82 "texts.mod"
  (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_B)))).pOt_len=(pOt_LONGINT)(0);

#line 83 "texts.mod"
pOt__Epilogue:;
#line 83 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 83 "texts.mod"
}
#line 83 "texts.mod"

#line 83 "texts.mod"

#line 88 "texts.mod"

#line 88 "texts.mod"
static pOt_File_Files (*pOt_T_Append_Texts);
#line 88 "texts.mod"
static pOt_Buffer_Texts *pOt_B_Append_Texts;
#line 88 "texts.mod"
static struct pOt__tag_2_Files (*pOt_R_Append_Texts);
#line 88 "texts.mod"

#line 88 "texts.mod"
extern void pOt_Append_Texts pOt__ARGS((pOt_File_Files , pOt_Buffer_Texts *));
#line 88 "texts.mod"

#line 88 "texts.mod"

#line 90 "texts.mod"

#line 90 "texts.mod"

#line 90 "texts.mod"
static void pOt_Invert_Append_Texts()
#line 90 "texts.mod"
{
#line 90 "texts.mod"
  pOt_Buffer_Texts pOt_b1, pOt_b2;
#line 90 "texts.mod"
  struct {void *next, *vars[0x3];} pOt__gc_ptrs;
#line 90 "texts.mod"
  struct {void *next, *vars[0x1];} pOt__gc_strs;
#line 90 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 90 "texts.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 90 "texts.mod"
  pOt__gc_ptrs.vars[0x2]=pOt_NIL;
#line 90 "texts.mod"
  pOt__gc_strs.vars[0x0]=pOt_NIL;
#line 90 "texts.mod"
  pOt__gc_ptrs.vars[0x1]=&pOt_b1;
#line 90 "texts.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_b2;
#line 90 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 90 "texts.mod"
  pOt_b1=pOt_NIL;
#line 90 "texts.mod"
  pOt_b2=pOt_NIL;
#line 90 "texts.mod"

#line 90 "texts.mod"
  pOt_b1=(struct pOt__tag_1_Texts*)(pOt_NIL);
#line 90 "texts.mod"
  for(;;) {
    pOt_b2=(struct pOt__tag_1_Texts*)(pOt_b1);
#line 91 "texts.mod"
    pOt_b1=(struct pOt__tag_1_Texts*)((*pOt_B_Append_Texts));
#line 91 "texts.mod"
    (*pOt_B_Append_Texts)=(struct pOt__tag_1_Texts*)((*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_B_Append_Texts)))).pOt_next);
#line 91 "texts.mod"
    (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,pOt_b1))).pOt_next=(struct pOt__tag_1_Texts*)(pOt_b2);
#line 91 "texts.mod"
    if(( (*pOt_B_Append_Texts)==pOt_NIL)) break;
#line 91 "texts.mod"
  }
#line 91 "texts.mod"
  (*pOt_B_Append_Texts)=(struct pOt__tag_1_Texts*)(pOt_b1);
#line 93 "texts.mod"

#line 93 "texts.mod"
pOt__Epilogue:;
#line 93 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 93 "texts.mod"
}
#line 93 "texts.mod"

#line 93 "texts.mod"
extern void pOt_Append_Texts
#line 95 "texts.mod"
#if pOt__ANSI_C
#line 95 "texts.mod"
  (pOt_File_Files pOt_T, pOt_Buffer_Texts *pOt_B)
#line 95 "texts.mod"
#else
#line 95 "texts.mod"
  (pOt_T, pOt_B)
#line 95 "texts.mod"
  pOt_File_Files pOt_T;
#line 95 "texts.mod"
  pOt_Buffer_Texts *pOt_B;
#line 95 "texts.mod"

#line 95 "texts.mod"
#endif
#line 95 "texts.mod"
{
#line 95 "texts.mod"
  pOt_File_Files (*pOt_T_);
#line 95 "texts.mod"
  pOt_Buffer_Texts *pOt_B_;
#line 95 "texts.mod"
  struct pOt__tag_2_Files pOt_R, (*pOt_R_);
#line 95 "texts.mod"
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
#line 95 "texts.mod"
  struct {void *next, *vars[0x2];} pOt__gc_strs;
#line 95 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 95 "texts.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 95 "texts.mod"
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
#line 95 "texts.mod"
  pOt__gc_strs.vars[0x1]=pOt_NIL;
#line 95 "texts.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_T;
#line 95 "texts.mod"
  pOt__gc_strs.vars[0x0]=&pOt_R;
#line 95 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 95 "texts.mod"
  pOt_T_=pOt_T_Append_Texts;
#line 95 "texts.mod"
  pOt_T_Append_Texts=&pOt_T;
#line 95 "texts.mod"
  pOt_B_=pOt_B_Append_Texts;
#line 95 "texts.mod"
  pOt_B_Append_Texts=pOt_B;
#line 95 "texts.mod"
  pOt_R_=pOt_R_Append_Texts;
#line 95 "texts.mod"
  pOt_R_Append_Texts=&pOt_R;
#line 95 "texts.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_R,(pOt__TypDsc*)&pOt__td_2_Files);
#line 95 "texts.mod"

#line 95 "texts.mod"
  pOt_Set_Files((struct pOt__tag_2_Files*)&pOt_R,(struct pOt__tag_1_Files*)(pOt_T),(pOt_LONGINT)(pOt_Length_Files((struct pOt__tag_1_Files*)(pOt_T))));
#line 95 "texts.mod"
  pOt_Invert_Append_Texts();
#line 95 "texts.mod"
  for(;;) {
    if(( (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_B)))).pOt_len==((pOt_LONGINT)(0)))) {
#line 96 "texts.mod"
      goto pOt__LoopLabel_1;
#line 96 "texts.mod"
    }
#line 96 "texts.mod"
    pOt_WriteBytes_Files((struct pOt__tag_2_Files*)&pOt_R,pOt__make_byte_arr((void*)&(*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_B)))).pOt_data,1,0),(pOt_LONGINT)((*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_B)))).pOt_len));
    if(( (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_B)))).pOt_next==pOt_NIL)) {
      (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_B)))).pOt_len=(pOt_LONGINT)(0);
#line 98 "texts.mod"
      goto pOt__LoopLabel_1;
#line 98 "texts.mod"
    }
#line 98 "texts.mod"
    (*pOt_B)=(struct pOt__tag_1_Texts*)((*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_B)))).pOt_next);
#line 100 "texts.mod"
  }
#line 100 "texts.mod"
pOt__LoopLabel_1:;
#line 100 "texts.mod"
  pOt_Set_Files((struct pOt__tag_2_Files*)&pOt_R,(struct pOt__tag_1_Files*)(pOt_T),(pOt_LONGINT)(pOt_Pos_Files((struct pOt__tag_2_Files*)&pOt_R)));
#line 102 "texts.mod"

#line 102 "texts.mod"
pOt__Epilogue:;
#line 102 "texts.mod"
  pOt_T_Append_Texts=pOt_T_;
#line 102 "texts.mod"
  pOt_B_Append_Texts=pOt_B_;
#line 102 "texts.mod"
  pOt_R_Append_Texts=pOt_R_;
#line 102 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 102 "texts.mod"
}
#line 102 "texts.mod"

#line 102 "texts.mod"

#line 107 "texts.mod"

#line 107 "texts.mod"

#line 107 "texts.mod"
extern void pOt_OpenReader_Texts
#line 107 "texts.mod"
#if pOt__ANSI_C
#line 107 "texts.mod"
  (struct pOt__tag_2_Texts *pOt_R, pOt_File_Files pOt_T, pOt_LONGINT pOt_pos)
#line 107 "texts.mod"
#else
#line 107 "texts.mod"
  (pOt_R, pOt_T, pOt_pos)
#line 107 "texts.mod"
  struct pOt__tag_2_Texts *pOt_R;
#line 107 "texts.mod"
  pOt_File_Files pOt_T;
#line 107 "texts.mod"
  pOt_LONGINT pOt_pos;
#line 107 "texts.mod"

#line 107 "texts.mod"
#endif
#line 107 "texts.mod"
{
#line 107 "texts.mod"
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
#line 107 "texts.mod"
  struct {void *next, *vars[0x1];} pOt__gc_strs;
#line 107 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 107 "texts.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 107 "texts.mod"
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
#line 107 "texts.mod"
  pOt__gc_strs.vars[0x0]=pOt_NIL;
#line 107 "texts.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_T;
#line 107 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 107 "texts.mod"

#line 107 "texts.mod"
  pOt_Set_Files((struct pOt__tag_2_Files*)&(*pOt_R),(struct pOt__tag_1_Files*)(pOt_T),(pOt_LONGINT)(pOt_pos));
#line 107 "texts.mod"
  (*pOt_R).pOt_eot=(pOt_BOOLEAN)0;

#line 108 "texts.mod"
pOt__Epilogue:;
#line 108 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 108 "texts.mod"
}
#line 108 "texts.mod"

#line 108 "texts.mod"

#line 111 "texts.mod"

#line 111 "texts.mod"

#line 111 "texts.mod"
extern void pOt_Read_Texts
#line 111 "texts.mod"
#if pOt__ANSI_C
#line 111 "texts.mod"
  (struct pOt__tag_2_Texts *pOt_R, pOt_CHAR *pOt_ch)
#line 111 "texts.mod"
#else
#line 111 "texts.mod"
  (pOt_R, pOt_ch)
#line 111 "texts.mod"
  struct pOt__tag_2_Texts *pOt_R;
#line 111 "texts.mod"
  pOt_CHAR *pOt_ch;
#line 111 "texts.mod"

#line 111 "texts.mod"
#endif
#line 111 "texts.mod"
{
#line 111 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 111 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 111 "texts.mod"

#line 111 "texts.mod"
  pOt_Read_Files((struct pOt__tag_2_Files*)&(*pOt_R),(pOt_BYTE_SYSTEM*)&(*pOt_ch));
#line 111 "texts.mod"
  (*pOt_R).pOt_eot=((*pOt_R).base.pOt_eof||(((unsigned char)(*pOt_ch)==(unsigned char)'\0')));

#line 112 "texts.mod"
pOt__Epilogue:;
#line 112 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 112 "texts.mod"
}
#line 112 "texts.mod"

#line 112 "texts.mod"

#line 115 "texts.mod"

#line 115 "texts.mod"

#line 115 "texts.mod"
extern pOt_LONGINT pOt_Pos_Texts
#line 115 "texts.mod"
#if pOt__ANSI_C
#line 115 "texts.mod"
  (struct pOt__tag_2_Texts *pOt_R)
#line 115 "texts.mod"
#else
#line 115 "texts.mod"
  (pOt_R)
#line 115 "texts.mod"
  struct pOt__tag_2_Texts *pOt_R;
#line 115 "texts.mod"

#line 115 "texts.mod"
#endif
#line 115 "texts.mod"
{
#line 115 "texts.mod"
  pOt_LONGINT pOt__retval;
#line 115 "texts.mod"
  int pOt__gc_enabled_prev;
#line 115 "texts.mod"
  pOt__gc_enabled_prev=pOt__gc_enabled;
#line 115 "texts.mod"
  pOt__gc_enabled=0;
#line 115 "texts.mod"

#line 115 "texts.mod"
  pOt__retval =(pOt_LONGINT)(pOt_Pos_Files((struct pOt__tag_2_Files*)&(*pOt_R)));
  goto pOt__Epilogue;
#line 116 "texts.mod"

#line 116 "texts.mod"
  pOt__halt(__FILE__,__LINE__,0x11);
#line 116 "texts.mod"
pOt__Epilogue:;
#line 116 "texts.mod"
  pOt__gc_enabled=pOt__gc_enabled_prev;
#line 116 "texts.mod"
  return pOt__retval;
#line 116 "texts.mod"
}
#line 116 "texts.mod"

#line 116 "texts.mod"

#line 121 "texts.mod"

#line 121 "texts.mod"

#line 121 "texts.mod"
extern void pOt_OpenScanner_Texts
#line 121 "texts.mod"
#if pOt__ANSI_C
#line 121 "texts.mod"
  (struct pOt__tag_4_Texts *pOt_S, pOt_File_Files pOt_T, pOt_LONGINT pOt_pos)
#line 121 "texts.mod"
#else
#line 121 "texts.mod"
  (pOt_S, pOt_T, pOt_pos)
#line 121 "texts.mod"
  struct pOt__tag_4_Texts *pOt_S;
#line 121 "texts.mod"
  pOt_File_Files pOt_T;
#line 121 "texts.mod"
  pOt_LONGINT pOt_pos;
#line 121 "texts.mod"

#line 121 "texts.mod"
#endif
#line 121 "texts.mod"
{
#line 121 "texts.mod"
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
#line 121 "texts.mod"
  struct {void *next, *vars[0x1];} pOt__gc_strs;
#line 121 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 121 "texts.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 121 "texts.mod"
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
#line 121 "texts.mod"
  pOt__gc_strs.vars[0x0]=pOt_NIL;
#line 121 "texts.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_T;
#line 121 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 121 "texts.mod"

#line 121 "texts.mod"
  pOt_OpenReader_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),(struct pOt__tag_1_Files*)(pOt_T),(pOt_LONGINT)(pOt_pos));
#line 121 "texts.mod"
  (*pOt_S).pOt_line=(pOt_INTEGER)(0);
#line 121 "texts.mod"
  (*pOt_S).pOt_nextCh=' ';

#line 122 "texts.mod"
pOt__Epilogue:;
#line 122 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 122 "texts.mod"
}
#line 122 "texts.mod"

#line 122 "texts.mod"

#line 137 "texts.mod"
struct pOt__tag_6_Texts {
#line 137 "texts.mod"
  pOt__ArrTypDsc *td;
#line 137 "texts.mod"
  pOt_CHAR arr[0x20L];
#line 137 "texts.mod"
} ;
#line 137 "texts.mod"
static pOt__ArrTypDsc pOt__td_6_Texts= {
#line 137 "texts.mod"
  1,
#line 137 "texts.mod"
  0x20L, sizeof(pOt_CHAR)
#line 137 "texts.mod"
};
#line 137 "texts.mod"

#line 137 "texts.mod"
static struct pOt__tag_4_Texts *pOt_S_Scan_Texts;
#line 137 "texts.mod"
static pOt_CHAR (*pOt_ch_Scan_Texts), (*pOt_term_Scan_Texts);
#line 137 "texts.mod"
static pOt_BOOLEAN (*pOt_neg_Scan_Texts), (*pOt_negE_Scan_Texts), (*pOt_hex_Scan_Texts);
#line 137 "texts.mod"
static pOt_SHORTINT (*pOt_i_Scan_Texts), (*pOt_j_Scan_Texts), (*pOt_h_Scan_Texts);
#line 137 "texts.mod"
static pOt_INTEGER (*pOt_e_Scan_Texts);
#line 137 "texts.mod"
static pOt_LONGINT (*pOt_k_Scan_Texts);
#line 137 "texts.mod"
static pOt_REAL (*pOt_x_Scan_Texts), (*pOt_f_Scan_Texts);
#line 137 "texts.mod"
static pOt_LONGREAL (*pOt_y_Scan_Texts), (*pOt_g_Scan_Texts);
#line 137 "texts.mod"
static struct pOt__tag_6_Texts (*pOt_d_Scan_Texts);
#line 137 "texts.mod"

#line 137 "texts.mod"
extern void pOt_Scan_Texts pOt__ARGS((struct pOt__tag_4_Texts *));
#line 137 "texts.mod"

#line 137 "texts.mod"


#line 138 "texts.mod"

#line 138 "texts.mod"
static void pOt_ReadScaleFactor_Scan_Texts()
#line 138 "texts.mod"
{
#line 138 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 138 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 138 "texts.mod"

#line 138 "texts.mod"
  pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S_Scan_Texts),&(*pOt_ch_Scan_Texts));
#line 138 "texts.mod"
  if(((unsigned char) (*pOt_ch_Scan_Texts)==(unsigned char)'-')) {
    (*pOt_negE_Scan_Texts)=(pOt_BOOLEAN)1;
#line 139 "texts.mod"
    pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S_Scan_Texts),&(*pOt_ch_Scan_Texts));
  } else {
#line 140 "texts.mod"
    (*pOt_negE_Scan_Texts)=(pOt_BOOLEAN)0;
#line 140 "texts.mod"
    if(((unsigned char) (*pOt_ch_Scan_Texts)==(unsigned char)'+')) {
      pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S_Scan_Texts),&(*pOt_ch_Scan_Texts));
#line 141 "texts.mod"
    }
#line 141 "texts.mod"
  }
  for(;;) {
    if(((((unsigned char)'0'<=(unsigned char)(*pOt_ch_Scan_Texts)))&&(((unsigned char)(*pOt_ch_Scan_Texts)<=(unsigned char)'9')))); else break;
#line 143 "texts.mod"
    (*pOt_e_Scan_Texts)=(pOt_INTEGER)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)((*pOt_e_Scan_Texts)),(pOt_LONGINT)(10),5)),(pOt_LONGINT)((pOt_INTEGER)((unsigned char)(*pOt_ch_Scan_Texts))),5)),(pOt_LONGINT)(48),5));
    pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S_Scan_Texts),&(*pOt_ch_Scan_Texts));
  }
#line 145 "texts.mod"

pOt__Epilogue:;
#line 146 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 146 "texts.mod"
}
#line 146 "texts.mod"

#line 146 "texts.mod"
extern void pOt_Scan_Texts
#line 148 "texts.mod"
#if pOt__ANSI_C
#line 148 "texts.mod"
  (struct pOt__tag_4_Texts *pOt_S)
#line 148 "texts.mod"
#else
#line 148 "texts.mod"
  (pOt_S)
#line 148 "texts.mod"
  struct pOt__tag_4_Texts *pOt_S;
#line 148 "texts.mod"

#line 148 "texts.mod"
#endif
#line 148 "texts.mod"
{
#line 148 "texts.mod"
  struct pOt__tag_4_Texts *pOt_S_;
#line 148 "texts.mod"
  pOt_CHAR pOt_ch, (*pOt_ch_), pOt_term, (*pOt_term_);
#line 148 "texts.mod"
  pOt_BOOLEAN pOt_neg, (*pOt_neg_), pOt_negE, (*pOt_negE_), pOt_hex, (*pOt_hex_);
#line 148 "texts.mod"
  pOt_SHORTINT pOt_i, (*pOt_i_), pOt_j, (*pOt_j_), pOt_h, (*pOt_h_);
#line 148 "texts.mod"
  pOt_INTEGER pOt_e, (*pOt_e_);
#line 148 "texts.mod"
  pOt_LONGINT pOt_k, (*pOt_k_);
#line 148 "texts.mod"
  pOt_REAL pOt_x, (*pOt_x_), pOt_f, (*pOt_f_);
#line 148 "texts.mod"
  pOt_LONGREAL pOt_y, (*pOt_y_), pOt_g, (*pOt_g_);
#line 148 "texts.mod"
  struct pOt__tag_6_Texts pOt_d, (*pOt_d_);
#line 148 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 148 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 148 "texts.mod"
  pOt_S_=pOt_S_Scan_Texts;
#line 148 "texts.mod"
  pOt_S_Scan_Texts=pOt_S;
#line 148 "texts.mod"
  pOt_ch_=pOt_ch_Scan_Texts;
#line 148 "texts.mod"
  pOt_ch_Scan_Texts=&pOt_ch;
#line 148 "texts.mod"
  pOt_term_=pOt_term_Scan_Texts;
#line 148 "texts.mod"
  pOt_term_Scan_Texts=&pOt_term;
#line 148 "texts.mod"
  pOt_neg_=pOt_neg_Scan_Texts;
#line 148 "texts.mod"
  pOt_neg_Scan_Texts=&pOt_neg;
#line 148 "texts.mod"
  pOt_negE_=pOt_negE_Scan_Texts;
#line 148 "texts.mod"
  pOt_negE_Scan_Texts=&pOt_negE;
#line 148 "texts.mod"
  pOt_hex_=pOt_hex_Scan_Texts;
#line 148 "texts.mod"
  pOt_hex_Scan_Texts=&pOt_hex;
#line 148 "texts.mod"
  pOt_i_=pOt_i_Scan_Texts;
#line 148 "texts.mod"
  pOt_i_Scan_Texts=&pOt_i;
#line 148 "texts.mod"
  pOt_j_=pOt_j_Scan_Texts;
#line 148 "texts.mod"
  pOt_j_Scan_Texts=&pOt_j;
#line 148 "texts.mod"
  pOt_h_=pOt_h_Scan_Texts;
#line 148 "texts.mod"
  pOt_h_Scan_Texts=&pOt_h;
#line 148 "texts.mod"
  pOt_e_=pOt_e_Scan_Texts;
#line 148 "texts.mod"
  pOt_e_Scan_Texts=&pOt_e;
#line 148 "texts.mod"
  pOt_k_=pOt_k_Scan_Texts;
#line 148 "texts.mod"
  pOt_k_Scan_Texts=&pOt_k;
#line 148 "texts.mod"
  pOt_x_=pOt_x_Scan_Texts;
#line 148 "texts.mod"
  pOt_x_Scan_Texts=&pOt_x;
#line 148 "texts.mod"
  pOt_f_=pOt_f_Scan_Texts;
#line 148 "texts.mod"
  pOt_f_Scan_Texts=&pOt_f;
#line 148 "texts.mod"
  pOt_y_=pOt_y_Scan_Texts;
#line 148 "texts.mod"
  pOt_y_Scan_Texts=&pOt_y;
#line 148 "texts.mod"
  pOt_g_=pOt_g_Scan_Texts;
#line 148 "texts.mod"
  pOt_g_Scan_Texts=&pOt_g;
#line 148 "texts.mod"
  pOt_d_=pOt_d_Scan_Texts;
#line 148 "texts.mod"
  pOt_d_Scan_Texts=&pOt_d;
#line 148 "texts.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_d,(pOt__TypDsc*)&pOt__td_6_Texts);
#line 148 "texts.mod"

#line 148 "texts.mod"
  pOt_ch=(*pOt_S).pOt_nextCh;
#line 148 "texts.mod"
  pOt_i=0;
#line 148 "texts.mod"
  for(;;) {
#line 150 "texts.mod"
    if(((unsigned char) pOt_ch==(unsigned char)'\12')) {
#line 150 "texts.mod"
      (*pOt_S).pOt_line+=(1);
    } else if(((((unsigned char)pOt_ch!=(unsigned char)' '))&&(((unsigned char)pOt_ch!=(unsigned char)'\11')))) {
#line 151 "texts.mod"
      goto pOt__LoopLabel_1;
    }
#line 152 "texts.mod"
    pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
#line 154 "texts.mod"
  }
#line 154 "texts.mod"
pOt__LoopLabel_1:;
#line 154 "texts.mod"
  if(((((unsigned char)'A'<=(unsigned char)pOt__cap((unsigned char)pOt_ch)))&&(((unsigned char)pOt__cap((unsigned char)pOt_ch)<=(unsigned char)'Z')))) {
#line 156 "texts.mod"
    for(;;) {
#line 156 "texts.mod"
      (*pOt_S).pOt_s.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_i)]=pOt_ch;
#line 156 "texts.mod"
      pOt_i+=(1);
#line 156 "texts.mod"
      pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
      if(((((((unsigned char)pOt__cap((unsigned char)pOt_ch)>(unsigned char)'Z'))||((((unsigned char)'A'>(unsigned char)pOt__cap((unsigned char)pOt_ch)))&&(((unsigned char)pOt_ch>(unsigned char)'9'))))||((((unsigned char)'0'>(unsigned char)pOt_ch))&&(((unsigned char)pOt_ch!=(unsigned char)'.'))))||((pOt_i==31)))) break;
#line 160 "texts.mod"
    }
#line 160 "texts.mod"
    (*pOt_S).pOt_s.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_i)]='\0';
    (*pOt_S).pOt_len=pOt_i;
#line 161 "texts.mod"
    (*pOt_S).pOt_class=(pOt_INTEGER)(1);
  } else if(((unsigned char) pOt_ch==(unsigned char)'\"')) {
    pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
#line 163 "texts.mod"
    for(;;) {
      if((((((unsigned char)pOt_ch!=(unsigned char)'\"'))&&(((unsigned char)pOt_ch>=(unsigned char)' ')))&&((pOt_i!=31)))); else break;
#line 164 "texts.mod"
      (*pOt_S).pOt_s.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_i)]=pOt_ch;
      pOt_i+=(1);
#line 165 "texts.mod"
      pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
    }
#line 166 "texts.mod"
    (*pOt_S).pOt_s.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_i)]='\0';
    (*pOt_S).pOt_len=(pOt_SHORTINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_i),(pOt_LONGINT)(1),4);
#line 167 "texts.mod"
    pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
#line 167 "texts.mod"
    (*pOt_S).pOt_class=(pOt_INTEGER)(2);
  } else {
    if(((unsigned char) pOt_ch==(unsigned char)'-')) {
#line 169 "texts.mod"
      pOt_neg=(pOt_BOOLEAN)1;
#line 169 "texts.mod"
      pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
#line 169 "texts.mod"
    } else {
#line 169 "texts.mod"
      pOt_neg=(pOt_BOOLEAN)0;
#line 169 "texts.mod"
    }
#line 169 "texts.mod"
    if(((((unsigned char)'0'<=(unsigned char)pOt_ch))&&(((unsigned char)pOt_ch<=(unsigned char)'9')))) {
#line 171 "texts.mod"
      pOt_hex=(pOt_BOOLEAN)0;
#line 171 "texts.mod"
      pOt_j=0;
#line 171 "texts.mod"
      for(;;) {
        pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_i)]=pOt_ch;
#line 172 "texts.mod"
        pOt_i+=(1);
#line 172 "texts.mod"
        pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
#line 172 "texts.mod"
        if(((unsigned char) pOt_ch<(unsigned char)'0')) {
          goto pOt__LoopLabel_2;
#line 173 "texts.mod"
        }
#line 173 "texts.mod"
        if(((unsigned char) '9'<(unsigned char)pOt_ch)) {
#line 175 "texts.mod"
          if(((((unsigned char)'A'<=(unsigned char)pOt_ch))&&(((unsigned char)pOt_ch<=(unsigned char)'F')))) {
#line 175 "texts.mod"
            pOt_hex=(pOt_BOOLEAN)1;
#line 175 "texts.mod"
            pOt_ch=(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_ch)),(pOt_LONGINT)(7),5)));
          } else if(((((unsigned char)'a'<=(unsigned char)pOt_ch))&&(((unsigned char)pOt_ch<=(unsigned char)'f')))) {
#line 176 "texts.mod"
            pOt_hex=(pOt_BOOLEAN)1;
#line 176 "texts.mod"
            pOt_ch=(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_ch)),(pOt_LONGINT)(39),5)));
          } else {
#line 177 "texts.mod"
            goto pOt__LoopLabel_2;
          }
#line 178 "texts.mod"
        }
      }
    pOt__LoopLabel_2:;
#line 180 "texts.mod"
      if(((unsigned char) pOt_ch==(unsigned char)'H')) {
#line 182 "texts.mod"
        pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
#line 182 "texts.mod"
        (*pOt_S).pOt_class=(pOt_INTEGER)(3);
#line 182 "texts.mod"
        if(( (pOt_SHORTINT)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_i),(pOt_LONGINT)(pOt_j),4)>8)) {
          pOt_j=(pOt_SHORTINT)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_i),(pOt_LONGINT)(8),4);
#line 183 "texts.mod"
        }
#line 183 "texts.mod"
        pOt_k=(pOt_LONGINT)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_j)])),(pOt_LONGINT)(48),5));
        pOt_j+=(1);
#line 184 "texts.mod"
        if(((((pOt_SHORTINT)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_i),(pOt_LONGINT)(pOt_j),4)==7))&&((pOt_k>=((pOt_LONGINT)(8)))))) {
          pOt_k-=(16);
#line 185 "texts.mod"
        }
#line 185 "texts.mod"
        for(;;) {
          if(( pOt_j<pOt_i)); else break;
#line 186 "texts.mod"
          pOt_k=(pOt_LONGINT)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_k),(pOt_LONGINT)(16),6)),(pOt_LONGINT)(((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_j)])),(pOt_LONGINT)(48),5))),6));
#line 186 "texts.mod"
          pOt_j+=(1);
#line 186 "texts.mod"
        }
#line 186 "texts.mod"
        if(pOt_neg) {
          (*pOt_S).pOt_i=(pOt_LONGINT)(-pOt_k);
#line 187 "texts.mod"
        } else {
#line 187 "texts.mod"
          (*pOt_S).pOt_i=(pOt_LONGINT)(pOt_k);
#line 187 "texts.mod"
        }
#line 187 "texts.mod"
      } else if(((unsigned char) pOt_ch==(unsigned char)'.')) {
#line 189 "texts.mod"
        pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
#line 189 "texts.mod"
        pOt_h=pOt_i;
#line 189 "texts.mod"
        for(;;) {
          if(((((unsigned char)'0'<=(unsigned char)pOt_ch))&&(((unsigned char)pOt_ch<=(unsigned char)'9')))); else break;
#line 190 "texts.mod"
          pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_i)]=pOt_ch;
#line 190 "texts.mod"
          pOt_i+=(1);
#line 190 "texts.mod"
          pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
#line 190 "texts.mod"
        }
#line 190 "texts.mod"
        if(((unsigned char) pOt_ch==(unsigned char)'D')) {
#line 192 "texts.mod"
          pOt_e=(pOt_INTEGER)(0);
#line 192 "texts.mod"
          pOt_y=(pOt_LONGREAL)(0);
#line 192 "texts.mod"
          pOt_g=(pOt_LONGREAL)(1);
#line 192 "texts.mod"
          for(;;) {
            pOt_y=(pOt_LONGREAL)(pOt_y*((pOt_LONGREAL)(10))+((pOt_LONGREAL)(((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_j)])),(pOt_LONGINT)(48),5)))));
#line 193 "texts.mod"
            pOt_j+=(1);
#line 193 "texts.mod"
            if(( pOt_j==pOt_h)) break;
#line 193 "texts.mod"
          }
#line 193 "texts.mod"
          for(;;) {
            if(( pOt_j<pOt_i)); else break;
#line 194 "texts.mod"
            pOt_g=(pOt_LONGREAL)(pOt_g/((pOt_LONGREAL)(10)));
#line 194 "texts.mod"
            pOt_y=(pOt_LONGREAL)(((pOt_LONGREAL)(((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_j)])),(pOt_LONGINT)(48),5))))*pOt_g+pOt_y);
#line 194 "texts.mod"
            pOt_j+=(1);
#line 194 "texts.mod"
          }
#line 194 "texts.mod"
          pOt_ReadScaleFactor_Scan_Texts();
          if(pOt_negE) {
#line 197 "texts.mod"
            if(( pOt_e<=308)) {
#line 197 "texts.mod"
              pOt_y=(pOt_LONGREAL)(pOt_y/pOt_TenL_Reals((pOt_INTEGER)(pOt_e)));
#line 197 "texts.mod"
            } else {
#line 197 "texts.mod"
              pOt_y=(pOt_LONGREAL)(0);
#line 197 "texts.mod"
            }
#line 197 "texts.mod"
          } else if(( pOt_e>((pOt_INTEGER)(0)))) {
#line 199 "texts.mod"
            if(( pOt_e<=308)) {
#line 199 "texts.mod"
              pOt_y=(pOt_LONGREAL)(pOt_TenL_Reals((pOt_INTEGER)(pOt_e))*pOt_y);
#line 199 "texts.mod"
            } else {
#line 199 "texts.mod"
              pOt__halt(__FILE__,__LINE__,40);
#line 199 "texts.mod"
            }
#line 199 "texts.mod"
          }
          if(pOt_neg) {
            pOt_y=(pOt_LONGREAL)(-pOt_y);
#line 201 "texts.mod"
          }
#line 201 "texts.mod"
          (*pOt_S).pOt_class=(pOt_INTEGER)(5);
          (*pOt_S).pOt_y=(pOt_LONGREAL)(pOt_y);
        } else {
#line 203 "texts.mod"
          pOt_e=(pOt_INTEGER)(0);
#line 203 "texts.mod"
          pOt_x=(pOt_REAL)(0);
#line 203 "texts.mod"
          pOt_f=(pOt_REAL)(1);
#line 203 "texts.mod"
          for(;;) {
            pOt_x=(pOt_REAL)(pOt_x*((pOt_REAL)(10))+((pOt_REAL)(((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_j)])),(pOt_LONGINT)(48),5)))));
#line 204 "texts.mod"
            pOt_j+=(1);
#line 204 "texts.mod"
            if(( pOt_j==pOt_h)) break;
#line 204 "texts.mod"
          }
#line 204 "texts.mod"
          for(;;) {
            if(( pOt_j<pOt_i)); else break;
#line 205 "texts.mod"
            pOt_f=(pOt_REAL)(pOt_f/((pOt_REAL)(10)));
#line 205 "texts.mod"
            pOt_x=(pOt_REAL)(((pOt_REAL)(((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_j)])),(pOt_LONGINT)(48),5))))*pOt_f+pOt_x);
#line 205 "texts.mod"
            pOt_j+=(1);
#line 205 "texts.mod"
          }
#line 205 "texts.mod"
          if(((unsigned char) pOt_ch==(unsigned char)'E')) {
            pOt_ReadScaleFactor_Scan_Texts();
#line 206 "texts.mod"
          }
#line 206 "texts.mod"
          if(pOt_negE) {
#line 208 "texts.mod"
            if(( pOt_e<=((pOt_INTEGER)(38)))) {
#line 208 "texts.mod"
              pOt_x=(pOt_REAL)(pOt_x/pOt_Ten_Reals((pOt_INTEGER)(pOt_e)));
#line 208 "texts.mod"
            } else {
#line 208 "texts.mod"
              pOt_x=(pOt_REAL)(0);
#line 208 "texts.mod"
            }
#line 208 "texts.mod"
          } else if(( pOt_e>((pOt_INTEGER)(0)))) {
#line 210 "texts.mod"
            if(( pOt_e<=((pOt_INTEGER)(38)))) {
#line 210 "texts.mod"
              pOt_x=(pOt_REAL)(pOt_Ten_Reals((pOt_INTEGER)(pOt_e))*pOt_x);
#line 210 "texts.mod"
            } else {
#line 210 "texts.mod"
              pOt__halt(__FILE__,__LINE__,40);
#line 210 "texts.mod"
            }
#line 210 "texts.mod"
          }
          if(pOt_neg) {
            pOt_x=(pOt_REAL)(-pOt_x);
#line 212 "texts.mod"
          }
#line 212 "texts.mod"
          (*pOt_S).pOt_class=(pOt_INTEGER)(4);
          (*pOt_S).pOt_x=(pOt_REAL)(pOt_x);
        }
#line 214 "texts.mod"
        if(pOt_hex) {
          (*pOt_S).pOt_class=(pOt_INTEGER)(0);
#line 215 "texts.mod"
        }
#line 215 "texts.mod"
      } else {
#line 217 "texts.mod"
        (*pOt_S).pOt_class=(pOt_INTEGER)(3);
#line 217 "texts.mod"
        pOt_k=(pOt_LONGINT)(0);
#line 217 "texts.mod"
        for(;;) {
          pOt_k=(pOt_LONGINT)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_k),(pOt_LONGINT)(10),6)),(pOt_LONGINT)(((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x20, pOt_j)])),(pOt_LONGINT)(48),5))),6));
#line 218 "texts.mod"
          pOt_j+=(1);
#line 218 "texts.mod"
          if(( pOt_j==pOt_i)) break;
#line 218 "texts.mod"
        }
#line 218 "texts.mod"
        if(pOt_neg) {
          (*pOt_S).pOt_i=(pOt_LONGINT)(-pOt_k);
#line 219 "texts.mod"
        } else {
#line 219 "texts.mod"
          (*pOt_S).pOt_i=(pOt_LONGINT)(pOt_k);
#line 219 "texts.mod"
        }
#line 219 "texts.mod"
        if(pOt_hex) {
          (*pOt_S).pOt_class=(pOt_INTEGER)(0);
#line 220 "texts.mod"
        } else {
#line 220 "texts.mod"
          (*pOt_S).pOt_class=(pOt_INTEGER)(3);
#line 220 "texts.mod"
        }
#line 220 "texts.mod"
      }
    } else {
      (*pOt_S).pOt_class=(pOt_INTEGER)(6);
#line 222 "texts.mod"
      if(pOt_neg) {
        (*pOt_S).pOt_c='-';
#line 223 "texts.mod"
      } else {
#line 223 "texts.mod"
        (*pOt_S).pOt_c=pOt_ch;
#line 223 "texts.mod"
        pOt_Read_Texts((struct pOt__tag_2_Texts*)&(*pOt_S),&pOt_ch);
#line 223 "texts.mod"
      }
#line 223 "texts.mod"
    }
  }
  (*pOt_S).pOt_nextCh=pOt_ch;
#line 227 "texts.mod"

#line 227 "texts.mod"
pOt__Epilogue:;
#line 227 "texts.mod"
  pOt_S_Scan_Texts=pOt_S_;
#line 227 "texts.mod"
  pOt_ch_Scan_Texts=pOt_ch_;
#line 227 "texts.mod"
  pOt_term_Scan_Texts=pOt_term_;
#line 227 "texts.mod"
  pOt_neg_Scan_Texts=pOt_neg_;
#line 227 "texts.mod"
  pOt_negE_Scan_Texts=pOt_negE_;
#line 227 "texts.mod"
  pOt_hex_Scan_Texts=pOt_hex_;
#line 227 "texts.mod"
  pOt_i_Scan_Texts=pOt_i_;
#line 227 "texts.mod"
  pOt_j_Scan_Texts=pOt_j_;
#line 227 "texts.mod"
  pOt_h_Scan_Texts=pOt_h_;
#line 227 "texts.mod"
  pOt_e_Scan_Texts=pOt_e_;
#line 227 "texts.mod"
  pOt_k_Scan_Texts=pOt_k_;
#line 227 "texts.mod"
  pOt_x_Scan_Texts=pOt_x_;
#line 227 "texts.mod"
  pOt_f_Scan_Texts=pOt_f_;
#line 227 "texts.mod"
  pOt_y_Scan_Texts=pOt_y_;
#line 227 "texts.mod"
  pOt_g_Scan_Texts=pOt_g_;
#line 227 "texts.mod"
  pOt_d_Scan_Texts=pOt_d_;
#line 227 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 227 "texts.mod"
}
#line 227 "texts.mod"

#line 227 "texts.mod"

#line 232 "texts.mod"

#line 232 "texts.mod"

#line 232 "texts.mod"
extern void pOt_OpenWriter_Texts
#line 232 "texts.mod"
#if pOt__ANSI_C
#line 232 "texts.mod"
  (struct pOt__tag_5_Texts *pOt_W)
#line 232 "texts.mod"
#else
#line 232 "texts.mod"
  (pOt_W)
#line 232 "texts.mod"
  struct pOt__tag_5_Texts *pOt_W;
#line 232 "texts.mod"

#line 232 "texts.mod"
#endif
#line 232 "texts.mod"
{
#line 232 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 232 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 232 "texts.mod"

#line 232 "texts.mod"
  pOt_OpenBuf_Texts(&(*pOt_W).pOt_buf);

#line 233 "texts.mod"
pOt__Epilogue:;
#line 233 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 233 "texts.mod"
}
#line 233 "texts.mod"

#line 233 "texts.mod"

#line 237 "texts.mod"

#line 237 "texts.mod"

#line 237 "texts.mod"
extern void pOt_Write_Texts
#line 237 "texts.mod"
#if pOt__ANSI_C
#line 237 "texts.mod"
  (struct pOt__tag_5_Texts *pOt_W, pOt_CHAR pOt_ch)
#line 237 "texts.mod"
#else
#line 237 "texts.mod"
  (pOt_W, pOt_ch)
#line 237 "texts.mod"
  struct pOt__tag_5_Texts *pOt_W;
#line 237 "texts.mod"
  pOt_CHAR pOt_ch;
#line 237 "texts.mod"

#line 237 "texts.mod"
#endif
#line 237 "texts.mod"
{
#line 237 "texts.mod"
  pOt_Buffer_Texts pOt_B;
#line 237 "texts.mod"
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
#line 237 "texts.mod"
  struct {void *next, *vars[0x1];} pOt__gc_strs;
#line 237 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 237 "texts.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 237 "texts.mod"
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
#line 237 "texts.mod"
  pOt__gc_strs.vars[0x0]=pOt_NIL;
#line 237 "texts.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_B;
#line 237 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 237 "texts.mod"
  pOt_B=pOt_NIL;
#line 237 "texts.mod"

#line 237 "texts.mod"
  if(( (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_W).pOt_buf))).pOt_len==((pOt_LONGINT)(512)))) {
#line 237 "texts.mod"
    pOt_OpenBuf_Texts(&pOt_B);
#line 237 "texts.mod"
    (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,pOt_B))).pOt_next=(struct pOt__tag_1_Texts*)((*pOt_W).pOt_buf);
#line 237 "texts.mod"
    (*pOt_W).pOt_buf=(struct pOt__tag_1_Texts*)(pOt_B);
#line 237 "texts.mod"
  }
#line 237 "texts.mod"
  (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_W).pOt_buf))).pOt_data.arr[pOt__inxchk(__FILE__,__LINE__,0x200, (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_W).pOt_buf))).pOt_len)]=pOt_ch;
  (*((struct pOt__tag_1_Texts*)pOt__nilchk(__FILE__,__LINE__,(*pOt_W).pOt_buf))).pOt_len+=(1);

#line 239 "texts.mod"
pOt__Epilogue:;
#line 239 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 239 "texts.mod"
}
#line 239 "texts.mod"

#line 239 "texts.mod"

#line 242 "texts.mod"

#line 242 "texts.mod"

#line 242 "texts.mod"
extern void pOt_WriteLn_Texts
#line 242 "texts.mod"
#if pOt__ANSI_C
#line 242 "texts.mod"
  (struct pOt__tag_5_Texts *pOt_W)
#line 242 "texts.mod"
#else
#line 242 "texts.mod"
  (pOt_W)
#line 242 "texts.mod"
  struct pOt__tag_5_Texts *pOt_W;
#line 242 "texts.mod"

#line 242 "texts.mod"
#endif
#line 242 "texts.mod"
{
#line 242 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 242 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 242 "texts.mod"

#line 242 "texts.mod"
  pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'\12');

#line 243 "texts.mod"
pOt__Epilogue:;
#line 243 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 243 "texts.mod"
}
#line 243 "texts.mod"

#line 243 "texts.mod"

#line 247 "texts.mod"

#line 247 "texts.mod"

#line 247 "texts.mod"
extern void pOt_WriteString_Texts
#line 247 "texts.mod"
#if pOt__ANSI_C
#line 247 "texts.mod"
  (struct pOt__tag_5_Texts *pOt_W, pOt__DynArr *pOt_s)
#line 247 "texts.mod"
#else
#line 247 "texts.mod"
  (pOt_W, pOt_s)
#line 247 "texts.mod"
  struct pOt__tag_5_Texts *pOt_W;
#line 247 "texts.mod"
  pOt__DynArr *pOt_s;
#line 247 "texts.mod"

#line 247 "texts.mod"
#endif
#line 247 "texts.mod"
{
#line 247 "texts.mod"
  pOt_INTEGER pOt_i;
#line 247 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 247 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 247 "texts.mod"

#line 247 "texts.mod"
  pOt_i=(pOt_INTEGER)(0);
#line 247 "texts.mod"
  for(;;) {
    if(((unsigned char) (*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i)))))>=(unsigned char)' ')); else break;
#line 248 "texts.mod"
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),(*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i))))));
#line 248 "texts.mod"
    pOt_i+=(1);
#line 248 "texts.mod"
  }
#line 248 "texts.mod"

pOt__Epilogue:;
#line 249 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 249 "texts.mod"
  pOt__rm_par((pOt__TypDsc**)pOt_s);
#line 249 "texts.mod"
}
#line 249 "texts.mod"

#line 249 "texts.mod"

#line 254 "texts.mod"
struct pOt__tag_7_Texts {
#line 254 "texts.mod"
  pOt__ArrTypDsc *td;
#line 254 "texts.mod"
  pOt_CHAR arr[0xBL];
#line 254 "texts.mod"
} ;
#line 254 "texts.mod"
static pOt__ArrTypDsc pOt__td_7_Texts= {
#line 254 "texts.mod"
  1,
#line 254 "texts.mod"
  0xBL, sizeof(pOt_CHAR)
#line 254 "texts.mod"
};
#line 254 "texts.mod"

#line 254 "texts.mod"

#line 254 "texts.mod"
extern void pOt_WriteInt_Texts
#line 254 "texts.mod"
#if pOt__ANSI_C
#line 254 "texts.mod"
  (struct pOt__tag_5_Texts *pOt_W, pOt_LONGINT pOt_x, pOt_LONGINT pOt_n)
#line 254 "texts.mod"
#else
#line 254 "texts.mod"
  (pOt_W, pOt_x, pOt_n)
#line 254 "texts.mod"
  struct pOt__tag_5_Texts *pOt_W;
#line 254 "texts.mod"
  pOt_LONGINT pOt_x, pOt_n;
#line 254 "texts.mod"

#line 254 "texts.mod"
#endif
#line 254 "texts.mod"
{
#line 254 "texts.mod"
  pOt_INTEGER pOt_i;
#line 254 "texts.mod"
  pOt_LONGINT pOt_x0;
#line 254 "texts.mod"
  struct pOt__tag_7_Texts pOt_a;
#line 254 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 254 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 254 "texts.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_a,(pOt__TypDsc*)&pOt__td_7_Texts);
#line 254 "texts.mod"

#line 254 "texts.mod"
  pOt_i=(pOt_INTEGER)(0);
#line 254 "texts.mod"
  if(( pOt_x<((pOt_LONGINT)(0)))) {
#line 256 "texts.mod"
    if(( pOt_x==(pOt_LONGINT)0x80000000L)) {
#line 256 "texts.mod"
      pOt_WriteString_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0xC]))));
#line 256 "texts.mod"
      goto pOt__Epilogue;
    } else {
#line 257 "texts.mod"
      pOt_n-=(1);
#line 257 "texts.mod"
      pOt_x0=(pOt_LONGINT)(-pOt_x);
    }
#line 258 "texts.mod"
  } else {
    pOt_x0=(pOt_LONGINT)(pOt_x);
  }
#line 260 "texts.mod"
  for(;;) {
#line 262 "texts.mod"
    pOt_a.arr[pOt__inxchk(__FILE__,__LINE__,0xB, pOt_i)]=(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_x0),(pOt_LONGINT)(10),6)),(pOt_LONGINT)(48),6)));
#line 262 "texts.mod"
    pOt_x0=(pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_x0),(pOt_LONGINT)(10),6));
#line 262 "texts.mod"
    pOt_i+=(1);
    if(( pOt_x0==((pOt_LONGINT)(0)))) break;
#line 263 "texts.mod"
  }
#line 263 "texts.mod"
  for(;;) {
    if(( pOt_n>((pOt_LONGINT)(pOt_i)))); else break;
#line 264 "texts.mod"
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),' ');
#line 264 "texts.mod"
    pOt_n-=(1);
#line 264 "texts.mod"
  }
#line 264 "texts.mod"
  if(( pOt_x<((pOt_LONGINT)(0)))) {
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'-');
#line 265 "texts.mod"
  }
#line 265 "texts.mod"
  for(;;) {
    pOt_i-=(1);
#line 266 "texts.mod"
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt_a.arr[pOt__inxchk(__FILE__,__LINE__,0xB, pOt_i)]);
#line 266 "texts.mod"
    if(( pOt_i==((pOt_INTEGER)(0)))) break;
  }
#line 267 "texts.mod"

#line 267 "texts.mod"
pOt__Epilogue:;
#line 267 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 267 "texts.mod"
}
#line 267 "texts.mod"

#line 267 "texts.mod"

#line 272 "texts.mod"
struct pOt__tag_8_Texts {
#line 272 "texts.mod"
  pOt__ArrTypDsc *td;
#line 272 "texts.mod"
  pOt_CHAR arr[0xAL];
#line 272 "texts.mod"
} ;
#line 272 "texts.mod"
static pOt__ArrTypDsc pOt__td_8_Texts= {
#line 272 "texts.mod"
  1,
#line 272 "texts.mod"
  0xAL, sizeof(pOt_CHAR)
#line 272 "texts.mod"
};
#line 272 "texts.mod"

#line 272 "texts.mod"

#line 272 "texts.mod"
extern void pOt_WriteHex_Texts
#line 272 "texts.mod"
#if pOt__ANSI_C
#line 272 "texts.mod"
  (struct pOt__tag_5_Texts *pOt_W, pOt_LONGINT pOt_x)
#line 272 "texts.mod"
#else
#line 272 "texts.mod"
  (pOt_W, pOt_x)
#line 272 "texts.mod"
  struct pOt__tag_5_Texts *pOt_W;
#line 272 "texts.mod"
  pOt_LONGINT pOt_x;
#line 272 "texts.mod"

#line 272 "texts.mod"
#endif
#line 272 "texts.mod"
{
#line 272 "texts.mod"
  pOt_INTEGER pOt_i;
#line 272 "texts.mod"
  pOt_LONGINT pOt_y;
#line 272 "texts.mod"
  struct pOt__tag_8_Texts pOt_a;
#line 272 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 272 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 272 "texts.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_a,(pOt__TypDsc*)&pOt__td_8_Texts);
#line 272 "texts.mod"

#line 272 "texts.mod"
  pOt_i=(pOt_INTEGER)(0);
#line 272 "texts.mod"
  pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),' ');
#line 272 "texts.mod"
  for(;;) {
    pOt_y=(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_x),(pOt_LONGINT)(16),6));
#line 273 "texts.mod"
    if(( pOt_y<((pOt_LONGINT)(10)))) {
      pOt_a.arr[pOt__inxchk(__FILE__,__LINE__,0xA, pOt_i)]=(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_y),(pOt_LONGINT)(48),6)));
#line 274 "texts.mod"
    } else {
#line 274 "texts.mod"
      pOt_a.arr[pOt__inxchk(__FILE__,__LINE__,0xA, pOt_i)]=(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_y),(pOt_LONGINT)(55),6)));
#line 274 "texts.mod"
    }
#line 274 "texts.mod"
    pOt_x=(pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_x),(pOt_LONGINT)(16),6));
    pOt_i+=(1);
    if(( pOt_i==((pOt_INTEGER)(8)))) break;
#line 276 "texts.mod"
  }
#line 276 "texts.mod"
  for(;;) {
    pOt_i-=(1);
#line 277 "texts.mod"
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt_a.arr[pOt__inxchk(__FILE__,__LINE__,0xA, pOt_i)]);
#line 277 "texts.mod"
    if(( pOt_i==((pOt_INTEGER)(0)))) break;
  }
#line 278 "texts.mod"

#line 278 "texts.mod"
pOt__Epilogue:;
#line 278 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 278 "texts.mod"
}
#line 278 "texts.mod"

#line 278 "texts.mod"

#line 283 "texts.mod"
struct pOt__tag_9_Texts {
#line 283 "texts.mod"
  pOt__ArrTypDsc *td;
#line 283 "texts.mod"
  pOt_CHAR arr[0x9L];
#line 283 "texts.mod"
} ;
#line 283 "texts.mod"
static pOt__ArrTypDsc pOt__td_9_Texts= {
#line 283 "texts.mod"
  1,
#line 283 "texts.mod"
  0x9L, sizeof(pOt_CHAR)
#line 283 "texts.mod"
};
#line 283 "texts.mod"

#line 283 "texts.mod"

#line 283 "texts.mod"
extern void pOt_WriteReal_Texts
#line 283 "texts.mod"
#if pOt__ANSI_C
#line 283 "texts.mod"
  (struct pOt__tag_5_Texts *pOt_W, pOt_REAL pOt_x, pOt_INTEGER pOt_n)
#line 283 "texts.mod"
#else
#line 283 "texts.mod"
  (pOt_W, pOt_x, pOt_n)
#line 283 "texts.mod"
  struct pOt__tag_5_Texts *pOt_W;
#line 283 "texts.mod"
  pOt_REAL pOt_x;
#line 283 "texts.mod"
  pOt_INTEGER pOt_n;
#line 283 "texts.mod"

#line 283 "texts.mod"
#endif
#line 283 "texts.mod"
{
#line 283 "texts.mod"
  pOt_INTEGER pOt_e;
#line 283 "texts.mod"
  pOt_REAL pOt_x0;
#line 283 "texts.mod"
  struct pOt__tag_9_Texts pOt_d;
#line 283 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 283 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 283 "texts.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_d,(pOt__TypDsc*)&pOt__td_9_Texts);
#line 283 "texts.mod"

#line 283 "texts.mod"
  pOt_e=(pOt_INTEGER)(pOt_Expo_Reals((pOt_REAL)(pOt_x)));
#line 283 "texts.mod"
  if(( pOt_e==((pOt_INTEGER)(0)))) {
#line 285 "texts.mod"
    pOt_WriteString_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x14L],&pOt__str_td[0x3]))));
#line 285 "texts.mod"
    for(;;) {
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),' ');
#line 286 "texts.mod"
      pOt_n-=(1);
#line 286 "texts.mod"
      if(( pOt_n<=((pOt_INTEGER)(3)))) break;
    }
#line 287 "texts.mod"
  } else if(( pOt_e==255)) {
    pOt_WriteString_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1CL],&pOt__str_td[0x4]))));
#line 288 "texts.mod"
    for(;;) {
      if(( pOt_n>((pOt_INTEGER)(4)))); else break;
#line 289 "texts.mod"
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),' ');
#line 289 "texts.mod"
      pOt_n-=(1);
#line 289 "texts.mod"
    }
#line 289 "texts.mod"
  } else {
#line 291 "texts.mod"
    if(( pOt_n<=((pOt_INTEGER)(9)))) {
#line 291 "texts.mod"
      pOt_n=(pOt_INTEGER)(3);
#line 291 "texts.mod"
    } else {
#line 291 "texts.mod"
      pOt_n-=(6);
#line 291 "texts.mod"
    }
#line 291 "texts.mod"
    for(;;) {
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),' ');
#line 292 "texts.mod"
      pOt_n-=(1);
#line 292 "texts.mod"
      if(( pOt_n<=((pOt_INTEGER)(8)))) break;
#line 292 "texts.mod"
    }
#line 292 "texts.mod"
    if(( pOt_x<(pOt_REAL)0.0)) {
#line 294 "texts.mod"
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'-');
#line 294 "texts.mod"
      pOt_x=(pOt_REAL)(-pOt_x);
#line 294 "texts.mod"
    } else {
#line 294 "texts.mod"
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),' ');
#line 294 "texts.mod"
    }
#line 294 "texts.mod"
    pOt_e=(pOt_INTEGER)((pOt_INTEGER)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)(((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_e),(pOt_LONGINT)(127),5))),(pOt_LONGINT)(77),5)),(pOt_LONGINT)(256),5));
    if(( pOt_e>=((pOt_INTEGER)(0)))) {
      pOt_x=(pOt_REAL)(pOt_x/pOt_Ten_Reals((pOt_INTEGER)(pOt_e)));
#line 296 "texts.mod"
    } else {
#line 296 "texts.mod"
      pOt_x=(pOt_REAL)(pOt_Ten_Reals((pOt_INTEGER)(-pOt_e))*pOt_x);
#line 296 "texts.mod"
    }
#line 296 "texts.mod"
    if(( pOt_x>=(pOt_REAL)1.0000000E1)) {
      pOt_x=(pOt_REAL)((pOt_REAL)1.0000000E-1*pOt_x);
#line 297 "texts.mod"
      pOt_e+=(1);
#line 297 "texts.mod"
    }
#line 297 "texts.mod"
    pOt_x0=(pOt_REAL)(pOt_Ten_Reals((pOt_INTEGER)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(1),5))));
    pOt_x=(pOt_REAL)(pOt_x0*pOt_x+(pOt_REAL)5.0000000E-1);
#line 298 "texts.mod"
    if(( pOt_x>=(pOt_REAL)1.0000000E1*pOt_x0)) {
      pOt_x=(pOt_REAL)(pOt_x*(pOt_REAL)1.0000000E-1);
#line 299 "texts.mod"
      pOt_e+=(1);
#line 299 "texts.mod"
    }
#line 299 "texts.mod"
    pOt_Convert_Reals((pOt_REAL)(pOt_x),(pOt_INTEGER)(pOt_n),(pOt__ArrTypDsc**)&pOt_d);
    pOt_n-=(1);
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x9, pOt_n)]);
#line 301 "texts.mod"
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'.');
#line 301 "texts.mod"
    for(;;) {
      pOt_n-=(1);
#line 302 "texts.mod"
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x9, pOt_n)]);
#line 302 "texts.mod"
      if(( pOt_n==((pOt_INTEGER)(0)))) break;
#line 302 "texts.mod"
    }
#line 302 "texts.mod"
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'E');
    if(( pOt_e<((pOt_INTEGER)(0)))) {
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'-');
#line 304 "texts.mod"
      pOt_e=(pOt_INTEGER)(-pOt_e);
#line 304 "texts.mod"
    } else {
#line 304 "texts.mod"
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'+');
#line 304 "texts.mod"
    }
#line 304 "texts.mod"
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_e),(pOt_LONGINT)(10),5)),(pOt_LONGINT)(48),5))));
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_e),(pOt_LONGINT)(10),5)),(pOt_LONGINT)(48),5))));
  }
#line 306 "texts.mod"

pOt__Epilogue:;
#line 307 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 307 "texts.mod"
}
#line 307 "texts.mod"

#line 307 "texts.mod"

#line 313 "texts.mod"
struct pOt__tag_A_Texts {
#line 313 "texts.mod"
  pOt__ArrTypDsc *td;
#line 313 "texts.mod"
  pOt_CHAR arr[0x9L];
#line 313 "texts.mod"
} ;
#line 313 "texts.mod"
static pOt__ArrTypDsc pOt__td_A_Texts= {
#line 313 "texts.mod"
  1,
#line 313 "texts.mod"
  0x9L, sizeof(pOt_CHAR)
#line 313 "texts.mod"
};
#line 313 "texts.mod"

#line 313 "texts.mod"
static struct pOt__tag_5_Texts *pOt_W_WriteRealFix_Texts;
#line 313 "texts.mod"
static pOt_REAL (*pOt_x_WriteRealFix_Texts);
#line 313 "texts.mod"
static pOt_INTEGER (*pOt_n_WriteRealFix_Texts), (*pOt_k_WriteRealFix_Texts), (*pOt_e_WriteRealFix_Texts), (*pOt_i_WriteRealFix_Texts);
#line 313 "texts.mod"
static pOt_CHAR (*pOt_sign_WriteRealFix_Texts);
#line 313 "texts.mod"
static pOt_REAL (*pOt_x0_WriteRealFix_Texts);
#line 313 "texts.mod"
static struct pOt__tag_A_Texts (*pOt_d_WriteRealFix_Texts);
#line 313 "texts.mod"

#line 313 "texts.mod"
extern void pOt_WriteRealFix_Texts pOt__ARGS((struct pOt__tag_5_Texts *, pOt_REAL , pOt_INTEGER , pOt_INTEGER ));
#line 313 "texts.mod"

#line 313 "texts.mod"


#line 314 "texts.mod"

#line 314 "texts.mod"
static void pOt_seq_WriteRealFix_Texts
#line 314 "texts.mod"
#if pOt__ANSI_C
#line 314 "texts.mod"
  (pOt_CHAR pOt_ch, pOt_INTEGER pOt_n)
#line 314 "texts.mod"
#else
#line 314 "texts.mod"
  (pOt_ch, pOt_n)
#line 314 "texts.mod"
  pOt_CHAR pOt_ch;
#line 314 "texts.mod"
  pOt_INTEGER pOt_n;
#line 314 "texts.mod"

#line 314 "texts.mod"
#endif
#line 314 "texts.mod"
{
#line 314 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 314 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 314 "texts.mod"

#line 314 "texts.mod"
  for(;;) {
#line 314 "texts.mod"
    if(( pOt_n>((pOt_INTEGER)(0)))); else break;
#line 314 "texts.mod"
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W_WriteRealFix_Texts),pOt_ch);
#line 314 "texts.mod"
    pOt_n-=(1);
#line 314 "texts.mod"
  }
#line 314 "texts.mod"

pOt__Epilogue:;
#line 315 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 315 "texts.mod"
}
#line 315 "texts.mod"

#line 315 "texts.mod"

#line 318 "texts.mod"

#line 318 "texts.mod"

#line 318 "texts.mod"
static void pOt_dig_WriteRealFix_Texts
#line 318 "texts.mod"
#if pOt__ANSI_C
#line 318 "texts.mod"
  (pOt_INTEGER pOt_n)
#line 318 "texts.mod"
#else
#line 318 "texts.mod"
  (pOt_n)
#line 318 "texts.mod"
  pOt_INTEGER pOt_n;
#line 318 "texts.mod"

#line 318 "texts.mod"
#endif
#line 318 "texts.mod"
{
#line 318 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 318 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 318 "texts.mod"

#line 318 "texts.mod"
  for(;;) {
    if(( pOt_n>((pOt_INTEGER)(0)))); else break;
#line 319 "texts.mod"
    (*pOt_i_WriteRealFix_Texts)-=(1);
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W_WriteRealFix_Texts),(*pOt_d_WriteRealFix_Texts).arr[pOt__inxchk(__FILE__,__LINE__,0x9, (*pOt_i_WriteRealFix_Texts))]);
#line 320 "texts.mod"
    pOt_n-=(1);
  }
#line 321 "texts.mod"

pOt__Epilogue:;
#line 322 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 322 "texts.mod"
}
#line 322 "texts.mod"

#line 322 "texts.mod"
extern void pOt_WriteRealFix_Texts
#line 324 "texts.mod"
#if pOt__ANSI_C
#line 324 "texts.mod"
  (struct pOt__tag_5_Texts *pOt_W, pOt_REAL pOt_x, pOt_INTEGER pOt_n, pOt_INTEGER pOt_k)
#line 324 "texts.mod"
#else
#line 324 "texts.mod"
  (pOt_W, pOt_x, pOt_n, pOt_k)
#line 324 "texts.mod"
  struct pOt__tag_5_Texts *pOt_W;
#line 324 "texts.mod"
  pOt_REAL pOt_x;
#line 324 "texts.mod"
  pOt_INTEGER pOt_n, pOt_k;
#line 324 "texts.mod"

#line 324 "texts.mod"
#endif
#line 324 "texts.mod"
{
#line 324 "texts.mod"
  struct pOt__tag_5_Texts *pOt_W_;
#line 324 "texts.mod"
  pOt_REAL (*pOt_x_);
#line 324 "texts.mod"
  pOt_INTEGER (*pOt_n_), (*pOt_k_), pOt_e, (*pOt_e_), pOt_i, (*pOt_i_);
#line 324 "texts.mod"
  pOt_CHAR pOt_sign, (*pOt_sign_);
#line 324 "texts.mod"
  pOt_REAL pOt_x0, (*pOt_x0_);
#line 324 "texts.mod"
  struct pOt__tag_A_Texts pOt_d, (*pOt_d_);
#line 324 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 324 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 324 "texts.mod"
  pOt_W_=pOt_W_WriteRealFix_Texts;
#line 324 "texts.mod"
  pOt_W_WriteRealFix_Texts=pOt_W;
#line 324 "texts.mod"
  pOt_x_=pOt_x_WriteRealFix_Texts;
#line 324 "texts.mod"
  pOt_x_WriteRealFix_Texts=&pOt_x;
#line 324 "texts.mod"
  pOt_n_=pOt_n_WriteRealFix_Texts;
#line 324 "texts.mod"
  pOt_n_WriteRealFix_Texts=&pOt_n;
#line 324 "texts.mod"
  pOt_k_=pOt_k_WriteRealFix_Texts;
#line 324 "texts.mod"
  pOt_k_WriteRealFix_Texts=&pOt_k;
#line 324 "texts.mod"
  pOt_e_=pOt_e_WriteRealFix_Texts;
#line 324 "texts.mod"
  pOt_e_WriteRealFix_Texts=&pOt_e;
#line 324 "texts.mod"
  pOt_i_=pOt_i_WriteRealFix_Texts;
#line 324 "texts.mod"
  pOt_i_WriteRealFix_Texts=&pOt_i;
#line 324 "texts.mod"
  pOt_sign_=pOt_sign_WriteRealFix_Texts;
#line 324 "texts.mod"
  pOt_sign_WriteRealFix_Texts=&pOt_sign;
#line 324 "texts.mod"
  pOt_x0_=pOt_x0_WriteRealFix_Texts;
#line 324 "texts.mod"
  pOt_x0_WriteRealFix_Texts=&pOt_x0;
#line 324 "texts.mod"
  pOt_d_=pOt_d_WriteRealFix_Texts;
#line 324 "texts.mod"
  pOt_d_WriteRealFix_Texts=&pOt_d;
#line 324 "texts.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_d,(pOt__TypDsc*)&pOt__td_A_Texts);
#line 324 "texts.mod"

#line 324 "texts.mod"
  pOt_e=(pOt_INTEGER)(pOt_Expo_Reals((pOt_REAL)(pOt_x)));
#line 324 "texts.mod"
  if(( pOt_k<((pOt_INTEGER)(0)))) {
    pOt_k=(pOt_INTEGER)(0);
#line 325 "texts.mod"
  }
#line 325 "texts.mod"
  if(( pOt_e==((pOt_INTEGER)(0)))) {
    pOt_seq_WriteRealFix_Texts(' ',(pOt_INTEGER)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(pOt_k),5)),(pOt_LONGINT)(2),5)));
#line 326 "texts.mod"
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'0');
#line 326 "texts.mod"
    pOt_seq_WriteRealFix_Texts(' ',(pOt_INTEGER)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_k),(pOt_LONGINT)(1),5)));
  } else if(( pOt_e==255)) {
#line 327 "texts.mod"
    pOt_WriteString_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1CL],&pOt__str_td[0x4]))));
#line 327 "texts.mod"
    pOt_seq_WriteRealFix_Texts(' ',(pOt_INTEGER)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(4),5)));
  } else {
#line 328 "texts.mod"
    pOt_e=(pOt_INTEGER)((pOt_INTEGER)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)(((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_e),(pOt_LONGINT)(127),5))),(pOt_LONGINT)(77),5)),(pOt_LONGINT)(256),5));
#line 328 "texts.mod"
    if(( pOt_x<((pOt_REAL)(0)))) {
      pOt_sign='-';
#line 329 "texts.mod"
      pOt_x=(pOt_REAL)(-pOt_x);
#line 329 "texts.mod"
    } else {
#line 329 "texts.mod"
      pOt_sign=' ';
#line 329 "texts.mod"
    }
#line 329 "texts.mod"
    if(( pOt_e>=((pOt_INTEGER)(0)))) {
      pOt_x=(pOt_REAL)(pOt_x/pOt_Ten_Reals((pOt_INTEGER)(pOt_e)));
    } else {
#line 331 "texts.mod"
      pOt_x=(pOt_REAL)(pOt_Ten_Reals((pOt_INTEGER)(-pOt_e))*pOt_x);
    }
#line 332 "texts.mod"
    if(( pOt_x>=(pOt_REAL)1.0000000E1)) {
      pOt_x=(pOt_REAL)((pOt_REAL)1.0000000E-1*pOt_x);
#line 333 "texts.mod"
      pOt_e+=(1);
#line 333 "texts.mod"
    }
#line 333 "texts.mod"
    if(( (pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_k),(pOt_LONGINT)(pOt_e),5)>=((pOt_INTEGER)(8)))) {
#line 335 "texts.mod"
      pOt_k=(pOt_INTEGER)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_SHORTINT)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(9),(pOt_LONGINT)(1),4)),(pOt_LONGINT)(pOt_e),5));
    } else if(( (pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_k),(pOt_LONGINT)(pOt_e),5)<((pOt_INTEGER)(0)))) {
#line 336 "texts.mod"
      pOt_k=(pOt_INTEGER)(-pOt_e);
#line 336 "texts.mod"
      pOt_x=(pOt_REAL)((pOt_REAL)0.0);
    }
#line 337 "texts.mod"
    pOt_x0=(pOt_REAL)(pOt_Ten_Reals((pOt_INTEGER)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_k),(pOt_LONGINT)(pOt_e),5))));
    pOt_x=(pOt_REAL)(pOt_x0*pOt_x+(pOt_REAL)5.0000000E-1);
#line 338 "texts.mod"
    if(( pOt_x>=(pOt_REAL)1.0000000E1*pOt_x0)) {
      pOt_e+=(1);
#line 339 "texts.mod"
    }
#line 339 "texts.mod"
    pOt_e+=(1);
#line 341 "texts.mod"
    pOt_i=(pOt_INTEGER)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_k),(pOt_LONGINT)(pOt_e),5));
#line 341 "texts.mod"
    pOt_Convert_Reals((pOt_REAL)(pOt_x),(pOt_INTEGER)(pOt_i),(pOt__ArrTypDsc**)&pOt_d);
#line 341 "texts.mod"
    if(( pOt_e>((pOt_INTEGER)(0)))) {
#line 343 "texts.mod"
      pOt_seq_WriteRealFix_Texts(' ',(pOt_INTEGER)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(pOt_e),5)),(pOt_LONGINT)(pOt_k),5)),(pOt_LONGINT)(2),5)));
#line 343 "texts.mod"
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt_sign);
#line 343 "texts.mod"
      pOt_dig_WriteRealFix_Texts((pOt_INTEGER)(pOt_e));
#line 343 "texts.mod"
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'.');
      pOt_dig_WriteRealFix_Texts((pOt_INTEGER)(pOt_k));
    } else {
#line 345 "texts.mod"
      pOt_seq_WriteRealFix_Texts(' ',(pOt_INTEGER)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(pOt_k),5)),(pOt_LONGINT)(3),5)));
#line 345 "texts.mod"
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt_sign);
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'0');
#line 346 "texts.mod"
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'.');
#line 346 "texts.mod"
      pOt_seq_WriteRealFix_Texts('0',(pOt_INTEGER)(-pOt_e));
      pOt_dig_WriteRealFix_Texts((pOt_INTEGER)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_k),(pOt_LONGINT)(pOt_e),5)));
    }
#line 348 "texts.mod"
  }

pOt__Epilogue:;
#line 350 "texts.mod"
  pOt_W_WriteRealFix_Texts=pOt_W_;
#line 350 "texts.mod"
  pOt_x_WriteRealFix_Texts=pOt_x_;
#line 350 "texts.mod"
  pOt_n_WriteRealFix_Texts=pOt_n_;
#line 350 "texts.mod"
  pOt_k_WriteRealFix_Texts=pOt_k_;
#line 350 "texts.mod"
  pOt_e_WriteRealFix_Texts=pOt_e_;
#line 350 "texts.mod"
  pOt_i_WriteRealFix_Texts=pOt_i_;
#line 350 "texts.mod"
  pOt_sign_WriteRealFix_Texts=pOt_sign_;
#line 350 "texts.mod"
  pOt_x0_WriteRealFix_Texts=pOt_x0_;
#line 350 "texts.mod"
  pOt_d_WriteRealFix_Texts=pOt_d_;
#line 350 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 350 "texts.mod"
}
#line 350 "texts.mod"

#line 350 "texts.mod"

#line 355 "texts.mod"
struct pOt__tag_B_Texts {
#line 355 "texts.mod"
  pOt__ArrTypDsc *td;
#line 355 "texts.mod"
  pOt_CHAR arr[0x8L];
#line 355 "texts.mod"
} ;
#line 355 "texts.mod"
static pOt__ArrTypDsc pOt__td_B_Texts= {
#line 355 "texts.mod"
  1,
#line 355 "texts.mod"
  0x8L, sizeof(pOt_CHAR)
#line 355 "texts.mod"
};
#line 355 "texts.mod"

#line 355 "texts.mod"

#line 355 "texts.mod"
extern void pOt_WriteRealHex_Texts
#line 355 "texts.mod"
#if pOt__ANSI_C
#line 355 "texts.mod"
  (struct pOt__tag_5_Texts *pOt_W, pOt_REAL pOt_x)
#line 355 "texts.mod"
#else
#line 355 "texts.mod"
  (pOt_W, pOt_x)
#line 355 "texts.mod"
  struct pOt__tag_5_Texts *pOt_W;
#line 355 "texts.mod"
  pOt_REAL pOt_x;
#line 355 "texts.mod"

#line 355 "texts.mod"
#endif
#line 355 "texts.mod"
{
#line 355 "texts.mod"
  pOt_INTEGER pOt_i;
#line 355 "texts.mod"
  struct pOt__tag_B_Texts pOt_d;
#line 355 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 355 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 355 "texts.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_d,(pOt__TypDsc*)&pOt__td_B_Texts);
#line 355 "texts.mod"

#line 355 "texts.mod"
  pOt_ConvertH_Reals((pOt_REAL)(pOt_x),(pOt__ArrTypDsc**)&pOt_d);
#line 355 "texts.mod"
  pOt_i=(pOt_INTEGER)(0);
#line 355 "texts.mod"
  for(;;) {
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x8, pOt_i)]);
#line 356 "texts.mod"
    pOt_i+=(1);
#line 356 "texts.mod"
    if(( pOt_i==((pOt_INTEGER)(8)))) break;
  }
#line 357 "texts.mod"

#line 357 "texts.mod"
pOt__Epilogue:;
#line 357 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 357 "texts.mod"
}
#line 357 "texts.mod"

#line 357 "texts.mod"

#line 363 "texts.mod"
struct pOt__tag_C_Texts {
#line 363 "texts.mod"
  pOt__ArrTypDsc *td;
#line 363 "texts.mod"
  pOt_CHAR arr[0x10L];
#line 363 "texts.mod"
} ;
#line 363 "texts.mod"
static pOt__ArrTypDsc pOt__td_C_Texts= {
#line 363 "texts.mod"
  1,
#line 363 "texts.mod"
  0x10L, sizeof(pOt_CHAR)
#line 363 "texts.mod"
};
#line 363 "texts.mod"

#line 363 "texts.mod"

#line 363 "texts.mod"
extern void pOt_WriteLongReal_Texts
#line 363 "texts.mod"
#if pOt__ANSI_C
#line 363 "texts.mod"
  (struct pOt__tag_5_Texts *pOt_W, pOt_LONGREAL pOt_x, pOt_INTEGER pOt_n)
#line 363 "texts.mod"
#else
#line 363 "texts.mod"
  (pOt_W, pOt_x, pOt_n)
#line 363 "texts.mod"
  struct pOt__tag_5_Texts *pOt_W;
#line 363 "texts.mod"
  pOt_LONGREAL pOt_x;
#line 363 "texts.mod"
  pOt_INTEGER pOt_n;
#line 363 "texts.mod"

#line 363 "texts.mod"
#endif
#line 363 "texts.mod"
{
#line 363 "texts.mod"
  pOt_INTEGER pOt_e;
#line 363 "texts.mod"
  pOt_LONGREAL pOt_x0;
#line 363 "texts.mod"
  struct pOt__tag_C_Texts pOt_d;
#line 363 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 363 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 363 "texts.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_d,(pOt__TypDsc*)&pOt__td_C_Texts);
#line 363 "texts.mod"

#line 363 "texts.mod"
  pOt_e=(pOt_INTEGER)(pOt_ExpoL_Reals((pOt_LONGREAL)(pOt_x)));
#line 363 "texts.mod"
  if(( pOt_e==((pOt_INTEGER)(0)))) {
#line 365 "texts.mod"
    pOt_WriteString_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x14L],&pOt__str_td[0x3]))));
#line 365 "texts.mod"
    for(;;) {
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),' ');
#line 366 "texts.mod"
      pOt_n-=(1);
#line 366 "texts.mod"
      if(( pOt_n<=((pOt_INTEGER)(3)))) break;
    }
#line 367 "texts.mod"
  } else if(( pOt_e==2047)) {
    pOt_WriteString_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1CL],&pOt__str_td[0x4]))));
#line 368 "texts.mod"
    for(;;) {
      if(( pOt_n>((pOt_INTEGER)(4)))); else break;
#line 369 "texts.mod"
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),' ');
#line 369 "texts.mod"
      pOt_n-=(1);
#line 369 "texts.mod"
    }
#line 369 "texts.mod"
  } else {
#line 371 "texts.mod"
    if(( pOt_n<=((pOt_INTEGER)(10)))) {
#line 371 "texts.mod"
      pOt_n=(pOt_INTEGER)(3);
#line 371 "texts.mod"
    } else {
#line 371 "texts.mod"
      pOt_n-=(7);
#line 371 "texts.mod"
    }
#line 371 "texts.mod"
    for(;;) {
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),' ');
#line 372 "texts.mod"
      pOt_n-=(1);
#line 372 "texts.mod"
      if(( pOt_n<=((pOt_INTEGER)(16)))) break;
#line 372 "texts.mod"
    }
#line 372 "texts.mod"
    if(( pOt_x<((pOt_LONGREAL)(0)))) {
#line 374 "texts.mod"
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'-');
#line 374 "texts.mod"
      pOt_x=(pOt_LONGREAL)(-pOt_x);
#line 374 "texts.mod"
    } else {
#line 374 "texts.mod"
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),' ');
#line 374 "texts.mod"
    }
#line 374 "texts.mod"
    pOt_e=(pOt_INTEGER)((pOt_LONGINT)pOt__rngchk_i(__FILE__,__LINE__,(pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_e),(pOt_LONGINT)(1023),5))),(pOt_LONGINT)(77),6)),(pOt_LONGINT)(256),6)));
    if(( pOt_e>=((pOt_INTEGER)(0)))) {
      pOt_x=(pOt_LONGREAL)(pOt_x/pOt_TenL_Reals((pOt_INTEGER)(pOt_e)));
#line 376 "texts.mod"
    } else {
#line 376 "texts.mod"
      pOt_x=(pOt_LONGREAL)(pOt_TenL_Reals((pOt_INTEGER)(-pOt_e))*pOt_x);
#line 376 "texts.mod"
    }
#line 376 "texts.mod"
    if(( pOt_x>=1.000000000000000E1)) {
      pOt_x=(pOt_LONGREAL)(1.000000000000000E-1*pOt_x);
#line 377 "texts.mod"
      pOt_e+=(1);
#line 377 "texts.mod"
    }
#line 377 "texts.mod"
    pOt_x0=(pOt_LONGREAL)(pOt_TenL_Reals((pOt_INTEGER)((pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_n),(pOt_LONGINT)(1),5))));
    pOt_x=(pOt_LONGREAL)(pOt_x0*pOt_x+5.000000000000000E-1);
#line 378 "texts.mod"
    if(( pOt_x>=1.000000000000000E1*pOt_x0)) {
      pOt_x=(pOt_LONGREAL)(1.000000000000000E-1*pOt_x);
#line 379 "texts.mod"
      pOt_e+=(1);
#line 379 "texts.mod"
    }
#line 379 "texts.mod"
    pOt_ConvertL_Reals((pOt_LONGREAL)(pOt_x),(pOt_INTEGER)(pOt_n),(pOt__ArrTypDsc**)&pOt_d);
    pOt_n-=(1);
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x10, pOt_n)]);
#line 381 "texts.mod"
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'.');
#line 381 "texts.mod"
    for(;;) {
      pOt_n-=(1);
#line 382 "texts.mod"
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x10, pOt_n)]);
#line 382 "texts.mod"
      if(( pOt_n==((pOt_INTEGER)(0)))) break;
#line 382 "texts.mod"
    }
#line 382 "texts.mod"
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'D');
    if(( pOt_e<((pOt_INTEGER)(0)))) {
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'-');
#line 384 "texts.mod"
      pOt_e=(pOt_INTEGER)(-pOt_e);
#line 384 "texts.mod"
    } else {
#line 384 "texts.mod"
      pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),'+');
#line 384 "texts.mod"
    }
#line 384 "texts.mod"
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_e),(pOt_LONGINT)(100),5)),(pOt_LONGINT)(48),5))));
    pOt_e=(pOt_INTEGER)((pOt_INTEGER)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_e),(pOt_LONGINT)(100),5));
#line 385 "texts.mod"
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_e),(pOt_LONGINT)(10),5)),(pOt_LONGINT)(48),5))));
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_e),(pOt_LONGINT)(10),5)),(pOt_LONGINT)(48),5))));
#line 388 "texts.mod"
  }
#line 388 "texts.mod"

pOt__Epilogue:;
#line 389 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 389 "texts.mod"
}
#line 389 "texts.mod"

#line 389 "texts.mod"

#line 394 "texts.mod"
struct pOt__tag_D_Texts {
#line 394 "texts.mod"
  pOt__ArrTypDsc *td;
#line 394 "texts.mod"
  pOt_CHAR arr[0x10L];
#line 394 "texts.mod"
} ;
#line 394 "texts.mod"
static pOt__ArrTypDsc pOt__td_D_Texts= {
#line 394 "texts.mod"
  1,
#line 394 "texts.mod"
  0x10L, sizeof(pOt_CHAR)
#line 394 "texts.mod"
};
#line 394 "texts.mod"

#line 394 "texts.mod"

#line 394 "texts.mod"
extern void pOt_WriteLongRealHex_Texts
#line 394 "texts.mod"
#if pOt__ANSI_C
#line 394 "texts.mod"
  (struct pOt__tag_5_Texts *pOt_W, pOt_LONGREAL pOt_x)
#line 394 "texts.mod"
#else
#line 394 "texts.mod"
  (pOt_W, pOt_x)
#line 394 "texts.mod"
  struct pOt__tag_5_Texts *pOt_W;
#line 394 "texts.mod"
  pOt_LONGREAL pOt_x;
#line 394 "texts.mod"

#line 394 "texts.mod"
#endif
#line 394 "texts.mod"
{
#line 394 "texts.mod"
  pOt_INTEGER pOt_i;
#line 394 "texts.mod"
  struct pOt__tag_D_Texts pOt_d;
#line 394 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 394 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 394 "texts.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_d,(pOt__TypDsc*)&pOt__td_D_Texts);
#line 394 "texts.mod"

#line 394 "texts.mod"
  pOt_ConvertHL_Reals((pOt_LONGREAL)(pOt_x),(pOt__ArrTypDsc**)&pOt_d);
#line 394 "texts.mod"
  pOt_i=(pOt_INTEGER)(0);
#line 394 "texts.mod"
  for(;;) {
    pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W),pOt_d.arr[pOt__inxchk(__FILE__,__LINE__,0x10, pOt_i)]);
#line 395 "texts.mod"
    pOt_i+=(1);
#line 395 "texts.mod"
    if(( pOt_i==((pOt_INTEGER)(16)))) break;
  }
#line 396 "texts.mod"

#line 396 "texts.mod"
pOt__Epilogue:;
#line 396 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 396 "texts.mod"
}
#line 396 "texts.mod"

#line 396 "texts.mod"

#line 400 "texts.mod"

#line 400 "texts.mod"
static struct pOt__tag_5_Texts *pOt_W_WriteDate_Texts;
#line 400 "texts.mod"
static pOt_LONGINT (*pOt_t_WriteDate_Texts), (*pOt_d_WriteDate_Texts);
#line 400 "texts.mod"

#line 400 "texts.mod"
extern void pOt_WriteDate_Texts pOt__ARGS((struct pOt__tag_5_Texts *, pOt_LONGINT , pOt_LONGINT ));
#line 400 "texts.mod"

#line 400 "texts.mod"


#line 401 "texts.mod"

#line 401 "texts.mod"
static void pOt_WritePair_WriteDate_Texts
#line 401 "texts.mod"
#if pOt__ANSI_C
#line 401 "texts.mod"
  (pOt_CHAR pOt_ch, pOt_LONGINT pOt_x)
#line 401 "texts.mod"
#else
#line 401 "texts.mod"
  (pOt_ch, pOt_x)
#line 401 "texts.mod"
  pOt_CHAR pOt_ch;
#line 401 "texts.mod"
  pOt_LONGINT pOt_x;
#line 401 "texts.mod"

#line 401 "texts.mod"
#endif
#line 401 "texts.mod"
{
#line 401 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 401 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 401 "texts.mod"

#line 401 "texts.mod"
  pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W_WriteDate_Texts),pOt_ch);
#line 401 "texts.mod"
  pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W_WriteDate_Texts),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_x),(pOt_LONGINT)(10),6)),(pOt_LONGINT)(48),6))));
  pOt_Write_Texts((struct pOt__tag_5_Texts*)&(*pOt_W_WriteDate_Texts),(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_x),(pOt_LONGINT)(10),6)),(pOt_LONGINT)(48),6))));

#line 403 "texts.mod"
pOt__Epilogue:;
#line 403 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 403 "texts.mod"
}
#line 403 "texts.mod"

#line 403 "texts.mod"
extern void pOt_WriteDate_Texts
#line 405 "texts.mod"
#if pOt__ANSI_C
#line 405 "texts.mod"
  (struct pOt__tag_5_Texts *pOt_W, pOt_LONGINT pOt_t, pOt_LONGINT pOt_d)
#line 405 "texts.mod"
#else
#line 405 "texts.mod"
  (pOt_W, pOt_t, pOt_d)
#line 405 "texts.mod"
  struct pOt__tag_5_Texts *pOt_W;
#line 405 "texts.mod"
  pOt_LONGINT pOt_t, pOt_d;
#line 405 "texts.mod"

#line 405 "texts.mod"
#endif
#line 405 "texts.mod"
{
#line 405 "texts.mod"
  struct pOt__tag_5_Texts *pOt_W_;
#line 405 "texts.mod"
  pOt_LONGINT (*pOt_t_), (*pOt_d_);
#line 405 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 405 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 405 "texts.mod"
  pOt_W_=pOt_W_WriteDate_Texts;
#line 405 "texts.mod"
  pOt_W_WriteDate_Texts=pOt_W;
#line 405 "texts.mod"
  pOt_t_=pOt_t_WriteDate_Texts;
#line 405 "texts.mod"
  pOt_t_WriteDate_Texts=&pOt_t;
#line 405 "texts.mod"
  pOt_d_=pOt_d_WriteDate_Texts;
#line 405 "texts.mod"
  pOt_d_WriteDate_Texts=&pOt_d;
#line 405 "texts.mod"

#line 405 "texts.mod"
  pOt_WritePair_WriteDate_Texts(' ',(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_d),(pOt_LONGINT)(32),6)));
  pOt_WritePair_WriteDate_Texts('.',(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_d),(pOt_LONGINT)(32),6)),(pOt_LONGINT)(16),6)));
#line 406 "texts.mod"
  pOt_WritePair_WriteDate_Texts('.',(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_d),(pOt_LONGINT)(512),6)),(pOt_LONGINT)(128),6)));
#line 406 "texts.mod"
  pOt_WritePair_WriteDate_Texts(' ',(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_t),(pOt_LONGINT)(4096),6)),(pOt_LONGINT)(32),6)));
  pOt_WritePair_WriteDate_Texts(':',(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__divchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_t),(pOt_LONGINT)(64),6)),(pOt_LONGINT)(64),6)));
#line 407 "texts.mod"
  pOt_WritePair_WriteDate_Texts(':',(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_t),(pOt_LONGINT)(64),6)));

#line 408 "texts.mod"
pOt__Epilogue:;
#line 408 "texts.mod"
  pOt_W_WriteDate_Texts=pOt_W_;
#line 408 "texts.mod"
  pOt_t_WriteDate_Texts=pOt_t_;
#line 408 "texts.mod"
  pOt_d_WriteDate_Texts=pOt_d_;
#line 408 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 408 "texts.mod"
}
#line 408 "texts.mod"

#line 408 "texts.mod"

#line 411 "texts.mod"

#line 411 "texts.mod"

#line 411 "texts.mod"
extern void pOt_Open_Texts
#line 411 "texts.mod"
#if pOt__ANSI_C
#line 411 "texts.mod"
  (pOt_File_Files *pOt_T, pOt__DynArr *pOt_name)
#line 411 "texts.mod"
#else
#line 411 "texts.mod"
  (pOt_T, pOt_name)
#line 411 "texts.mod"
  pOt_File_Files *pOt_T;
#line 411 "texts.mod"
  pOt__DynArr *pOt_name;
#line 411 "texts.mod"

#line 411 "texts.mod"
#endif
#line 411 "texts.mod"
{
#line 411 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 411 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 411 "texts.mod"

#line 411 "texts.mod"
  (*pOt_T)=(struct pOt__tag_1_Files*)(pOt_Old_Files(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt_name))));
#line 411 "texts.mod"
  if(( (*pOt_T)==pOt_NIL)) {
    (*pOt_T)=(struct pOt__tag_1_Files*)(pOt_New_Files(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt_name))));
#line 412 "texts.mod"
  }
#line 412 "texts.mod"

pOt__Epilogue:;
#line 413 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 413 "texts.mod"
  pOt__rm_par((pOt__TypDsc**)pOt_name);
#line 413 "texts.mod"
}
#line 413 "texts.mod"

#line 413 "texts.mod"

#line 416 "texts.mod"

#line 416 "texts.mod"

#line 416 "texts.mod"
extern void pOt_Create_Texts
#line 416 "texts.mod"
#if pOt__ANSI_C
#line 416 "texts.mod"
  (pOt_File_Files *pOt_T, pOt__DynArr *pOt_name)
#line 416 "texts.mod"
#else
#line 416 "texts.mod"
  (pOt_T, pOt_name)
#line 416 "texts.mod"
  pOt_File_Files *pOt_T;
#line 416 "texts.mod"
  pOt__DynArr *pOt_name;
#line 416 "texts.mod"

#line 416 "texts.mod"
#endif
#line 416 "texts.mod"
{
#line 416 "texts.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 416 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 416 "texts.mod"

#line 416 "texts.mod"
  (*pOt_T)=(struct pOt__tag_1_Files*)(pOt_New_Files(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt_name))));

#line 417 "texts.mod"
pOt__Epilogue:;
#line 417 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 417 "texts.mod"
  pOt__rm_par((pOt__TypDsc**)pOt_name);
#line 417 "texts.mod"
}
#line 417 "texts.mod"

#line 417 "texts.mod"

#line 420 "texts.mod"

#line 420 "texts.mod"

#line 420 "texts.mod"
extern void pOt_Close_Texts
#line 420 "texts.mod"
#if pOt__ANSI_C
#line 420 "texts.mod"
  (pOt_File_Files pOt_T)
#line 420 "texts.mod"
#else
#line 420 "texts.mod"
  (pOt_T)
#line 420 "texts.mod"
  pOt_File_Files pOt_T;
#line 420 "texts.mod"

#line 420 "texts.mod"
#endif
#line 420 "texts.mod"
{
#line 420 "texts.mod"
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
#line 420 "texts.mod"
  struct {void *next, *vars[0x1];} pOt__gc_strs;
#line 420 "texts.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 420 "texts.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 420 "texts.mod"
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
#line 420 "texts.mod"
  pOt__gc_strs.vars[0x0]=pOt_NIL;
#line 420 "texts.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_T;
#line 420 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 420 "texts.mod"

#line 420 "texts.mod"
  pOt_Close_Files((struct pOt__tag_1_Files*)(pOt_T));

#line 421 "texts.mod"
pOt__Epilogue:;
#line 421 "texts.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 421 "texts.mod"
}
#line 421 "texts.mod"

#line 421 "texts.mod"
void pOt_Texts__body()
#line 423 "texts.mod"
{
#line 423 "texts.mod"
  static int pOt_Texts__loaded=0;
#line 423 "texts.mod"
  if(!pOt_Texts__loaded){
#line 423 "texts.mod"
    pOt_Texts__loaded=1;
#line 423 "texts.mod"

#line 423 "texts.mod"
    pOt_Files__body();
#line 423 "texts.mod"
    pOt_Reals__body();
#line 423 "texts.mod"

#line 423 "texts.mod"
    pOt__gc_ptrs.next=pOt__gc_root;
#line 423 "texts.mod"
    pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 423 "texts.mod"

#line 423 "texts.mod"

#line 423 "texts.mod"

#line 423 "texts.mod"
  pOt__Epilogue:;
#line 423 "texts.mod"
  }
#line 423 "texts.mod"
}
#line 423 "texts.mod"
