/* This code is generated by pOt. */

#include <pOtRTL.h>
#include <math.h>
#include <stdio.h>
  /* some erroneous implementations of assert require stdio to be included */
#include <assert.h>

#include "Reals.hi"

static struct {void *next, *vars[0x1L];} pOt__gc_ptrs = {pOt_NIL,{
  pOt_NIL
}};
static struct {void *next, *vars[0x1L];} pOt__gc_strs = {&pOt__gc_ptrs,{
  pOt_NIL
}};

extern pOt_INTEGER pOt_Expo_Reals(pOt_x) pOt_REAL pOt_x;
{
  pOt_INTEGER pOt__retval;
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  pOt__retval = (pOt_INTEGER)floor(log10(pOt_x)) + 1;
  goto pOt__Epilogue;

  pOt__halt(__FILE__,__LINE__,0x11);
pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
  return pOt__retval;
}

extern pOt_INTEGER pOt_ExpoL_Reals(pOt_x) pOt_LONGREAL pOt_x;
{
  pOt_INTEGER pOt__retval;
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  pOt__retval = (pOt_INTEGER)floor(log10(pOt_x)) + 1;
  goto pOt__Epilogue;

  pOt__halt(__FILE__,__LINE__,0x11);
pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
  return pOt__retval;
}

extern void pOt_SetExpo_Reals(pOt_e, pOt_x)
	pOt_INTEGER pOt_e; pOt_REAL *pOt_x;
{
  pOt_INTEGER pOt_oldexp;
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  pOt_oldexp = pOt_Expo_Reals(*pOt_x);
  *pOt_x *= pow(10.0, pOt_e - pOt_oldexp);
  
pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}

extern void pOt_SetExpoL_Reals(pOt_e, pOt_x)
	pOt_INTEGER pOt_e; pOt_LONGREAL *pOt_x;
{
  pOt_INTEGER pOt_oldexp;
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  pOt_oldexp = pOt_Expo_Reals(*pOt_x);
  *pOt_x *= pow(10.0, pOt_e - pOt_oldexp);

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}



extern pOt_REAL pOt_Ten_Reals(pOt_e) pOt_INTEGER pOt_e;
{
  pOt_REAL pOt__retval;
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  pOt__retval = pow(10.0, pOt_e);
  goto pOt__Epilogue;

  pOt__halt(__FILE__,__LINE__,0x11);
pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
  return pOt__retval;
}



extern pOt_LONGREAL pOt_TenL_Reals(pOt_e) pOt_INTEGER pOt_e;
{
  pOt_LONGREAL pOt__retval;
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  pOt__retval = pow(10.0, pOt_e);
  goto pOt__Epilogue;

  pOt__halt(__FILE__,__LINE__,0x11);
pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
  return pOt__retval;
}



extern void pOt_Convert_Reals(pOt_x, pOt_n, pOt_d)
	pOt_REAL pOt_x; pOt_INTEGER pOt_n; pOt__DynArr *pOt_d;
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  assert(0);

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}



extern void pOt_ConvertL_Reals(pOt_x, pOt_n, pOt_d)
	pOt_LONGREAL pOt_x; pOt_INTEGER pOt_n; pOt__DynArr *pOt_d;
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  assert(0);

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}



extern void pOt_ConvertH_Reals(pOt_x, pOt_d)
	pOt_REAL pOt_x; pOt__DynArr *pOt_d;
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  assert(0);

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}



extern void pOt_ConvertHL_Reals(pOt_x, pOt_d)
	pOt_LONGREAL pOt_x; pOt__DynArr *pOt_d;
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  assert(0);

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}



extern pOt_LONGINT pOt_FSR_Reals()
{
  pOt_LONGINT pOt__retval;
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  assert(0);

  pOt__halt(__FILE__,__LINE__,0x11);
pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
  return pOt__retval;
}



extern void pOt_SetFSR_Reals(pOt_status) pOt_LONGINT pOt_status;
{
  struct {void*next;} pOt__gc_ptrs;
  pOt__gc_ptrs.next = pOt__gc_root;

  assert(0);

pOt__Epilogue:;
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
}

void pOt_Reals__body()
{
  static int pOt_Reals__loaded=0;
  if(!pOt_Reals__loaded){
    pOt_Reals__loaded=1;


    pOt__gc_ptrs.next=pOt__gc_root;
    pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;



  pOt__Epilogue:;
  }
}
