/* This code is generated by pOt. */
#line 25 "files.mod"

#line 25 "files.mod"
#include <pOtRTL.h>
#line 25 "files.mod"

#line 25 "files.mod"
#include "Files.hi"
#line 25 "files.mod"

#line 25 "files.mod"
typedef struct pOt__tag_1_Files *pOt_File_Files;
#line 25 "files.mod"
typedef struct pOt__tag_1_Files pOt_FileDesc_Files;
#line 25 "files.mod"
typedef struct pOt__tag_2_Files pOt_Rider_Files;
#line 25 "files.mod"

#line 25 "files.mod"
struct pOt__tag_0_Files {
#line 25 "files.mod"
  pOt__ArrTypDsc *td;
#line 25 "files.mod"
  pOt_CHAR arr[0x400L];
#line 25 "files.mod"
} ;
#line 25 "files.mod"
pOt__ArrTypDsc pOt__td_0_Files= {
#line 25 "files.mod"
  1,
#line 25 "files.mod"
  0x400L, sizeof(pOt_CHAR)
#line 25 "files.mod"
};
#line 25 "files.mod"
struct pOt__tag_1_Files {
#line 25 "files.mod"
  pOt__RecTypDsc *td;
#line 25 "files.mod"
  struct pOt__tag_0_Files pOt_name;
#line 25 "files.mod"
  pOt_LONGINT pOt_handle, pOt_pos;
#line 25 "files.mod"
} ;
#line 25 "files.mod"
struct {
#line 25 "files.mod"
  pOt_INTEGER mode;
#line 25 "files.mod"
  pOt_LONGINT size;
#line 25 "files.mod"
  pOt_INTEGER extlev, nstr, nptr, npro;
#line 25 "files.mod"
  pOt__RecTypDsc *base_td[pOt__MaxExts];
#line 25 "files.mod"
  struct {pOt_LONGINT poffs; pOt__TypDsc *fld_td;} tab[0x1];
#line 25 "files.mod"
} pOt__td_1_Files= {
#line 25 "files.mod"
  0,
#line 25 "files.mod"
  sizeof(struct pOt__tag_1_Files),
#line 25 "files.mod"
  0x0, 0x1, 0x0, 0x0,
#line 25 "files.mod"
  {pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL},
#line 25 "files.mod"
  {
#line 25 "files.mod"
    {(pOt_LONGINT)&((struct pOt__tag_1_Files*)0)->pOt_name, (pOt__TypDsc*)&pOt__td_0_Files}
#line 25 "files.mod"
  }
#line 25 "files.mod"
};
#line 25 "files.mod"
struct pOt__tag_2_Files {
#line 25 "files.mod"
  pOt__RecTypDsc *td;
#line 25 "files.mod"
  pOt_INTEGER pOt_res;
#line 25 "files.mod"
  pOt_BOOLEAN pOt_eof;
#line 25 "files.mod"
  pOt_LONGINT pOt_pos;
#line 25 "files.mod"
  pOt_File_Files pOt_file;
#line 25 "files.mod"
} ;
#line 25 "files.mod"
struct {
#line 25 "files.mod"
  pOt_INTEGER mode;
#line 25 "files.mod"
  pOt_LONGINT size;
#line 25 "files.mod"
  pOt_INTEGER extlev, nstr, nptr, npro;
#line 25 "files.mod"
  pOt__RecTypDsc *base_td[pOt__MaxExts];
#line 25 "files.mod"
  struct {pOt_LONGINT poffs; pOt__TypDsc *fld_td;} tab[0x1];
#line 25 "files.mod"
} pOt__td_2_Files= {
#line 25 "files.mod"
  0,
#line 25 "files.mod"
  sizeof(struct pOt__tag_2_Files),
#line 25 "files.mod"
  0x0, 0x0, 0x1, 0x0,
#line 25 "files.mod"
  {pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL, pOt_NIL},
#line 25 "files.mod"
  {
#line 25 "files.mod"
    {(pOt_LONGINT)&((struct pOt__tag_2_Files*)0)->pOt_file, pOt_NIL}
#line 25 "files.mod"
  }
#line 25 "files.mod"
};
#line 25 "files.mod"

#line 25 "files.mod"
pOt_File_Files pOt_StdIn_Files, pOt_StdOut_Files, pOt_StdErr_Files;
#line 25 "files.mod"

#line 25 "files.mod"
static struct {void *next, *vars[0x4];} pOt__gc_ptrs = {pOt_NIL,{
#line 25 "files.mod"
  &pOt_StdIn_Files,
#line 25 "files.mod"
  &pOt_StdOut_Files,
#line 25 "files.mod"
  &pOt_StdErr_Files,
#line 25 "files.mod"
  pOt_NIL
#line 25 "files.mod"
}};
#line 25 "files.mod"
static struct {void *next, *vars[0x1];} pOt__gc_strs = {&pOt__gc_ptrs,{
#line 25 "files.mod"
  pOt_NIL
#line 25 "files.mod"
}};
#line 25 "files.mod"

#line 25 "files.mod"

#line 27 "files.mod"

#line 27 "files.mod"

#line 27 "files.mod"
extern pOt_File_Files pOt_Old_Files
#line 27 "files.mod"
#if pOt__ANSI_C
#line 27 "files.mod"
  (pOt__DynArr *pOt_name)
#line 27 "files.mod"
#else
#line 27 "files.mod"
  (pOt_name)
#line 27 "files.mod"
  pOt__DynArr *pOt_name;
#line 27 "files.mod"

#line 27 "files.mod"
#endif
#line 27 "files.mod"
{
#line 27 "files.mod"
  pOt_File_Files pOt__retval;
#line 27 "files.mod"
  pOt_File_Files pOt_f;
#line 27 "files.mod"
  int pOt__gc_enabled_prev;
#line 27 "files.mod"
  pOt__gc_enabled_prev=pOt__gc_enabled;
#line 27 "files.mod"
  pOt__gc_enabled=0;
#line 27 "files.mod"
  pOt_f=pOt_NIL;
#line 27 "files.mod"

#line 27 "files.mod"
  pOt__new(__FILE__,__LINE__,(pOt__TypDsc***)&pOt_f,(pOt__TypDsc*)&pOt__td_1_Files);
#line 27 "files.mod"
  (*((struct pOt__tag_1_Files*)pOt__nilchk(__FILE__,__LINE__,pOt_f))).pOt_handle=(pOt_LONGINT)(0);
#line 27 "files.mod"
  (*((struct pOt__tag_1_Files*)pOt__nilchk(__FILE__,__LINE__,pOt_f))).pOt_pos=(pOt_LONGINT)(0);
#line 27 "files.mod"
  pOt__copychk(__FILE__,__LINE__,(pOt_CHAR*)&(*pOt_name),(pOt_CHAR*)&(*((struct pOt__tag_1_Files*)pOt__nilchk(__FILE__,__LINE__,pOt_f))).pOt_name);
  pOt__retval =(struct pOt__tag_1_Files*)(pOt_f);
  goto pOt__Epilogue;
#line 29 "files.mod"

#line 29 "files.mod"
  pOt__halt(__FILE__,__LINE__,0x11);
#line 29 "files.mod"
pOt__Epilogue:;
#line 29 "files.mod"
  pOt__gc_enabled=pOt__gc_enabled_prev;
#line 29 "files.mod"
  pOt__rm_par((pOt__TypDsc**)pOt_name);
#line 29 "files.mod"
  return pOt__retval;
#line 29 "files.mod"
}
#line 29 "files.mod"

#line 29 "files.mod"

#line 34 "files.mod"

#line 34 "files.mod"

#line 34 "files.mod"
extern pOt_File_Files pOt_New_Files
#line 34 "files.mod"
#if pOt__ANSI_C
#line 34 "files.mod"
  (pOt__DynArr *pOt_name)
#line 34 "files.mod"
#else
#line 34 "files.mod"
  (pOt_name)
#line 34 "files.mod"
  pOt__DynArr *pOt_name;
#line 34 "files.mod"

#line 34 "files.mod"
#endif
#line 34 "files.mod"
{
#line 34 "files.mod"
  pOt_File_Files pOt__retval;
#line 34 "files.mod"
  pOt_File_Files pOt_f;
#line 34 "files.mod"
  int pOt__gc_enabled_prev;
#line 34 "files.mod"
  pOt__gc_enabled_prev=pOt__gc_enabled;
#line 34 "files.mod"
  pOt__gc_enabled=0;
#line 34 "files.mod"
  pOt_f=pOt_NIL;
#line 34 "files.mod"

#line 34 "files.mod"
  pOt__new(__FILE__,__LINE__,(pOt__TypDsc***)&pOt_f,(pOt__TypDsc*)&pOt__td_1_Files);
#line 34 "files.mod"
  (*((struct pOt__tag_1_Files*)pOt__nilchk(__FILE__,__LINE__,pOt_f))).pOt_handle=(pOt_LONGINT)(0);
#line 34 "files.mod"
  (*((struct pOt__tag_1_Files*)pOt__nilchk(__FILE__,__LINE__,pOt_f))).pOt_pos=(pOt_LONGINT)(0);
#line 34 "files.mod"
  pOt__copychk(__FILE__,__LINE__,(pOt_CHAR*)&(*pOt_name),(pOt_CHAR*)&(*((struct pOt__tag_1_Files*)pOt__nilchk(__FILE__,__LINE__,pOt_f))).pOt_name);
  pOt__retval =(struct pOt__tag_1_Files*)(pOt_f);
  goto pOt__Epilogue;
#line 36 "files.mod"

#line 36 "files.mod"
  pOt__halt(__FILE__,__LINE__,0x11);
#line 36 "files.mod"
pOt__Epilogue:;
#line 36 "files.mod"
  pOt__gc_enabled=pOt__gc_enabled_prev;
#line 36 "files.mod"
  pOt__rm_par((pOt__TypDsc**)pOt_name);
#line 36 "files.mod"
  return pOt__retval;
#line 36 "files.mod"
}
#line 36 "files.mod"

#line 36 "files.mod"

#line 42 "files.mod"

#line 42 "files.mod"

#line 42 "files.mod"
extern void pOt_Register_Files
#line 42 "files.mod"
#if pOt__ANSI_C
#line 42 "files.mod"
  (pOt_File_Files pOt_f)
#line 42 "files.mod"
#else
#line 42 "files.mod"
  (pOt_f)
#line 42 "files.mod"
  pOt_File_Files pOt_f;
#line 42 "files.mod"

#line 42 "files.mod"
#endif
#line 42 "files.mod"
{
#line 42 "files.mod"
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
#line 42 "files.mod"
  struct {void *next, *vars[0x1];} pOt__gc_strs;
#line 42 "files.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 42 "files.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 42 "files.mod"
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
#line 42 "files.mod"
  pOt__gc_strs.vars[0x0]=pOt_NIL;
#line 42 "files.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_f;
#line 42 "files.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 42 "files.mod"

#line 42 "files.mod"
  pOt_f=(struct pOt__tag_1_Files*)(pOt_NIL);

#line 43 "files.mod"
pOt__Epilogue:;
#line 43 "files.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 43 "files.mod"
}
#line 43 "files.mod"

#line 43 "files.mod"

#line 46 "files.mod"

#line 46 "files.mod"

#line 46 "files.mod"
extern void pOt_Close_Files
#line 46 "files.mod"
#if pOt__ANSI_C
#line 46 "files.mod"
  (pOt_File_Files pOt_f)
#line 46 "files.mod"
#else
#line 46 "files.mod"
  (pOt_f)
#line 46 "files.mod"
  pOt_File_Files pOt_f;
#line 46 "files.mod"

#line 46 "files.mod"
#endif
#line 46 "files.mod"
{
#line 46 "files.mod"
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
#line 46 "files.mod"
  struct {void *next, *vars[0x1];} pOt__gc_strs;
#line 46 "files.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 46 "files.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 46 "files.mod"
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
#line 46 "files.mod"
  pOt__gc_strs.vars[0x0]=pOt_NIL;
#line 46 "files.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_f;
#line 46 "files.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 46 "files.mod"

#line 46 "files.mod"
  pOt_f=(struct pOt__tag_1_Files*)(pOt_NIL);

#line 47 "files.mod"
pOt__Epilogue:;
#line 47 "files.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 47 "files.mod"
}
#line 47 "files.mod"

#line 47 "files.mod"

#line 50 "files.mod"

#line 50 "files.mod"

#line 50 "files.mod"
extern void pOt_Purge_Files
#line 50 "files.mod"
#if pOt__ANSI_C
#line 50 "files.mod"
  (pOt_File_Files pOt_f)
#line 50 "files.mod"
#else
#line 50 "files.mod"
  (pOt_f)
#line 50 "files.mod"
  pOt_File_Files pOt_f;
#line 50 "files.mod"

#line 50 "files.mod"
#endif
#line 50 "files.mod"
{
#line 50 "files.mod"
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
#line 50 "files.mod"
  struct {void *next, *vars[0x1];} pOt__gc_strs;
#line 50 "files.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 50 "files.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 50 "files.mod"
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
#line 50 "files.mod"
  pOt__gc_strs.vars[0x0]=pOt_NIL;
#line 50 "files.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_f;
#line 50 "files.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 50 "files.mod"

#line 50 "files.mod"
  pOt_f=(struct pOt__tag_1_Files*)(pOt_NIL);

#line 51 "files.mod"
pOt__Epilogue:;
#line 51 "files.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 51 "files.mod"
}
#line 51 "files.mod"

#line 51 "files.mod"

#line 54 "files.mod"

#line 54 "files.mod"

#line 54 "files.mod"
extern pOt_LONGINT pOt_Length_Files
#line 54 "files.mod"
#if pOt__ANSI_C
#line 54 "files.mod"
  (pOt_File_Files pOt_f)
#line 54 "files.mod"
#else
#line 54 "files.mod"
  (pOt_f)
#line 54 "files.mod"
  pOt_File_Files pOt_f;
#line 54 "files.mod"

#line 54 "files.mod"
#endif
#line 54 "files.mod"
{
#line 54 "files.mod"
  pOt_LONGINT pOt__retval;
#line 54 "files.mod"
  int pOt__gc_enabled_prev;
#line 54 "files.mod"
  pOt__gc_enabled_prev=pOt__gc_enabled;
#line 54 "files.mod"
  pOt__gc_enabled=0;
#line 54 "files.mod"

#line 54 "files.mod"

#line 54 "files.mod"
  pOt__halt(__FILE__,__LINE__,0x11);
#line 54 "files.mod"
pOt__Epilogue:;
#line 54 "files.mod"
  pOt__gc_enabled=pOt__gc_enabled_prev;
#line 54 "files.mod"
  return pOt__retval;
#line 54 "files.mod"
}
#line 54 "files.mod"

#line 54 "files.mod"

#line 58 "files.mod"

#line 58 "files.mod"

#line 58 "files.mod"
extern void pOt_Set_Files
#line 58 "files.mod"
#if pOt__ANSI_C
#line 58 "files.mod"
  (struct pOt__tag_2_Files *pOt_r, pOt_File_Files pOt_f, pOt_LONGINT pOt_pos)
#line 58 "files.mod"
#else
#line 58 "files.mod"
  (pOt_r, pOt_f, pOt_pos)
#line 58 "files.mod"
  struct pOt__tag_2_Files *pOt_r;
#line 58 "files.mod"
  pOt_File_Files pOt_f;
#line 58 "files.mod"
  pOt_LONGINT pOt_pos;
#line 58 "files.mod"

#line 58 "files.mod"
#endif
#line 58 "files.mod"
{
#line 58 "files.mod"
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
#line 58 "files.mod"
  struct {void *next, *vars[0x1];} pOt__gc_strs;
#line 58 "files.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 58 "files.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 58 "files.mod"
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
#line 58 "files.mod"
  pOt__gc_strs.vars[0x0]=pOt_NIL;
#line 58 "files.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_f;
#line 58 "files.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 58 "files.mod"

#line 58 "files.mod"

#line 58 "files.mod"
pOt__Epilogue:;
#line 58 "files.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 58 "files.mod"
}
#line 58 "files.mod"

#line 58 "files.mod"

#line 62 "files.mod"

#line 62 "files.mod"

#line 62 "files.mod"
extern void pOt_Read_Files
#line 62 "files.mod"
#if pOt__ANSI_C
#line 62 "files.mod"
  (struct pOt__tag_2_Files *pOt_r, pOt_BYTE_SYSTEM *pOt_x)
#line 62 "files.mod"
#else
#line 62 "files.mod"
  (pOt_r, pOt_x)
#line 62 "files.mod"
  struct pOt__tag_2_Files *pOt_r;
#line 62 "files.mod"
  pOt_BYTE_SYSTEM *pOt_x;
#line 62 "files.mod"

#line 62 "files.mod"
#endif
#line 62 "files.mod"
{
#line 62 "files.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 62 "files.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 62 "files.mod"

#line 62 "files.mod"

#line 62 "files.mod"
pOt__Epilogue:;
#line 62 "files.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 62 "files.mod"
}
#line 62 "files.mod"

#line 62 "files.mod"

#line 67 "files.mod"

#line 67 "files.mod"

#line 67 "files.mod"
extern void pOt_ReadBytes_Files
#line 67 "files.mod"
#if pOt__ANSI_C
#line 67 "files.mod"
  (struct pOt__tag_2_Files *pOt_r, pOt__BytArr pOt_x, pOt_LONGINT pOt_n)
#line 67 "files.mod"
#else
#line 67 "files.mod"
  (pOt_r, pOt_x, pOt_n)
#line 67 "files.mod"
  struct pOt__tag_2_Files *pOt_r;
#line 67 "files.mod"
  pOt__BytArr pOt_x;
#line 67 "files.mod"
  pOt_LONGINT pOt_n;
#line 67 "files.mod"

#line 67 "files.mod"
#endif
#line 67 "files.mod"
{
#line 67 "files.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 67 "files.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 67 "files.mod"

#line 67 "files.mod"

#line 67 "files.mod"
pOt__Epilogue:;
#line 67 "files.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 67 "files.mod"
}
#line 67 "files.mod"

#line 67 "files.mod"

#line 72 "files.mod"

#line 72 "files.mod"

#line 72 "files.mod"
extern void pOt_Write_Files
#line 72 "files.mod"
#if pOt__ANSI_C
#line 72 "files.mod"
  (struct pOt__tag_2_Files *pOt_r, pOt_BYTE_SYSTEM pOt_x)
#line 72 "files.mod"
#else
#line 72 "files.mod"
  (pOt_r, pOt_x)
#line 72 "files.mod"
  struct pOt__tag_2_Files *pOt_r;
#line 72 "files.mod"
  pOt_BYTE_SYSTEM pOt_x;
#line 72 "files.mod"

#line 72 "files.mod"
#endif
#line 72 "files.mod"
{
#line 72 "files.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 72 "files.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 72 "files.mod"

#line 72 "files.mod"

#line 72 "files.mod"
pOt__Epilogue:;
#line 72 "files.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 72 "files.mod"
}
#line 72 "files.mod"

#line 72 "files.mod"

#line 77 "files.mod"

#line 77 "files.mod"

#line 77 "files.mod"
extern void pOt_WriteBytes_Files
#line 77 "files.mod"
#if pOt__ANSI_C
#line 77 "files.mod"
  (struct pOt__tag_2_Files *pOt_r, pOt__BytArr pOt_x, pOt_LONGINT pOt_n)
#line 77 "files.mod"
#else
#line 77 "files.mod"
  (pOt_r, pOt_x, pOt_n)
#line 77 "files.mod"
  struct pOt__tag_2_Files *pOt_r;
#line 77 "files.mod"
  pOt__BytArr pOt_x;
#line 77 "files.mod"
  pOt_LONGINT pOt_n;
#line 77 "files.mod"

#line 77 "files.mod"
#endif
#line 77 "files.mod"
{
#line 77 "files.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 77 "files.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 77 "files.mod"

#line 77 "files.mod"

#line 77 "files.mod"
pOt__Epilogue:;
#line 77 "files.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 77 "files.mod"
}
#line 77 "files.mod"

#line 77 "files.mod"

#line 80 "files.mod"

#line 80 "files.mod"

#line 80 "files.mod"
extern pOt_LONGINT pOt_Pos_Files
#line 80 "files.mod"
#if pOt__ANSI_C
#line 80 "files.mod"
  (struct pOt__tag_2_Files *pOt_r)
#line 80 "files.mod"
#else
#line 80 "files.mod"
  (pOt_r)
#line 80 "files.mod"
  struct pOt__tag_2_Files *pOt_r;
#line 80 "files.mod"

#line 80 "files.mod"
#endif
#line 80 "files.mod"
{
#line 80 "files.mod"
  pOt_LONGINT pOt__retval;
#line 80 "files.mod"
  int pOt__gc_enabled_prev;
#line 80 "files.mod"
  pOt__gc_enabled_prev=pOt__gc_enabled;
#line 80 "files.mod"
  pOt__gc_enabled=0;
#line 80 "files.mod"

#line 80 "files.mod"
  pOt__retval =(pOt_LONGINT)((*pOt_r).pOt_pos);
  goto pOt__Epilogue;
#line 81 "files.mod"

#line 81 "files.mod"
  pOt__halt(__FILE__,__LINE__,0x11);
#line 81 "files.mod"
pOt__Epilogue:;
#line 81 "files.mod"
  pOt__gc_enabled=pOt__gc_enabled_prev;
#line 81 "files.mod"
  return pOt__retval;
#line 81 "files.mod"
}
#line 81 "files.mod"

#line 81 "files.mod"

#line 84 "files.mod"

#line 84 "files.mod"

#line 84 "files.mod"
extern pOt_File_Files pOt_Base_Files
#line 84 "files.mod"
#if pOt__ANSI_C
#line 84 "files.mod"
  (struct pOt__tag_2_Files *pOt_r)
#line 84 "files.mod"
#else
#line 84 "files.mod"
  (pOt_r)
#line 84 "files.mod"
  struct pOt__tag_2_Files *pOt_r;
#line 84 "files.mod"

#line 84 "files.mod"
#endif
#line 84 "files.mod"
{
#line 84 "files.mod"
  pOt_File_Files pOt__retval;
#line 84 "files.mod"
  int pOt__gc_enabled_prev;
#line 84 "files.mod"
  pOt__gc_enabled_prev=pOt__gc_enabled;
#line 84 "files.mod"
  pOt__gc_enabled=0;
#line 84 "files.mod"

#line 84 "files.mod"
  pOt__retval =(struct pOt__tag_1_Files*)((*pOt_r).pOt_file);
  goto pOt__Epilogue;
#line 85 "files.mod"

#line 85 "files.mod"
  pOt__halt(__FILE__,__LINE__,0x11);
#line 85 "files.mod"
pOt__Epilogue:;
#line 85 "files.mod"
  pOt__gc_enabled=pOt__gc_enabled_prev;
#line 85 "files.mod"
  return pOt__retval;
#line 85 "files.mod"
}
#line 85 "files.mod"

#line 85 "files.mod"

#line 93 "files.mod"

#line 93 "files.mod"

#line 93 "files.mod"
extern void pOt_Rename_Files
#line 93 "files.mod"
#if pOt__ANSI_C
#line 93 "files.mod"
  (pOt__DynArr *pOt_old, pOt__DynArr *pOt_new, pOt_INTEGER *pOt_res)
#line 93 "files.mod"
#else
#line 93 "files.mod"
  (pOt_old, pOt_new, pOt_res)
#line 93 "files.mod"
  pOt__DynArr *pOt_old, *pOt_new;
#line 93 "files.mod"
  pOt_INTEGER *pOt_res;
#line 93 "files.mod"

#line 93 "files.mod"
#endif
#line 93 "files.mod"
{
#line 93 "files.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 93 "files.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 93 "files.mod"

#line 93 "files.mod"

#line 93 "files.mod"
pOt__Epilogue:;
#line 93 "files.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 93 "files.mod"
  pOt__rm_par((pOt__TypDsc**)pOt_old);
#line 93 "files.mod"
  pOt__rm_par((pOt__TypDsc**)pOt_new);
#line 93 "files.mod"
}
#line 93 "files.mod"

#line 93 "files.mod"

#line 100 "files.mod"

#line 100 "files.mod"

#line 100 "files.mod"
extern void pOt_Delete_Files
#line 100 "files.mod"
#if pOt__ANSI_C
#line 100 "files.mod"
  (pOt__DynArr *pOt_name, pOt_INTEGER *pOt_res)
#line 100 "files.mod"
#else
#line 100 "files.mod"
  (pOt_name, pOt_res)
#line 100 "files.mod"
  pOt__DynArr *pOt_name;
#line 100 "files.mod"
  pOt_INTEGER *pOt_res;
#line 100 "files.mod"

#line 100 "files.mod"
#endif
#line 100 "files.mod"
{
#line 100 "files.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 100 "files.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 100 "files.mod"

#line 100 "files.mod"

#line 100 "files.mod"
pOt__Epilogue:;
#line 100 "files.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 100 "files.mod"
  pOt__rm_par((pOt__TypDsc**)pOt_name);
#line 100 "files.mod"
}
#line 100 "files.mod"

#line 100 "files.mod"
void pOt_Files__body()
#line 102 "files.mod"
{
#line 102 "files.mod"
  static int pOt_Files__loaded=0;
#line 102 "files.mod"
  if(!pOt_Files__loaded){
#line 102 "files.mod"
    pOt_Files__loaded=1;
#line 102 "files.mod"

#line 102 "files.mod"

#line 102 "files.mod"
    pOt__gc_ptrs.next=pOt__gc_root;
#line 102 "files.mod"
    pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 102 "files.mod"

#line 102 "files.mod"
    pOt_StdIn_Files=pOt_NIL;
#line 102 "files.mod"
    pOt_StdOut_Files=pOt_NIL;
#line 102 "files.mod"
    pOt_StdErr_Files=pOt_NIL;
#line 102 "files.mod"

#line 102 "files.mod"
    pOt__new(__FILE__,__LINE__,(pOt__TypDsc***)&pOt_StdIn_Files,(pOt__TypDsc*)&pOt__td_1_Files);
    (*((struct pOt__tag_1_Files*)pOt__nilchk(__FILE__,__LINE__,pOt_StdIn_Files))).pOt_pos=(pOt_LONGINT)(0);
#line 103 "files.mod"
    pOt__arr_assign((pOt__ArrTypDsc**)& (*((struct pOt__tag_1_Files*)pOt__nilchk(__FILE__,__LINE__,pOt_StdIn_Files))).pOt_name,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__td_0_Files)));
#line 103 "files.mod"
    (*((struct pOt__tag_1_Files*)pOt__nilchk(__FILE__,__LINE__,pOt_StdIn_Files))).pOt_handle=(pOt_LONGINT)(0);
    pOt__new(__FILE__,__LINE__,(pOt__TypDsc***)&pOt_StdOut_Files,(pOt__TypDsc*)&pOt__td_1_Files);
#line 104 "files.mod"
    (*((struct pOt__tag_1_Files*)pOt__nilchk(__FILE__,__LINE__,pOt_StdOut_Files))).pOt_pos=(pOt_LONGINT)(0);
#line 104 "files.mod"
    pOt__arr_assign((pOt__ArrTypDsc**)& (*((struct pOt__tag_1_Files*)pOt__nilchk(__FILE__,__LINE__,pOt_StdOut_Files))).pOt_name,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__td_0_Files)));
#line 104 "files.mod"
    (*((struct pOt__tag_1_Files*)pOt__nilchk(__FILE__,__LINE__,pOt_StdOut_Files))).pOt_handle=(pOt_LONGINT)(0);
    pOt__new(__FILE__,__LINE__,(pOt__TypDsc***)&pOt_StdErr_Files,(pOt__TypDsc*)&pOt__td_1_Files);
#line 105 "files.mod"
    (*((struct pOt__tag_1_Files*)pOt__nilchk(__FILE__,__LINE__,pOt_StdErr_Files))).pOt_pos=(pOt_LONGINT)(0);
#line 105 "files.mod"
    pOt__arr_assign((pOt__ArrTypDsc**)& (*((struct pOt__tag_1_Files*)pOt__nilchk(__FILE__,__LINE__,pOt_StdErr_Files))).pOt_name,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__td_0_Files)));
#line 105 "files.mod"
    (*((struct pOt__tag_1_Files*)pOt__nilchk(__FILE__,__LINE__,pOt_StdErr_Files))).pOt_handle=(pOt_LONGINT)(0);

#line 106 "files.mod"
  pOt__Epilogue:;
#line 106 "files.mod"
  }
#line 106 "files.mod"
}
#line 106 "files.mod"
