#ifndef pOt_Files__INC
#define pOt_Files__INC
/* This code is generated by pOt. */


typedef struct pOt__tag_1_Files *pOt_File_Files;
typedef struct pOt__tag_1_Files pOt_FileDesc_Files;
typedef struct pOt__tag_2_Files pOt_Rider_Files;

struct pOt__tag_0_Files {
  pOt__ArrTypDsc *td;
  pOt_CHAR arr[0x400L];
} ;
extern pOt__ArrTypDsc pOt__td_0_Files;
struct pOt__tag_1_Files {
  pOt__RecTypDsc *td;
  struct pOt__tag_0_Files pOt_name;
  pOt_LONGINT pOt_handle, pOt_pos;
} ;
extern pOt__RecTypDsc pOt__td_1_Files;
struct pOt__tag_2_Files {
  pOt__RecTypDsc *td;
  pOt_INTEGER pOt_res;
  pOt_BOOLEAN pOt_eof;
  pOt_LONGINT pOt_pos;
  pOt_File_Files pOt_file;
} ;
extern pOt__RecTypDsc pOt__td_2_Files;

extern pOt_File_Files pOt_StdIn_Files, pOt_StdOut_Files, pOt_StdErr_Files;

extern pOt_File_Files pOt_Old_Files pOt__ARGS((pOt__DynArr *));
extern pOt_File_Files pOt_New_Files pOt__ARGS((pOt__DynArr *));
extern void pOt_Register_Files pOt__ARGS((pOt_File_Files ));
extern void pOt_Close_Files pOt__ARGS((pOt_File_Files ));
extern void pOt_Purge_Files pOt__ARGS((pOt_File_Files ));
extern pOt_LONGINT pOt_Length_Files pOt__ARGS((pOt_File_Files ));
extern void pOt_Set_Files pOt__ARGS((struct pOt__tag_2_Files *, pOt_File_Files , pOt_LONGINT ));
extern void pOt_Read_Files pOt__ARGS((struct pOt__tag_2_Files *, pOt_BYTE_SYSTEM *));
extern void pOt_ReadBytes_Files pOt__ARGS((struct pOt__tag_2_Files *, pOt__BytArr , pOt_LONGINT ));
extern void pOt_Write_Files pOt__ARGS((struct pOt__tag_2_Files *, pOt_BYTE_SYSTEM ));
extern void pOt_WriteBytes_Files pOt__ARGS((struct pOt__tag_2_Files *, pOt__BytArr , pOt_LONGINT ));
extern pOt_LONGINT pOt_Pos_Files pOt__ARGS((struct pOt__tag_2_Files *));
extern pOt_File_Files pOt_Base_Files pOt__ARGS((struct pOt__tag_2_Files *));
extern void pOt_Rename_Files pOt__ARGS((pOt__DynArr *, pOt__DynArr *, pOt_INTEGER *));
extern void pOt_Delete_Files pOt__ARGS((pOt__DynArr *, pOt_INTEGER *));
extern void pOt_Files__body pOt__ARGS((void));

#endif
