/* This code is generated by pOt. */
#line 3 "os.mod"

#line 3 "os.mod"
#include <pOtRTL.h>
#line 3 "os.mod"

#line 3 "os.mod"
#include "OS.hi"
#line 3 "os.mod"

#line 3 "os.mod"

#line 3 "os.mod"

#line 3 "os.mod"

#line 3 "os.mod"
static struct {void *next, *vars[0x1];} pOt__gc_ptrs = {pOt_NIL,{
#line 3 "os.mod"
  pOt_NIL
#line 3 "os.mod"
}};
#line 3 "os.mod"
static struct {void *next, *vars[0x1];} pOt__gc_strs = {&pOt__gc_ptrs,{
#line 3 "os.mod"
  pOt_NIL
#line 3 "os.mod"
}};
#line 3 "os.mod"

#line 3 "os.mod"


#line 4 "os.mod"

#line 4 "os.mod"
extern pOt_LONGINT pOt_Time_OS()
#line 4 "os.mod"
{
#line 4 "os.mod"
  pOt_LONGINT pOt__retval;
#line 4 "os.mod"
  int pOt__gc_enabled_prev;
#line 4 "os.mod"
  pOt__gc_enabled_prev=pOt__gc_enabled;
#line 4 "os.mod"
  pOt__gc_enabled=0;
#line 4 "os.mod"

#line 4 "os.mod"

#line 4 "os.mod"
  pOt__halt(__FILE__,__LINE__,0x11);
#line 4 "os.mod"
pOt__Epilogue:;
#line 4 "os.mod"
  pOt__gc_enabled=pOt__gc_enabled_prev;
#line 4 "os.mod"
  return pOt__retval;
#line 4 "os.mod"
}
#line 4 "os.mod"

#line 4 "os.mod"

#line 7 "os.mod"

#line 7 "os.mod"

#line 7 "os.mod"
extern void pOt_GetClock_OS
#line 7 "os.mod"
#if pOt__ANSI_C
#line 7 "os.mod"
  (pOt_LONGINT *pOt_date, pOt_LONGINT *pOt_time)
#line 7 "os.mod"
#else
#line 7 "os.mod"
  (pOt_date, pOt_time)
#line 7 "os.mod"
  pOt_LONGINT *pOt_date, *pOt_time;
#line 7 "os.mod"

#line 7 "os.mod"
#endif
#line 7 "os.mod"
{
#line 7 "os.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 7 "os.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 7 "os.mod"

#line 7 "os.mod"

#line 7 "os.mod"
pOt__Epilogue:;
#line 7 "os.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 7 "os.mod"
}
#line 7 "os.mod"

#line 7 "os.mod"

#line 10 "os.mod"

#line 10 "os.mod"

#line 10 "os.mod"
extern void pOt_GetParFile_OS
#line 10 "os.mod"
#if pOt__ANSI_C
#line 10 "os.mod"
  (pOt__DynArr *pOt_fname)
#line 10 "os.mod"
#else
#line 10 "os.mod"
  (pOt_fname)
#line 10 "os.mod"
  pOt__DynArr *pOt_fname;
#line 10 "os.mod"

#line 10 "os.mod"
#endif
#line 10 "os.mod"
{
#line 10 "os.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 10 "os.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 10 "os.mod"

#line 10 "os.mod"

#line 10 "os.mod"
pOt__Epilogue:;
#line 10 "os.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 10 "os.mod"
}
#line 10 "os.mod"

#line 10 "os.mod"

#line 13 "os.mod"

#line 13 "os.mod"

#line 13 "os.mod"
extern void pOt_GC_OS()
#line 13 "os.mod"
{
#line 13 "os.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 13 "os.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 13 "os.mod"

#line 13 "os.mod"

#line 13 "os.mod"
pOt__Epilogue:;
#line 13 "os.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 13 "os.mod"
}
#line 13 "os.mod"

#line 13 "os.mod"
void pOt_OS__body()
#line 15 "os.mod"
{
#line 15 "os.mod"
  static int pOt_OS__loaded=0;
#line 15 "os.mod"
  if(!pOt_OS__loaded){
#line 15 "os.mod"
    pOt_OS__loaded=1;
#line 15 "os.mod"

#line 15 "os.mod"

#line 15 "os.mod"
    pOt__gc_ptrs.next=pOt__gc_root;
#line 15 "os.mod"
    pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 15 "os.mod"

#line 15 "os.mod"

#line 15 "os.mod"

#line 15 "os.mod"
  pOt__Epilogue:;
#line 15 "os.mod"
  }
#line 15 "os.mod"
}
#line 15 "os.mod"
