#ifndef pOt_OS__INC
#define pOt_OS__INC
/* This code is generated by pOt. */





extern pOt_LONGINT pOt_Time_OS pOt__ARGS((void));
extern void pOt_GetClock_OS pOt__ARGS((pOt_LONGINT *, pOt_LONGINT *));
extern void pOt_GetParFile_OS pOt__ARGS((pOt__DynArr *));
extern void pOt_GC_OS pOt__ARGS((void));
extern void pOt_OS__body pOt__ARGS((void));

#endif
