#ifndef pOt_Reals__INC
#define pOt_Reals__INC
/* This code is generated by pOt. */





extern pOt_INTEGER pOt_Expo_Reals pOt__ARGS((pOt_REAL ));
extern pOt_INTEGER pOt_ExpoL_Reals pOt__ARGS((pOt_LONGREAL ));
extern void pOt_SetExpo_Reals pOt__ARGS((pOt_INTEGER , pOt_REAL *));
extern void pOt_SetExpoL_Reals pOt__ARGS((pOt_INTEGER , pOt_LONGREAL *));
extern pOt_REAL pOt_Ten_Reals pOt__ARGS((pOt_INTEGER ));
extern pOt_LONGREAL pOt_TenL_Reals pOt__ARGS((pOt_INTEGER ));
extern void pOt_Convert_Reals pOt__ARGS((pOt_REAL , pOt_INTEGER , pOt__DynArr *));
extern void pOt_ConvertL_Reals pOt__ARGS((pOt_LONGREAL , pOt_INTEGER , pOt__DynArr *));
extern void pOt_ConvertH_Reals pOt__ARGS((pOt_REAL , pOt__DynArr *));
extern void pOt_ConvertHL_Reals pOt__ARGS((pOt_LONGREAL , pOt__DynArr *));
extern pOt_LONGINT pOt_FSR_Reals pOt__ARGS((void));
extern void pOt_SetFSR_Reals pOt__ARGS((pOt_LONGINT ));
extern void pOt_Reals__body pOt__ARGS((void));

#endif
