/* This code is generated by pOt. */
#line 3 "reals.mod"

#line 3 "reals.mod"
#include <pOtRTL.h>
#line 3 "reals.mod"

#line 3 "reals.mod"
#include "Reals.hi"
#line 3 "reals.mod"

#line 3 "reals.mod"

#line 3 "reals.mod"

#line 3 "reals.mod"

#line 3 "reals.mod"
static struct {void *next, *vars[0x1];} pOt__gc_ptrs = {pOt_NIL,{
#line 3 "reals.mod"
  pOt_NIL
#line 3 "reals.mod"
}};
#line 3 "reals.mod"
static struct {void *next, *vars[0x1];} pOt__gc_strs = {&pOt__gc_ptrs,{
#line 3 "reals.mod"
  pOt_NIL
#line 3 "reals.mod"
}};
#line 3 "reals.mod"

#line 3 "reals.mod"


#line 4 "reals.mod"

#line 4 "reals.mod"
extern pOt_INTEGER pOt_Expo_Reals
#line 4 "reals.mod"
#if pOt__ANSI_C
#line 4 "reals.mod"
  (pOt_REAL pOt_x)
#line 4 "reals.mod"
#else
#line 4 "reals.mod"
  (pOt_x)
#line 4 "reals.mod"
  pOt_REAL pOt_x;
#line 4 "reals.mod"

#line 4 "reals.mod"
#endif
#line 4 "reals.mod"
{
#line 4 "reals.mod"
  pOt_INTEGER pOt__retval;
#line 4 "reals.mod"
  int pOt__gc_enabled_prev;
#line 4 "reals.mod"
  pOt__gc_enabled_prev=pOt__gc_enabled;
#line 4 "reals.mod"
  pOt__gc_enabled=0;
#line 4 "reals.mod"

#line 4 "reals.mod"

#line 4 "reals.mod"
  pOt__halt(__FILE__,__LINE__,0x11);
#line 4 "reals.mod"
pOt__Epilogue:;
#line 4 "reals.mod"
  pOt__gc_enabled=pOt__gc_enabled_prev;
#line 4 "reals.mod"
  return pOt__retval;
#line 4 "reals.mod"
}
#line 4 "reals.mod"

#line 4 "reals.mod"

#line 7 "reals.mod"

#line 7 "reals.mod"

#line 7 "reals.mod"
extern pOt_INTEGER pOt_ExpoL_Reals
#line 7 "reals.mod"
#if pOt__ANSI_C
#line 7 "reals.mod"
  (pOt_LONGREAL pOt_x)
#line 7 "reals.mod"
#else
#line 7 "reals.mod"
  (pOt_x)
#line 7 "reals.mod"
  pOt_LONGREAL pOt_x;
#line 7 "reals.mod"

#line 7 "reals.mod"
#endif
#line 7 "reals.mod"
{
#line 7 "reals.mod"
  pOt_INTEGER pOt__retval;
#line 7 "reals.mod"
  int pOt__gc_enabled_prev;
#line 7 "reals.mod"
  pOt__gc_enabled_prev=pOt__gc_enabled;
#line 7 "reals.mod"
  pOt__gc_enabled=0;
#line 7 "reals.mod"

#line 7 "reals.mod"

#line 7 "reals.mod"
  pOt__halt(__FILE__,__LINE__,0x11);
#line 7 "reals.mod"
pOt__Epilogue:;
#line 7 "reals.mod"
  pOt__gc_enabled=pOt__gc_enabled_prev;
#line 7 "reals.mod"
  return pOt__retval;
#line 7 "reals.mod"
}
#line 7 "reals.mod"

#line 7 "reals.mod"

#line 10 "reals.mod"

#line 10 "reals.mod"

#line 10 "reals.mod"
extern void pOt_SetExpo_Reals
#line 10 "reals.mod"
#if pOt__ANSI_C
#line 10 "reals.mod"
  (pOt_INTEGER pOt_e, pOt_REAL *pOt_x)
#line 10 "reals.mod"
#else
#line 10 "reals.mod"
  (pOt_e, pOt_x)
#line 10 "reals.mod"
  pOt_INTEGER pOt_e;
#line 10 "reals.mod"
  pOt_REAL *pOt_x;
#line 10 "reals.mod"

#line 10 "reals.mod"
#endif
#line 10 "reals.mod"
{
#line 10 "reals.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 10 "reals.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 10 "reals.mod"

#line 10 "reals.mod"

#line 10 "reals.mod"
pOt__Epilogue:;
#line 10 "reals.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 10 "reals.mod"
}
#line 10 "reals.mod"

#line 10 "reals.mod"

#line 13 "reals.mod"

#line 13 "reals.mod"

#line 13 "reals.mod"
extern void pOt_SetExpoL_Reals
#line 13 "reals.mod"
#if pOt__ANSI_C
#line 13 "reals.mod"
  (pOt_INTEGER pOt_e, pOt_LONGREAL *pOt_x)
#line 13 "reals.mod"
#else
#line 13 "reals.mod"
  (pOt_e, pOt_x)
#line 13 "reals.mod"
  pOt_INTEGER pOt_e;
#line 13 "reals.mod"
  pOt_LONGREAL *pOt_x;
#line 13 "reals.mod"

#line 13 "reals.mod"
#endif
#line 13 "reals.mod"
{
#line 13 "reals.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 13 "reals.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 13 "reals.mod"

#line 13 "reals.mod"

#line 13 "reals.mod"
pOt__Epilogue:;
#line 13 "reals.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 13 "reals.mod"
}
#line 13 "reals.mod"

#line 13 "reals.mod"

#line 16 "reals.mod"

#line 16 "reals.mod"

#line 16 "reals.mod"
extern pOt_REAL pOt_Ten_Reals
#line 16 "reals.mod"
#if pOt__ANSI_C
#line 16 "reals.mod"
  (pOt_INTEGER pOt_e)
#line 16 "reals.mod"
#else
#line 16 "reals.mod"
  (pOt_e)
#line 16 "reals.mod"
  pOt_INTEGER pOt_e;
#line 16 "reals.mod"

#line 16 "reals.mod"
#endif
#line 16 "reals.mod"
{
#line 16 "reals.mod"
  pOt_REAL pOt__retval;
#line 16 "reals.mod"
  int pOt__gc_enabled_prev;
#line 16 "reals.mod"
  pOt__gc_enabled_prev=pOt__gc_enabled;
#line 16 "reals.mod"
  pOt__gc_enabled=0;
#line 16 "reals.mod"

#line 16 "reals.mod"

#line 16 "reals.mod"
  pOt__halt(__FILE__,__LINE__,0x11);
#line 16 "reals.mod"
pOt__Epilogue:;
#line 16 "reals.mod"
  pOt__gc_enabled=pOt__gc_enabled_prev;
#line 16 "reals.mod"
  return pOt__retval;
#line 16 "reals.mod"
}
#line 16 "reals.mod"

#line 16 "reals.mod"

#line 19 "reals.mod"

#line 19 "reals.mod"

#line 19 "reals.mod"
extern pOt_LONGREAL pOt_TenL_Reals
#line 19 "reals.mod"
#if pOt__ANSI_C
#line 19 "reals.mod"
  (pOt_INTEGER pOt_e)
#line 19 "reals.mod"
#else
#line 19 "reals.mod"
  (pOt_e)
#line 19 "reals.mod"
  pOt_INTEGER pOt_e;
#line 19 "reals.mod"

#line 19 "reals.mod"
#endif
#line 19 "reals.mod"
{
#line 19 "reals.mod"
  pOt_LONGREAL pOt__retval;
#line 19 "reals.mod"
  int pOt__gc_enabled_prev;
#line 19 "reals.mod"
  pOt__gc_enabled_prev=pOt__gc_enabled;
#line 19 "reals.mod"
  pOt__gc_enabled=0;
#line 19 "reals.mod"

#line 19 "reals.mod"

#line 19 "reals.mod"
  pOt__halt(__FILE__,__LINE__,0x11);
#line 19 "reals.mod"
pOt__Epilogue:;
#line 19 "reals.mod"
  pOt__gc_enabled=pOt__gc_enabled_prev;
#line 19 "reals.mod"
  return pOt__retval;
#line 19 "reals.mod"
}
#line 19 "reals.mod"

#line 19 "reals.mod"

#line 22 "reals.mod"

#line 22 "reals.mod"

#line 22 "reals.mod"
extern void pOt_Convert_Reals
#line 22 "reals.mod"
#if pOt__ANSI_C
#line 22 "reals.mod"
  (pOt_REAL pOt_x, pOt_INTEGER pOt_n, pOt__DynArr *pOt_d)
#line 22 "reals.mod"
#else
#line 22 "reals.mod"
  (pOt_x, pOt_n, pOt_d)
#line 22 "reals.mod"
  pOt_REAL pOt_x;
#line 22 "reals.mod"
  pOt_INTEGER pOt_n;
#line 22 "reals.mod"
  pOt__DynArr *pOt_d;
#line 22 "reals.mod"

#line 22 "reals.mod"
#endif
#line 22 "reals.mod"
{
#line 22 "reals.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 22 "reals.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 22 "reals.mod"

#line 22 "reals.mod"

#line 22 "reals.mod"
pOt__Epilogue:;
#line 22 "reals.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 22 "reals.mod"
}
#line 22 "reals.mod"

#line 22 "reals.mod"

#line 25 "reals.mod"

#line 25 "reals.mod"

#line 25 "reals.mod"
extern void pOt_ConvertL_Reals
#line 25 "reals.mod"
#if pOt__ANSI_C
#line 25 "reals.mod"
  (pOt_LONGREAL pOt_x, pOt_INTEGER pOt_n, pOt__DynArr *pOt_d)
#line 25 "reals.mod"
#else
#line 25 "reals.mod"
  (pOt_x, pOt_n, pOt_d)
#line 25 "reals.mod"
  pOt_LONGREAL pOt_x;
#line 25 "reals.mod"
  pOt_INTEGER pOt_n;
#line 25 "reals.mod"
  pOt__DynArr *pOt_d;
#line 25 "reals.mod"

#line 25 "reals.mod"
#endif
#line 25 "reals.mod"
{
#line 25 "reals.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 25 "reals.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 25 "reals.mod"

#line 25 "reals.mod"

#line 25 "reals.mod"
pOt__Epilogue:;
#line 25 "reals.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 25 "reals.mod"
}
#line 25 "reals.mod"

#line 25 "reals.mod"

#line 28 "reals.mod"

#line 28 "reals.mod"

#line 28 "reals.mod"
extern void pOt_ConvertH_Reals
#line 28 "reals.mod"
#if pOt__ANSI_C
#line 28 "reals.mod"
  (pOt_REAL pOt_x, pOt__DynArr *pOt_d)
#line 28 "reals.mod"
#else
#line 28 "reals.mod"
  (pOt_x, pOt_d)
#line 28 "reals.mod"
  pOt_REAL pOt_x;
#line 28 "reals.mod"
  pOt__DynArr *pOt_d;
#line 28 "reals.mod"

#line 28 "reals.mod"
#endif
#line 28 "reals.mod"
{
#line 28 "reals.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 28 "reals.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 28 "reals.mod"

#line 28 "reals.mod"

#line 28 "reals.mod"
pOt__Epilogue:;
#line 28 "reals.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 28 "reals.mod"
}
#line 28 "reals.mod"

#line 28 "reals.mod"

#line 31 "reals.mod"

#line 31 "reals.mod"

#line 31 "reals.mod"
extern void pOt_ConvertHL_Reals
#line 31 "reals.mod"
#if pOt__ANSI_C
#line 31 "reals.mod"
  (pOt_LONGREAL pOt_x, pOt__DynArr *pOt_d)
#line 31 "reals.mod"
#else
#line 31 "reals.mod"
  (pOt_x, pOt_d)
#line 31 "reals.mod"
  pOt_LONGREAL pOt_x;
#line 31 "reals.mod"
  pOt__DynArr *pOt_d;
#line 31 "reals.mod"

#line 31 "reals.mod"
#endif
#line 31 "reals.mod"
{
#line 31 "reals.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 31 "reals.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 31 "reals.mod"

#line 31 "reals.mod"

#line 31 "reals.mod"
pOt__Epilogue:;
#line 31 "reals.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 31 "reals.mod"
}
#line 31 "reals.mod"

#line 31 "reals.mod"

#line 34 "reals.mod"

#line 34 "reals.mod"

#line 34 "reals.mod"
extern pOt_LONGINT pOt_FSR_Reals()
#line 34 "reals.mod"
{
#line 34 "reals.mod"
  pOt_LONGINT pOt__retval;
#line 34 "reals.mod"
  int pOt__gc_enabled_prev;
#line 34 "reals.mod"
  pOt__gc_enabled_prev=pOt__gc_enabled;
#line 34 "reals.mod"
  pOt__gc_enabled=0;
#line 34 "reals.mod"

#line 34 "reals.mod"

#line 34 "reals.mod"
  pOt__halt(__FILE__,__LINE__,0x11);
#line 34 "reals.mod"
pOt__Epilogue:;
#line 34 "reals.mod"
  pOt__gc_enabled=pOt__gc_enabled_prev;
#line 34 "reals.mod"
  return pOt__retval;
#line 34 "reals.mod"
}
#line 34 "reals.mod"

#line 34 "reals.mod"

#line 37 "reals.mod"

#line 37 "reals.mod"

#line 37 "reals.mod"
extern void pOt_SetFSR_Reals
#line 37 "reals.mod"
#if pOt__ANSI_C
#line 37 "reals.mod"
  (pOt_LONGINT pOt_status)
#line 37 "reals.mod"
#else
#line 37 "reals.mod"
  (pOt_status)
#line 37 "reals.mod"
  pOt_LONGINT pOt_status;
#line 37 "reals.mod"

#line 37 "reals.mod"
#endif
#line 37 "reals.mod"
{
#line 37 "reals.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 37 "reals.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 37 "reals.mod"

#line 37 "reals.mod"

#line 37 "reals.mod"
pOt__Epilogue:;
#line 37 "reals.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 37 "reals.mod"
}
#line 37 "reals.mod"

#line 37 "reals.mod"
void pOt_Reals__body()
#line 39 "reals.mod"
{
#line 39 "reals.mod"
  static int pOt_Reals__loaded=0;
#line 39 "reals.mod"
  if(!pOt_Reals__loaded){
#line 39 "reals.mod"
    pOt_Reals__loaded=1;
#line 39 "reals.mod"

#line 39 "reals.mod"

#line 39 "reals.mod"
    pOt__gc_ptrs.next=pOt__gc_root;
#line 39 "reals.mod"
    pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 39 "reals.mod"

#line 39 "reals.mod"

#line 39 "reals.mod"

#line 39 "reals.mod"
  pOt__Epilogue:;
#line 39 "reals.mod"
  }
#line 39 "reals.mod"
}
#line 39 "reals.mod"
