/* This code is generated by pOt. */
#line 24 "cocd.mod"

#line 24 "cocd.mod"
#include <pOtRTL.h>
#line 24 "cocd.mod"
#include "Strings.h"
#line 24 "cocd.mod"
#include "COCS.h"
#line 24 "cocd.mod"
#include "COCT.h"
#line 24 "cocd.mod"
#include "COCQ.h"
#line 24 "cocd.mod"
#include "COCN.h"
#line 24 "cocd.mod"
#include "COCY.h"
#line 24 "cocd.mod"
#include "COCO.h"
#line 24 "cocd.mod"

#line 24 "cocd.mod"
#include "COCD.hi"
#line 24 "cocd.mod"

#line 24 "cocd.mod"

#line 24 "cocd.mod"
struct pOt__tag_0_COCD {
#line 24 "cocd.mod"
  pOt__ArrTypDsc *td;
#line 24 "cocd.mod"
  pOt_CHAR arr[0x4000L];
#line 24 "cocd.mod"
} ;
#line 24 "cocd.mod"
pOt__ArrTypDsc pOt__td_0_COCD= {
#line 24 "cocd.mod"
  1,
#line 24 "cocd.mod"
  0x4000L, sizeof(pOt_CHAR)
#line 24 "cocd.mod"
};
#line 24 "cocd.mod"
struct pOt__tag_1_COCD {
#line 24 "cocd.mod"
  pOt__PtrArrTypDsc *td;
#line 24 "cocd.mod"
  pOt_Struct_COCT arr[0x80L];
#line 24 "cocd.mod"
} ;
#line 24 "cocd.mod"
pOt__PtrArrTypDsc pOt__td_1_COCD= {
#line 24 "cocd.mod"
  2,
#line 24 "cocd.mod"
  0x80L, sizeof(struct pOt__tag_2_COCT*)
#line 24 "cocd.mod"
};
#line 24 "cocd.mod"

#line 24 "cocd.mod"
static pOt_LONGINT pOt_PtrSize_COCD;
#line 24 "cocd.mod"
static struct pOt__tag_0_COCD pOt_constant_COCD;
#line 24 "cocd.mod"
static struct pOt__tag_1_COCD pOt_RecTab_COCD;
#line 24 "cocd.mod"
static pOt_LONGINT pOt_conx_COCD;
#line 24 "cocd.mod"
static pOt_INTEGER pOt_bofrec_COCD, pOt_nofrec_COCD, pOt_recnum_COCD;
#line 24 "cocd.mod"

#line 24 "cocd.mod"
static struct {void *next, *vars[0x1];} pOt__gc_ptrs = {pOt_NIL,{
#line 24 "cocd.mod"
  pOt_NIL
#line 24 "cocd.mod"
}};
#line 24 "cocd.mod"
static struct {void *next, *vars[0x2];} pOt__gc_strs = {&pOt__gc_ptrs,{
#line 24 "cocd.mod"
  &pOt_RecTab_COCD,
#line 24 "cocd.mod"
  pOt_NIL
#line 24 "cocd.mod"
}};
#line 24 "cocd.mod"

#line 24 "cocd.mod"

#line 26 "cocd.mod"

#line 26 "cocd.mod"

#line 26 "cocd.mod"
extern void pOt_Init_COCD()
#line 26 "cocd.mod"
{
#line 26 "cocd.mod"
  pOt_INTEGER pOt_iofrec;
#line 26 "cocd.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 26 "cocd.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 26 "cocd.mod"

#line 26 "cocd.mod"
  pOt_conx_COCD=(pOt_LONGINT)(0);
#line 26 "cocd.mod"
  pOt_bofrec_COCD=(pOt_INTEGER)(0);
#line 26 "cocd.mod"
  pOt_nofrec_COCD=(pOt_INTEGER)(0);
#line 26 "cocd.mod"
  pOt_recnum_COCD=(pOt_INTEGER)(0);
  pOt_iofrec=(pOt_INTEGER)(0);
#line 27 "cocd.mod"
  for(;;) {
#line 27 "cocd.mod"
    if(( pOt_iofrec!=128)); else break;
#line 27 "cocd.mod"
    pOt_RecTab_COCD.arr[pOt__inxchk(__FILE__,__LINE__,0x80, pOt_iofrec)]=(struct pOt__tag_2_COCT*)(pOt_NIL);
#line 27 "cocd.mod"
    pOt_iofrec+=(1);
  }
#line 28 "cocd.mod"

#line 28 "cocd.mod"
pOt__Epilogue:;
#line 28 "cocd.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 28 "cocd.mod"
}
#line 28 "cocd.mod"

#line 28 "cocd.mod"

#line 34 "cocd.mod"

#line 34 "cocd.mod"
static pOt__DynArr *pOt_s_AllocString_COCD;
#line 34 "cocd.mod"
static struct pOt__tag_3_COCT *pOt_x_AllocString_COCD;
#line 34 "cocd.mod"
static pOt_LONGINT (*pOt_start_AllocString_COCD), (*pOt_rem_AllocString_COCD);
#line 34 "cocd.mod"
static pOt_INTEGER (*pOt_i_AllocString_COCD);
#line 34 "cocd.mod"
static pOt_CHAR (*pOt_ch_AllocString_COCD);
#line 34 "cocd.mod"

#line 34 "cocd.mod"
extern void pOt_AllocString_COCD pOt__ARGS((pOt__DynArr *, struct pOt__tag_3_COCT *));
#line 34 "cocd.mod"

#line 34 "cocd.mod"

#line 36 "cocd.mod"

#line 36 "cocd.mod"

#line 36 "cocd.mod"
static void pOt_FindString_AllocString_COCD()
#line 36 "cocd.mod"
{
#line 36 "cocd.mod"
  pOt_INTEGER pOt_slen, pOt_clen, pOt_i;
#line 36 "cocd.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 36 "cocd.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 36 "cocd.mod"

#line 36 "cocd.mod"
  (*pOt_start_AllocString_COCD)=(pOt_LONGINT)(0);
#line 36 "cocd.mod"
  pOt_slen=(pOt_INTEGER)((pOt_LONGINT)pOt__rngchk_i(__FILE__,__LINE__,pOt_Length_Strings(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt_s_AllocString_COCD)))));
  for(;;) {
    if(( (*pOt_start_AllocString_COCD)==pOt_conx_COCD)) {
#line 38 "cocd.mod"
      goto pOt__LoopLabel_1;
#line 38 "cocd.mod"
    }
#line 38 "cocd.mod"
    pOt_clen=(pOt_INTEGER)((pOt_INTEGER)((unsigned char)pOt_constant_COCD.arr[pOt__inxchk(__FILE__,__LINE__,0x4000, (*pOt_start_AllocString_COCD))]));
#line 40 "cocd.mod"
    if(( pOt_slen==pOt_clen)) {
      pOt_i=(pOt_INTEGER)(pOt_slen);
      for(;;) {
        pOt_i-=(1);
        if(( pOt_i==((pOt_INTEGER)(-1)))) {
#line 44 "cocd.mod"
          goto pOt__LoopLabel_2;
#line 44 "cocd.mod"
        }
#line 44 "cocd.mod"
        if(((unsigned char) pOt_constant_COCD.arr[pOt__inxchk(__FILE__,__LINE__,0x4000, (pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((*pOt_start_AllocString_COCD)),(pOt_LONGINT)(pOt_PtrSize_COCD),6)),(pOt_LONGINT)(pOt_i),6))]!=(unsigned char)(*((pOt_CHAR*)(((char *)pOt_s_AllocString_COCD+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s_AllocString_COCD))->nofel,pOt_i))))))) {
          goto pOt__LoopLabel_2;
        }
#line 46 "cocd.mod"
      }
#line 46 "cocd.mod"
    pOt__LoopLabel_2:;
#line 46 "cocd.mod"
      if(( pOt_i==((pOt_INTEGER)(-1)))) {
        goto pOt__LoopLabel_1;
      }
#line 48 "cocd.mod"
    }
#line 48 "cocd.mod"
    (*pOt_start_AllocString_COCD)+=((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_PtrSize_COCD),(pOt_LONGINT)(pOt_clen),6)),(pOt_LONGINT)(1),6));
    (*pOt_rem_AllocString_COCD)=(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)((*pOt_start_AllocString_COCD)),(pOt_LONGINT)(pOt_PtrSize_COCD),6));
    if(( (*pOt_rem_AllocString_COCD)!=((pOt_LONGINT)(0)))) {
#line 50 "cocd.mod"
      (*pOt_start_AllocString_COCD)+=((pOt_LONGINT)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_PtrSize_COCD),(pOt_LONGINT)((*pOt_rem_AllocString_COCD)),6));
    }
#line 51 "cocd.mod"
  }
pOt__LoopLabel_1:;
#line 52 "cocd.mod"

#line 52 "cocd.mod"
pOt__Epilogue:;
#line 52 "cocd.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 52 "cocd.mod"
}
#line 52 "cocd.mod"

#line 52 "cocd.mod"
extern void pOt_AllocString_COCD
#line 54 "cocd.mod"
#if pOt__ANSI_C
#line 54 "cocd.mod"
  (pOt__DynArr *pOt_s, struct pOt__tag_3_COCT *pOt_x)
#line 54 "cocd.mod"
#else
#line 54 "cocd.mod"
  (pOt_s, pOt_x)
#line 54 "cocd.mod"
  pOt__DynArr *pOt_s;
#line 54 "cocd.mod"
  struct pOt__tag_3_COCT *pOt_x;
#line 54 "cocd.mod"

#line 54 "cocd.mod"
#endif
#line 54 "cocd.mod"
{
#line 54 "cocd.mod"
  pOt__DynArr *pOt_s_;
#line 54 "cocd.mod"
  struct pOt__tag_3_COCT *pOt_x_;
#line 54 "cocd.mod"
  pOt_LONGINT pOt_start, (*pOt_start_), pOt_rem, (*pOt_rem_);
#line 54 "cocd.mod"
  pOt_INTEGER pOt_i, (*pOt_i_);
#line 54 "cocd.mod"
  pOt_CHAR pOt_ch, (*pOt_ch_);
#line 54 "cocd.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 54 "cocd.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 54 "cocd.mod"
  pOt_s_=pOt_s_AllocString_COCD;
#line 54 "cocd.mod"
  pOt_s_AllocString_COCD=pOt_s;
#line 54 "cocd.mod"
  pOt_x_=pOt_x_AllocString_COCD;
#line 54 "cocd.mod"
  pOt_x_AllocString_COCD=pOt_x;
#line 54 "cocd.mod"
  pOt_start_=pOt_start_AllocString_COCD;
#line 54 "cocd.mod"
  pOt_start_AllocString_COCD=&pOt_start;
#line 54 "cocd.mod"
  pOt_rem_=pOt_rem_AllocString_COCD;
#line 54 "cocd.mod"
  pOt_rem_AllocString_COCD=&pOt_rem;
#line 54 "cocd.mod"
  pOt_i_=pOt_i_AllocString_COCD;
#line 54 "cocd.mod"
  pOt_i_AllocString_COCD=&pOt_i;
#line 54 "cocd.mod"
  pOt_ch_=pOt_ch_AllocString_COCD;
#line 54 "cocd.mod"
  pOt_ch_AllocString_COCD=&pOt_ch;
#line 54 "cocd.mod"

#line 54 "cocd.mod"
  pOt_FindString_AllocString_COCD();
#line 54 "cocd.mod"
  (*pOt_x).pOt_intval+=((pOt_LONGINT)pOt__mulchk(__FILE__,__LINE__,(pOt_LONGINT)(((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_start),(pOt_LONGINT)(1),6))),(pOt_LONGINT)(256),6));
  if(( pOt_start==pOt_conx_COCD)) {
    pOt_i=(pOt_INTEGER)(-1);
#line 56 "cocd.mod"
    pOt_conx_COCD+=(pOt_PtrSize_COCD);
    for(;;) {
#line 57 "cocd.mod"
      pOt_i+=(1);
#line 57 "cocd.mod"
      pOt_ch=(*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i)))));
      if(( pOt_conx_COCD>=((pOt_LONGINT)(16384)))) {
#line 58 "cocd.mod"
        pOt_Mark_COCS((pOt_INTEGER)(230));
#line 58 "cocd.mod"
        pOt_conx_COCD=(pOt_LONGINT)(0);
#line 58 "cocd.mod"
      }
#line 58 "cocd.mod"
      pOt_constant_COCD.arr[pOt__inxchk(__FILE__,__LINE__,0x4000, pOt_conx_COCD)]=pOt_ch;
      pOt_conx_COCD+=(1);
      if(((unsigned char) pOt_ch==(unsigned char)'\0')) break;
    }
#line 61 "cocd.mod"
    pOt_rem=(pOt_LONGINT)((pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_conx_COCD),(pOt_LONGINT)(pOt_PtrSize_COCD),6));
#line 61 "cocd.mod"
    if(( pOt_rem!=((pOt_LONGINT)(0)))) {
#line 63 "cocd.mod"
      pOt_conx_COCD+=((pOt_LONGINT)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_PtrSize_COCD),(pOt_LONGINT)(pOt_rem),6));
      if(( pOt_conx_COCD>=((pOt_LONGINT)(16384)))) {
#line 64 "cocd.mod"
        pOt_Mark_COCS((pOt_INTEGER)(230));
#line 64 "cocd.mod"
        pOt_conx_COCD=(pOt_LONGINT)(0);
      }
#line 65 "cocd.mod"
    }
#line 65 "cocd.mod"
    pOt_constant_COCD.arr[pOt__inxchk(__FILE__,__LINE__,0x4000, pOt_start)]=(pOt_CHAR)pOt__rngchk_cn(__FILE__,__LINE__,(unsigned char)(pOt_i));
#line 67 "cocd.mod"
  }
#line 67 "cocd.mod"

pOt__Epilogue:;
#line 68 "cocd.mod"
  pOt_s_AllocString_COCD=pOt_s_;
#line 68 "cocd.mod"
  pOt_x_AllocString_COCD=pOt_x_;
#line 68 "cocd.mod"
  pOt_start_AllocString_COCD=pOt_start_;
#line 68 "cocd.mod"
  pOt_rem_AllocString_COCD=pOt_rem_;
#line 68 "cocd.mod"
  pOt_i_AllocString_COCD=pOt_i_;
#line 68 "cocd.mod"
  pOt_ch_AllocString_COCD=pOt_ch_;
#line 68 "cocd.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 68 "cocd.mod"
}
#line 68 "cocd.mod"

#line 68 "cocd.mod"

#line 74 "cocd.mod"
struct pOt__tag_2_COCD {
#line 74 "cocd.mod"
  pOt__ArrTypDsc *td;
#line 74 "cocd.mod"
  pOt_CHAR arr[0x9L];
#line 74 "cocd.mod"
} ;
#line 74 "cocd.mod"
static pOt__ArrTypDsc pOt__td_2_COCD= {
#line 74 "cocd.mod"
  1,
#line 74 "cocd.mod"
  0x9L, sizeof(pOt_CHAR)
#line 74 "cocd.mod"
};
#line 74 "cocd.mod"

#line 74 "cocd.mod"
static struct pOt__tag_2_COCD (*pOt_s_InitStrings_COCD);
#line 74 "cocd.mod"
static pOt_LONGINT (*pOt_i_InitStrings_COCD);
#line 74 "cocd.mod"

#line 74 "cocd.mod"
extern void pOt_InitStrings_COCD pOt__ARGS((void));
#line 74 "cocd.mod"

#line 74 "cocd.mod"

#line 77 "cocd.mod"

#line 77 "cocd.mod"

#line 77 "cocd.mod"
static void pOt_WriteChar_InitStrings_COCD
#line 77 "cocd.mod"
#if pOt__ANSI_C
#line 77 "cocd.mod"
  (pOt_CHAR pOt_c)
#line 77 "cocd.mod"
#else
#line 77 "cocd.mod"
  (pOt_c)
#line 77 "cocd.mod"
  pOt_CHAR pOt_c;
#line 77 "cocd.mod"

#line 77 "cocd.mod"
#endif
#line 77 "cocd.mod"
{
#line 77 "cocd.mod"
  pOt_INTEGER pOt_i;
#line 77 "cocd.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 77 "cocd.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 77 "cocd.mod"

#line 77 "cocd.mod"
  (*pOt_s_InitStrings_COCD).arr[pOt__inxchk(__FILE__,__LINE__,0x9, 0)]='\'';
  if((((((unsigned char)pOt_c==(unsigned char)'\\'))||(((unsigned char)pOt_c==(unsigned char)'\'')))||(((unsigned char)pOt_c==(unsigned char)'\"')))) {
    (*pOt_s_InitStrings_COCD).arr[pOt__inxchk(__FILE__,__LINE__,0x9, 1)]='\\';
#line 79 "cocd.mod"
    (*pOt_s_InitStrings_COCD).arr[pOt__inxchk(__FILE__,__LINE__,0x9, 2)]=pOt_c;
#line 79 "cocd.mod"
    pOt_i=(pOt_INTEGER)(3);
  } else if((((((unsigned char)'\0'<=(unsigned char)pOt_c))&&(((unsigned char)pOt_c<=(unsigned char)'\37')))||((((unsigned char)'\177'<=(unsigned char)pOt_c))&&(((unsigned char)pOt_c<=(unsigned char)'\377'))))) {
    (*pOt_s_InitStrings_COCD).arr[pOt__inxchk(__FILE__,__LINE__,0x9, 1)]='\\';
#line 81 "cocd.mod"
    (*pOt_s_InitStrings_COCD).arr[pOt__inxchk(__FILE__,__LINE__,0x9, 2)]='\0';
    pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt_s_InitStrings_COCD)));
    pOt_FromLInt_Strings((pOt_LONGINT)((pOt_INTEGER)((unsigned char)pOt_c)),8,(pOt__ArrTypDsc**)&(*pOt_s_InitStrings_COCD));
#line 83 "cocd.mod"
    pOt_i=(pOt_INTEGER)(0);
    for(;;) {
#line 84 "cocd.mod"
      if(((unsigned char) (*pOt_s_InitStrings_COCD).arr[pOt__inxchk(__FILE__,__LINE__,0x9, pOt_i)]!=(unsigned char)'\0')); else break;
#line 84 "cocd.mod"
      pOt_i+=(1);
    }
#line 85 "cocd.mod"
  } else {
    (*pOt_s_InitStrings_COCD).arr[pOt__inxchk(__FILE__,__LINE__,0x9, 1)]=pOt_c;
#line 86 "cocd.mod"
    pOt_i=(pOt_INTEGER)(2);
  }
#line 87 "cocd.mod"
  (*pOt_s_InitStrings_COCD).arr[pOt__inxchk(__FILE__,__LINE__,0x9, pOt_i)]='\'';
  (*pOt_s_InitStrings_COCD).arr[pOt__inxchk(__FILE__,__LINE__,0x9, (pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_i),(pOt_LONGINT)(1),5))]='\0';
  pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt_s_InitStrings_COCD)));

#line 90 "cocd.mod"
pOt__Epilogue:;
#line 90 "cocd.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 90 "cocd.mod"
}
#line 90 "cocd.mod"

#line 90 "cocd.mod"
extern void pOt_InitStrings_COCD()
#line 93 "cocd.mod"
{
#line 93 "cocd.mod"
  struct pOt__tag_2_COCD pOt_s, (*pOt_s_);
#line 93 "cocd.mod"
  pOt_LONGINT pOt_i, (*pOt_i_);
#line 93 "cocd.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 93 "cocd.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 93 "cocd.mod"
  pOt_s_=pOt_s_InitStrings_COCD;
#line 93 "cocd.mod"
  pOt_s_InitStrings_COCD=&pOt_s;
#line 93 "cocd.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_s,(pOt__TypDsc*)&pOt__td_2_COCD);
#line 93 "cocd.mod"
  pOt_i_=pOt_i_InitStrings_COCD;
#line 93 "cocd.mod"
  pOt_i_InitStrings_COCD=&pOt_i;
#line 93 "cocd.mod"

#line 93 "cocd.mod"
  if(( pOt_conx_COCD!=((pOt_LONGINT)(0)))) {
    pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x22]))));
    pOt_FromLInt_Strings((pOt_LONGINT)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_conx_COCD),(pOt_LONGINT)(2048),6)),16,(pOt__ArrTypDsc**)&pOt_s);
#line 95 "cocd.mod"
    pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&pOt_s));
    pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x28L],&pOt__str_td[0x4]))));
#line 96 "cocd.mod"
    pOt_Wrap_COCO();
    pOt_Indent_COCO();
    pOt_i=(pOt_LONGINT)(0);
    for(;;) {
#line 99 "cocd.mod"
      if(( pOt_i!=pOt_conx_COCD)); else break;
#line 99 "cocd.mod"
      pOt_WriteChar_InitStrings_COCD(pOt_constant_COCD.arr[pOt__inxchk(__FILE__,__LINE__,0x4000, pOt_i)]);
#line 99 "cocd.mod"
      pOt_i+=(1);
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x34L],&pOt__str_td[0x1]))));
#line 100 "cocd.mod"
      if(( (pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_i),(pOt_LONGINT)(16),6)==((pOt_LONGINT)(0)))) {
#line 100 "cocd.mod"
        pOt_Wrap_COCO();
      }
#line 101 "cocd.mod"
    }
#line 101 "cocd.mod"
    pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x3CL],&pOt__str_td[0x1]))));
    pOt_Wrap_COCO();
    pOt_Undent_COCO();
    pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x44L],&pOt__str_td[0x2]))));
#line 104 "cocd.mod"
    pOt_Wrap_COCO();
  }
#line 105 "cocd.mod"

pOt__Epilogue:;
#line 106 "cocd.mod"
  pOt_s_InitStrings_COCD=pOt_s_;
#line 106 "cocd.mod"
  pOt_i_InitStrings_COCD=pOt_i_;
#line 106 "cocd.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 106 "cocd.mod"
}
#line 106 "cocd.mod"

#line 106 "cocd.mod"

#line 109 "cocd.mod"

#line 109 "cocd.mod"

#line 109 "cocd.mod"
extern void pOt_AllocTypDesc_COCD
#line 109 "cocd.mod"
#if pOt__ANSI_C
#line 109 "cocd.mod"
  (pOt_Struct_COCT pOt_typ)
#line 109 "cocd.mod"
#else
#line 109 "cocd.mod"
  (pOt_typ)
#line 109 "cocd.mod"
  pOt_Struct_COCT pOt_typ;
#line 109 "cocd.mod"

#line 109 "cocd.mod"
#endif
#line 109 "cocd.mod"
{
#line 109 "cocd.mod"
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
#line 109 "cocd.mod"
  struct {void *next, *vars[0x1];} pOt__gc_strs;
#line 109 "cocd.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 109 "cocd.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 109 "cocd.mod"
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
#line 109 "cocd.mod"
  pOt__gc_strs.vars[0x0]=pOt_NIL;
#line 109 "cocd.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_typ;
#line 109 "cocd.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 109 "cocd.mod"

#line 109 "cocd.mod"
  (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_descr=(pOt_INTEGER)(pOt_recnum_COCD);
#line 109 "cocd.mod"
  pOt_recnum_COCD+=(1);
#line 109 "cocd.mod"
  if(((((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_form==17))&&(((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_n>((pOt_LONGINT)(16)))))) {
    pOt_Mark_COCS((pOt_INTEGER)(233));
  } else if(( pOt_nofrec_COCD<128)) {
    pOt_RecTab_COCD.arr[pOt__inxchk(__FILE__,__LINE__,0x80, pOt_nofrec_COCD)]=(struct pOt__tag_2_COCT*)(pOt_typ);
#line 112 "cocd.mod"
    pOt_nofrec_COCD+=(1);
  } else {
#line 113 "cocd.mod"
    pOt_Mark_COCS((pOt_INTEGER)(223));
  }
#line 114 "cocd.mod"

pOt__Epilogue:;
#line 115 "cocd.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 115 "cocd.mod"
}
#line 115 "cocd.mod"

#line 115 "cocd.mod"

#line 120 "cocd.mod"

#line 120 "cocd.mod"

#line 120 "cocd.mod"
extern void pOt_DeclTypDescs_COCD()
#line 120 "cocd.mod"
{
#line 120 "cocd.mod"
  pOt_INTEGER pOt_iofrec;
#line 120 "cocd.mod"
  pOt_Struct_COCT pOt_typ;
#line 120 "cocd.mod"
  pOt_INTEGER pOt_np;
#line 120 "cocd.mod"
  struct pOt__tag_3_COCT pOt_x;
#line 120 "cocd.mod"
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
#line 120 "cocd.mod"
  struct {void *next, *vars[0x2];} pOt__gc_strs;
#line 120 "cocd.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 120 "cocd.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 120 "cocd.mod"
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
#line 120 "cocd.mod"
  pOt__gc_strs.vars[0x1]=pOt_NIL;
#line 120 "cocd.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_typ;
#line 120 "cocd.mod"
  pOt__gc_strs.vars[0x0]=&pOt_x;
#line 120 "cocd.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 120 "cocd.mod"
  pOt_typ=pOt_NIL;
#line 120 "cocd.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_x,(pOt__TypDsc*)&pOt__td_3_COCT);
#line 120 "cocd.mod"

#line 120 "cocd.mod"
  pOt_iofrec=(pOt_INTEGER)(0);
  for(;;) {
#line 121 "cocd.mod"
    if(( pOt_iofrec!=pOt_nofrec_COCD)); else break;
    pOt_typ=(struct pOt__tag_2_COCT*)(pOt_RecTab_COCD.arr[pOt__inxchk(__FILE__,__LINE__,0x80, pOt_iofrec)]);
    if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_ref!=((pOt_INTEGER)(0)))) {
      pOt_Struct_COCY((struct pOt__tag_2_COCT*)(pOt_typ));
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x4CL],&pOt__str_td[0x6]))));
#line 125 "cocd.mod"
      pOt_Separate_COCO();
      switch((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_form) {
      case 15:
        switch((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_BaseTyp))).pOt_form) {
        case 0:
#line 129 "cocd.mod"
        case 1:
#line 129 "cocd.mod"
        case 2:
#line 129 "cocd.mod"
        case 3:
#line 129 "cocd.mod"
        case 4:
#line 129 "cocd.mod"
        case 5:
#line 129 "cocd.mod"
        case 6:
#line 129 "cocd.mod"
        case 7:
#line 129 "cocd.mod"
        case 8:
#line 129 "cocd.mod"
        case 9:
#line 129 "cocd.mod"
          pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x58L],&pOt__str_td[0xE]))));
        break;
#line 130 "cocd.mod"
        case 13:
#line 130 "cocd.mod"
        case 14:
#line 130 "cocd.mod"
          pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x6CL],&pOt__str_td[0x11]))));
        break;
#line 131 "cocd.mod"
        case 10:
        case 11:
#line 132 "cocd.mod"
        case 12:
#line 132 "cocd.mod"
        break;
#line 132 "cocd.mod"
        case 15:
#line 132 "cocd.mod"
        case 17:
#line 132 "cocd.mod"
          pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x84L],&pOt__str_td[0x11]))));
        break;
#line 133 "cocd.mod"
        case 16:
        break;
        default:;
#line 135 "cocd.mod"
          pOt__halt(__FILE__,__LINE__,0x10);
#line 135 "cocd.mod"
        }
#line 135 "cocd.mod"
      break;
#line 135 "cocd.mod"
      case 17:
#line 135 "cocd.mod"
        pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x9CL],&pOt__str_td[0xE]))));
      break;
#line 136 "cocd.mod"
      default:;
#line 136 "cocd.mod"
        pOt__halt(__FILE__,__LINE__,0x10);
#line 136 "cocd.mod"
      }
#line 136 "cocd.mod"
      pOt_Separate_COCO();
      pOt_Mark_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
#line 137 "cocd.mod"
      pOt_CTDName_COCN((struct pOt__tag_2_COCT*)(pOt_typ),(pOt_INTEGER)(pOt_x.pOt_qoffs),&pOt_np);
#line 137 "cocd.mod"
      pOt_Release_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xB0L],&pOt__str_td[0x1]))));
#line 138 "cocd.mod"
      pOt_Wrap_COCO();
    }
#line 139 "cocd.mod"
    pOt_iofrec+=(1);
#line 142 "cocd.mod"
  }
#line 142 "cocd.mod"

#line 142 "cocd.mod"
pOt__Epilogue:;
#line 142 "cocd.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 142 "cocd.mod"
}
#line 142 "cocd.mod"

#line 142 "cocd.mod"

#line 151 "cocd.mod"
struct pOt__tag_3_COCD {
#line 151 "cocd.mod"
  pOt__ArrTypDsc *td;
#line 151 "cocd.mod"
  pOt_CHAR arr[0x9L];
#line 151 "cocd.mod"
} ;
#line 151 "cocd.mod"
static pOt__ArrTypDsc pOt__td_3_COCD= {
#line 151 "cocd.mod"
  1,
#line 151 "cocd.mod"
  0x9L, sizeof(pOt_CHAR)
#line 151 "cocd.mod"
};
#line 151 "cocd.mod"
struct pOt__tag_4_COCD {
#line 151 "cocd.mod"
  pOt__PtrArrTypDsc *td;
#line 151 "cocd.mod"
  pOt_Struct_COCT arr[0x10L];
#line 151 "cocd.mod"
} ;
#line 151 "cocd.mod"
static pOt__PtrArrTypDsc pOt__td_4_COCD= {
#line 151 "cocd.mod"
  2,
#line 151 "cocd.mod"
  0x10L, sizeof(struct pOt__tag_2_COCT*)
#line 151 "cocd.mod"
};
#line 151 "cocd.mod"

#line 151 "cocd.mod"

#line 151 "cocd.mod"
extern void pOt_InitTypDescs_COCD()
#line 151 "cocd.mod"
{
#line 151 "cocd.mod"
  pOt_INTEGER pOt_iofrec;
#line 151 "cocd.mod"
  pOt_Struct_COCT pOt_typ;
#line 151 "cocd.mod"
  pOt_INTEGER pOt_np;
#line 151 "cocd.mod"
  struct pOt__tag_3_COCT pOt_x;
#line 151 "cocd.mod"
  struct pOt__tag_3_COCD pOt_s;
#line 151 "cocd.mod"
  pOt_INTEGER pOt_mode, pOt_nstr, pOt_nptr, pOt_npro, pOt_ifld, pOt_nfld;
#line 151 "cocd.mod"
  pOt_Object_COCT pOt_fld;
#line 151 "cocd.mod"
  pOt_INTEGER pOt_iext;
#line 151 "cocd.mod"
  pOt_Struct_COCT pOt_base;
#line 151 "cocd.mod"
  struct pOt__tag_4_COCD pOt_basetyps;
#line 151 "cocd.mod"
  struct {void *next, *vars[0x4];} pOt__gc_ptrs;
#line 151 "cocd.mod"
  struct {void *next, *vars[0x3];} pOt__gc_strs;
#line 151 "cocd.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 151 "cocd.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 151 "cocd.mod"
  pOt__gc_ptrs.vars[0x3]=pOt_NIL;
#line 151 "cocd.mod"
  pOt__gc_strs.vars[0x2]=pOt_NIL;
#line 151 "cocd.mod"
  pOt__gc_ptrs.vars[0x2]=&pOt_typ;
#line 151 "cocd.mod"
  pOt__gc_strs.vars[0x1]=&pOt_x;
#line 151 "cocd.mod"
  pOt__gc_ptrs.vars[0x1]=&pOt_fld;
#line 151 "cocd.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_base;
#line 151 "cocd.mod"
  pOt__gc_strs.vars[0x0]=&pOt_basetyps;
#line 151 "cocd.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 151 "cocd.mod"
  pOt_typ=pOt_NIL;
#line 151 "cocd.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_x,(pOt__TypDsc*)&pOt__td_3_COCT);
#line 151 "cocd.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_s,(pOt__TypDsc*)&pOt__td_3_COCD);
#line 151 "cocd.mod"
  pOt_fld=pOt_NIL;
#line 151 "cocd.mod"
  pOt_base=pOt_NIL;
#line 151 "cocd.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_basetyps,(pOt__TypDsc*)&pOt__td_4_COCD);
#line 151 "cocd.mod"

#line 151 "cocd.mod"
  pOt_iofrec=(pOt_INTEGER)(pOt_bofrec_COCD);
  for(;;) {
#line 152 "cocd.mod"
    if(( pOt_iofrec!=pOt_nofrec_COCD)); else break;
    pOt_typ=(struct pOt__tag_2_COCT*)(pOt_RecTab_COCD.arr[pOt__inxchk(__FILE__,__LINE__,0x80, pOt_iofrec)]);
    pOt_Struct_COCY((struct pOt__tag_2_COCT*)(pOt_typ));
    if(( pOt_level_COCT!=((pOt_INTEGER)(0)))) {
#line 155 "cocd.mod"
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xB8L],&pOt__str_td[0x6]))));
#line 155 "cocd.mod"
      pOt_Separate_COCO();
#line 155 "cocd.mod"
    }
#line 155 "cocd.mod"
    switch((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_form) {
#line 157 "cocd.mod"
    case 15:
      switch((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_BaseTyp))).pOt_form) {
      case 0:
#line 159 "cocd.mod"
      case 1:
#line 159 "cocd.mod"
      case 2:
#line 159 "cocd.mod"
      case 3:
#line 159 "cocd.mod"
      case 4:
#line 159 "cocd.mod"
      case 5:
#line 159 "cocd.mod"
      case 6:
#line 159 "cocd.mod"
      case 7:
#line 159 "cocd.mod"
      case 8:
#line 159 "cocd.mod"
      case 9:
#line 159 "cocd.mod"
        pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x58L],&pOt__str_td[0xE]))));
#line 159 "cocd.mod"
        pOt_mode=(pOt_INTEGER)(1);
      break;
#line 160 "cocd.mod"
      case 13:
#line 160 "cocd.mod"
        pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x6CL],&pOt__str_td[0x11]))));
#line 160 "cocd.mod"
        pOt_mode=(pOt_INTEGER)(2);
      break;
#line 161 "cocd.mod"
      case 14:
#line 161 "cocd.mod"
        pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x6CL],&pOt__str_td[0x11]))));
#line 161 "cocd.mod"
        pOt_mode=(pOt_INTEGER)(3);
      break;
#line 162 "cocd.mod"
      case 10:
      case 11:
#line 163 "cocd.mod"
      case 12:
#line 163 "cocd.mod"
      break;
#line 163 "cocd.mod"
      case 15:
#line 163 "cocd.mod"
      case 17:
#line 163 "cocd.mod"
        pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x84L],&pOt__str_td[0x11]))));
#line 163 "cocd.mod"
        pOt_mode=(pOt_INTEGER)(4);
      break;
#line 164 "cocd.mod"
      case 16:
      break;
      default:;
#line 166 "cocd.mod"
        pOt__halt(__FILE__,__LINE__,0x10);
#line 166 "cocd.mod"
      }
#line 166 "cocd.mod"
    break;
#line 166 "cocd.mod"
    case 17:
#line 166 "cocd.mod"
      pOt_mode=(pOt_INTEGER)(0);
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xC4L],&pOt__str_td[0x8]))));
#line 167 "cocd.mod"
      pOt_Wrap_COCO();
#line 167 "cocd.mod"
      pOt_Indent_COCO();
#line 169 "cocd.mod"
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xD4L],&pOt__str_td[0x11]))));
#line 169 "cocd.mod"
      pOt_Wrap_COCO();
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xECL],&pOt__str_td[0x11]))));
#line 170 "cocd.mod"
      pOt_Wrap_COCO();
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x104L],&pOt__str_td[0x25]))));
#line 171 "cocd.mod"
      pOt_Wrap_COCO();
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x130L],&pOt__str_td[0x26]))));
#line 172 "cocd.mod"
      pOt_Wrap_COCO();
      pOt_nstr=(pOt_INTEGER)(0);
#line 173 "cocd.mod"
      pOt_nptr=(pOt_INTEGER)(0);
#line 173 "cocd.mod"
      pOt_npro=(pOt_INTEGER)(0);
#line 173 "cocd.mod"
      pOt_fld=(struct pOt__tag_1_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_link);
      for(;;) {
#line 174 "cocd.mod"
        if(( pOt_fld!=pOt_NIL)); else break;
        if(pOt__cmpss((pOt_CHAR*)& (*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_fld))).pOt_name,&pOt__strcon_buf[0x15CL],0xA)) {
          if(((unsigned long)0!=((unsigned long)1<<pOt__rngchk_se(__FILE__,__LINE__, (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_fld))).pOt_typ))).pOt_form)&(pOt_SET)0x28000L))) {
#line 176 "cocd.mod"
            pOt_nstr+=(1);
          } else if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_fld))).pOt_typ))).pOt_form==13)) {
#line 177 "cocd.mod"
            pOt_nptr+=(1);
          } else if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_fld))).pOt_typ))).pOt_form==14)) {
#line 178 "cocd.mod"
            pOt_npro+=(1);
#line 180 "cocd.mod"
          }
#line 180 "cocd.mod"
        }
#line 180 "cocd.mod"
        pOt_fld=(struct pOt__tag_1_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_fld))).pOt_next);
#line 182 "cocd.mod"
      }
#line 182 "cocd.mod"
      pOt_nfld=(pOt_INTEGER)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_nstr),(pOt_LONGINT)(pOt_nptr),5)),(pOt_LONGINT)(pOt_npro),5));
#line 184 "cocd.mod"
      if(( pOt_nfld!=((pOt_INTEGER)(0)))) {
        pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x164L],&pOt__str_td[0x37]))));
        pOt_FromLInt_Strings((pOt_LONGINT)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_nstr),(pOt_LONGINT)(pOt_nptr),5)),(pOt_LONGINT)(pOt_npro),5)),16,(pOt__ArrTypDsc**)&pOt_s);
#line 186 "cocd.mod"
        pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&pOt_s));
#line 186 "cocd.mod"
        pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1A0L],&pOt__str_td[0x2]))));
#line 186 "cocd.mod"
        pOt_Wrap_COCO();
      }
#line 187 "cocd.mod"
      pOt_Undent_COCO();
#line 189 "cocd.mod"
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1A8L],&pOt__str_td[0x1]))));
    break;
#line 190 "cocd.mod"
    default:;
#line 190 "cocd.mod"
      pOt__halt(__FILE__,__LINE__,0x10);
#line 190 "cocd.mod"
    }
#line 190 "cocd.mod"
    pOt_Separate_COCO();
    pOt_Mark_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
#line 191 "cocd.mod"
    pOt_CTDName_COCN((struct pOt__tag_2_COCT*)(pOt_typ),(pOt_INTEGER)(pOt_x.pOt_qoffs),&pOt_np);
#line 191 "cocd.mod"
    pOt_Release_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
    pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1B0L],&pOt__str_td[0x3]))));
#line 192 "cocd.mod"
    pOt_Wrap_COCO();
    pOt_Indent_COCO();
    pOt_FromLInt_Strings((pOt_LONGINT)(pOt_mode),10,(pOt__ArrTypDsc**)&pOt_s);
#line 194 "cocd.mod"
    pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&pOt_s));
#line 194 "cocd.mod"
    pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x34L],&pOt__str_td[0x1]))));
    pOt_Wrap_COCO();
    switch((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_form) {
    case 15:
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1B8L],&pOt__str_td[0x2]))));
      pOt_FromLInt_Strings((pOt_LONGINT)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_n),16,(pOt__ArrTypDsc**)&pOt_s);
#line 199 "cocd.mod"
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&pOt_s));
#line 199 "cocd.mod"
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1C0L],&pOt__str_td[0x3]))));
      pOt_Link_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
#line 200 "cocd.mod"
      pOt_CTSize_COCN((struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_BaseTyp),(pOt_INTEGER)(pOt_x.pOt_qoffs),&pOt_np);
#line 200 "cocd.mod"
      pOt_Unlink_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
      if(( pOt_mode==((pOt_INTEGER)(4)))) {
        pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x34L],&pOt__str_td[0x1]))));
#line 202 "cocd.mod"
        pOt_Wrap_COCO();
        pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1C8L],&pOt__str_td[0xF]))));
#line 203 "cocd.mod"
        pOt_Link_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
#line 203 "cocd.mod"
        pOt_CTDName_COCN((struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_BaseTyp),(pOt_INTEGER)(pOt_x.pOt_qoffs),&pOt_np);
#line 203 "cocd.mod"
        pOt_Unlink_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
      }
#line 204 "cocd.mod"
      pOt_Wrap_COCO();
#line 206 "cocd.mod"
    break;
#line 206 "cocd.mod"
    case 17:
      pOt_Link_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
#line 207 "cocd.mod"
      pOt_CTSize_COCN((struct pOt__tag_2_COCT*)(pOt_typ),(pOt_INTEGER)(pOt_x.pOt_qoffs),&pOt_np);
#line 207 "cocd.mod"
      pOt_Unlink_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
#line 207 "cocd.mod"
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x34L],&pOt__str_td[0x1]))));
      pOt_Wrap_COCO();
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1B8L],&pOt__str_td[0x2]))));
#line 209 "cocd.mod"
      pOt_FromLInt_Strings((pOt_LONGINT)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_n),16,(pOt__ArrTypDsc**)&pOt_s);
#line 209 "cocd.mod"
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&pOt_s));
#line 209 "cocd.mod"
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1DCL],&pOt__str_td[0x2]))));
#line 211 "cocd.mod"
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1B8L],&pOt__str_td[0x2]))));
#line 211 "cocd.mod"
      pOt_FromLInt_Strings((pOt_LONGINT)(pOt_nstr),16,(pOt__ArrTypDsc**)&pOt_s);
#line 211 "cocd.mod"
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&pOt_s));
#line 211 "cocd.mod"
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1DCL],&pOt__str_td[0x2]))));
#line 213 "cocd.mod"
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1B8L],&pOt__str_td[0x2]))));
#line 213 "cocd.mod"
      pOt_FromLInt_Strings((pOt_LONGINT)(pOt_nptr),16,(pOt__ArrTypDsc**)&pOt_s);
#line 213 "cocd.mod"
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&pOt_s));
#line 213 "cocd.mod"
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1DCL],&pOt__str_td[0x2]))));
#line 215 "cocd.mod"
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1B8L],&pOt__str_td[0x2]))));
#line 215 "cocd.mod"
      pOt_FromLInt_Strings((pOt_LONGINT)(pOt_npro),16,(pOt__ArrTypDsc**)&pOt_s);
#line 215 "cocd.mod"
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&pOt_s));
#line 215 "cocd.mod"
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x34L],&pOt__str_td[0x1]))));
      pOt_Wrap_COCO();
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1E4L],&pOt__str_td[0x1]))));
      pOt_iext=(pOt_INTEGER)((pOt_LONGINT)pOt__rngchk_i(__FILE__,__LINE__,(*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_n));
#line 218 "cocd.mod"
      pOt_base=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_BaseTyp);
      for(;;) {
#line 219 "cocd.mod"
        if(( pOt_iext!=((pOt_INTEGER)(0)))); else break;
#line 219 "cocd.mod"
        pOt_iext-=(1);
        pOt_basetyps.arr[pOt__inxchk(__FILE__,__LINE__,0x10, pOt_iext)]=(struct pOt__tag_2_COCT*)(pOt_base);
        pOt_base=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_base))).pOt_BaseTyp);
      }
#line 222 "cocd.mod"
      if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_n!=((pOt_LONGINT)(0)))) {
#line 224 "cocd.mod"
        for(;;) {
#line 224 "cocd.mod"
          pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1ECL],&pOt__str_td[0x12]))));
#line 224 "cocd.mod"
          pOt_Link_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
          pOt_CTDName_COCN((struct pOt__tag_2_COCT*)(pOt_basetyps.arr[pOt__inxchk(__FILE__,__LINE__,0x10, pOt_iext)]),(pOt_INTEGER)(pOt_x.pOt_qoffs),&pOt_np);
#line 225 "cocd.mod"
          pOt_Unlink_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
          pOt_iext+=(1);
#line 226 "cocd.mod"
          if(( pOt_iext==(pOt_LONGINT)pOt__rngchk_i(__FILE__,__LINE__,(*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_n))) {
#line 226 "cocd.mod"
            goto pOt__LoopLabel_1;
#line 226 "cocd.mod"
          }
#line 226 "cocd.mod"
          pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1DCL],&pOt__str_td[0x2]))));
#line 229 "cocd.mod"
        }
#line 229 "cocd.mod"
      pOt__LoopLabel_1:;
#line 229 "cocd.mod"
      }
#line 229 "cocd.mod"
      if(( pOt_iext!=((pOt_INTEGER)(16)))) {
#line 231 "cocd.mod"
        if(( pOt_iext==((pOt_INTEGER)(0)))) {
#line 231 "cocd.mod"
          pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x204L],&pOt__str_td[0x7]))));
#line 231 "cocd.mod"
          pOt_iext+=(1);
#line 231 "cocd.mod"
        }
#line 231 "cocd.mod"
        for(;;) {
          if(( pOt_iext!=((pOt_INTEGER)(16)))); else break;
#line 232 "cocd.mod"
          pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x210L],&pOt__str_td[0x9]))));
#line 232 "cocd.mod"
          pOt_iext+=(1);
        }
#line 233 "cocd.mod"
      }
#line 233 "cocd.mod"
      pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1A8L],&pOt__str_td[0x1]))));
      if(( pOt_nfld!=((pOt_INTEGER)(0)))) {
        pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x34L],&pOt__str_td[0x1]))));
#line 235 "cocd.mod"
        pOt_Wrap_COCO();
#line 235 "cocd.mod"
        pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1E4L],&pOt__str_td[0x1]))));
        pOt_Wrap_COCO();
        pOt_Indent_COCO();
        pOt_x.pOt_mode=12;
#line 238 "cocd.mod"
        pOt_x.pOt_mnolev=(pOt_INTEGER)(0);
        pOt_ifld=(pOt_INTEGER)(0);
        if(( pOt_nstr!=((pOt_INTEGER)(0)))) {
          pOt_fld=(struct pOt__tag_1_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_link);
          for(;;) {
            if(((pOt__cmpss((pOt_CHAR*)&(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_fld))).pOt_name,&pOt__strcon_buf[0x15CL],0xA))&&(((unsigned long)0!=((unsigned long)1<<pOt__rngchk_se(__FILE__,__LINE__,(*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_fld))).pOt_typ))).pOt_form)&(pOt_SET)0x28000L))))) {
              pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x220L],&pOt__str_td[0x11]))));
              pOt_Link_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
#line 245 "cocd.mod"
              pOt_CTDenoter_COCN((struct pOt__tag_2_COCT*)(pOt_typ),(pOt_INTEGER)(pOt_x.pOt_qoffs),&pOt_np);
#line 245 "cocd.mod"
              pOt_Unlink_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
              pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x238L],&pOt__str_td[0x6]))));
              pOt_x.pOt_obj=(struct pOt__tag_1_COCT*)(pOt_fld);
#line 247 "cocd.mod"
              pOt_x.pOt_typ=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_fld))).pOt_typ);
              pOt_Link_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
#line 248 "cocd.mod"
              pOt_CObjName_COCN((struct pOt__tag_3_COCT*)&pOt_x,(pOt_INTEGER)(pOt_x.pOt_qoffs),&pOt_np);
#line 248 "cocd.mod"
              pOt_Unlink_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
              pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x244L],&pOt__str_td[0x11]))));
              pOt_Link_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
#line 250 "cocd.mod"
              pOt_CTDName_COCN((struct pOt__tag_2_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_fld))).pOt_typ),(pOt_INTEGER)(pOt_x.pOt_qoffs),&pOt_np);
#line 250 "cocd.mod"
              pOt_Unlink_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
              pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1A8L],&pOt__str_td[0x1]))));
              pOt_ifld+=(1);
              if(( pOt_ifld!=pOt_nfld)) {
#line 253 "cocd.mod"
                pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x34L],&pOt__str_td[0x1]))));
              }
#line 254 "cocd.mod"
            }
#line 254 "cocd.mod"
            if(( pOt_ifld==pOt_nstr)) {
              goto pOt__LoopLabel_2;
#line 255 "cocd.mod"
            }
#line 255 "cocd.mod"
            pOt_fld=(struct pOt__tag_1_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_fld))).pOt_next);
#line 257 "cocd.mod"
          }
#line 257 "cocd.mod"
        pOt__LoopLabel_2:;
#line 257 "cocd.mod"
          pOt_Wrap_COCO();
#line 259 "cocd.mod"
        }
#line 259 "cocd.mod"
        if(( pOt_nptr!=((pOt_INTEGER)(0)))) {
#line 261 "cocd.mod"
          pOt_nptr+=(pOt_nstr);
          pOt_fld=(struct pOt__tag_1_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_link);
          for(;;) {
            if(((pOt__cmpss((pOt_CHAR*)&(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_fld))).pOt_name,&pOt__strcon_buf[0x15CL],0xA))&&(((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_fld))).pOt_typ))).pOt_form==13)))) {
              pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x220L],&pOt__str_td[0x11]))));
              pOt_Link_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
#line 266 "cocd.mod"
              pOt_CTDenoter_COCN((struct pOt__tag_2_COCT*)(pOt_typ),(pOt_INTEGER)(pOt_x.pOt_qoffs),&pOt_np);
#line 266 "cocd.mod"
              pOt_Unlink_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
              pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x238L],&pOt__str_td[0x6]))));
              pOt_x.pOt_obj=(struct pOt__tag_1_COCT*)(pOt_fld);
#line 268 "cocd.mod"
              pOt_x.pOt_typ=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_fld))).pOt_typ);
              pOt_Link_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
#line 269 "cocd.mod"
              pOt_CObjName_COCN((struct pOt__tag_3_COCT*)&pOt_x,(pOt_INTEGER)(pOt_x.pOt_qoffs),&pOt_np);
#line 269 "cocd.mod"
              pOt_Unlink_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
              pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x25CL],&pOt__str_td[0xA]))));
              pOt_ifld+=(1);
              if(( pOt_ifld!=pOt_nfld)) {
#line 272 "cocd.mod"
                pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x34L],&pOt__str_td[0x1]))));
              }
#line 273 "cocd.mod"
            }
#line 273 "cocd.mod"
            if(( pOt_ifld==pOt_nptr)) {
              goto pOt__LoopLabel_3;
#line 274 "cocd.mod"
            }
#line 274 "cocd.mod"
            pOt_fld=(struct pOt__tag_1_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_fld))).pOt_next);
#line 276 "cocd.mod"
          }
#line 276 "cocd.mod"
        pOt__LoopLabel_3:;
#line 276 "cocd.mod"
          pOt_Wrap_COCO();
#line 278 "cocd.mod"
        }
#line 278 "cocd.mod"
        if(( pOt_npro!=((pOt_INTEGER)(0)))) {
#line 280 "cocd.mod"
          pOt_npro+=(pOt_nptr);
          pOt_fld=(struct pOt__tag_1_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_link);
          for(;;) {
            if(((pOt__cmpss((pOt_CHAR*)&(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_fld))).pOt_name,&pOt__strcon_buf[0x15CL],0xA))&&(((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_fld))).pOt_typ))).pOt_form==14)))) {
              pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x220L],&pOt__str_td[0x11]))));
              pOt_Link_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
#line 285 "cocd.mod"
              pOt_CTDenoter_COCN((struct pOt__tag_2_COCT*)(pOt_typ),(pOt_INTEGER)(pOt_x.pOt_qoffs),&pOt_np);
#line 285 "cocd.mod"
              pOt_Unlink_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
              pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x238L],&pOt__str_td[0x6]))));
              pOt_x.pOt_obj=(struct pOt__tag_1_COCT*)(pOt_fld);
#line 287 "cocd.mod"
              pOt_x.pOt_typ=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_fld))).pOt_typ);
              pOt_Link_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
#line 288 "cocd.mod"
              pOt_CObjName_COCN((struct pOt__tag_3_COCT*)&pOt_x,(pOt_INTEGER)(pOt_x.pOt_qoffs),&pOt_np);
#line 288 "cocd.mod"
              pOt_Unlink_COCQ((struct pOt__tag_3_COCT*)&pOt_x);
              pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x25CL],&pOt__str_td[0xA]))));
              pOt_ifld+=(1);
              if(( pOt_ifld!=pOt_nfld)) {
#line 291 "cocd.mod"
                pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x34L],&pOt__str_td[0x1]))));
              }
#line 292 "cocd.mod"
            }
#line 292 "cocd.mod"
            if(( pOt_ifld==pOt_npro)) {
              goto pOt__LoopLabel_4;
#line 293 "cocd.mod"
            }
#line 293 "cocd.mod"
            pOt_fld=(struct pOt__tag_1_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_fld))).pOt_next);
#line 295 "cocd.mod"
          }
#line 295 "cocd.mod"
        pOt__LoopLabel_4:;
#line 295 "cocd.mod"
          pOt_Wrap_COCO();
#line 297 "cocd.mod"
        }
#line 297 "cocd.mod"
        pOt_Undent_COCO();
#line 299 "cocd.mod"
        pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1A8L],&pOt__str_td[0x1]))));
      }
#line 300 "cocd.mod"
      pOt_Wrap_COCO();
#line 302 "cocd.mod"
    break;
#line 302 "cocd.mod"
    default:;
#line 302 "cocd.mod"
      pOt__halt(__FILE__,__LINE__,0x10);
#line 302 "cocd.mod"
    }
#line 302 "cocd.mod"
    pOt_Undent_COCO();
#line 304 "cocd.mod"
    pOt_PutSeq_COCO(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x44L],&pOt__str_td[0x2]))));
#line 304 "cocd.mod"
    pOt_Wrap_COCO();
    pOt_iofrec+=(1);
  }
#line 306 "cocd.mod"
  if(( pOt_level_COCT==((pOt_INTEGER)(0)))) {
    pOt_bofrec_COCD=(pOt_INTEGER)(pOt_nofrec_COCD);
  } else {
#line 308 "cocd.mod"
    pOt_nofrec_COCD=(pOt_INTEGER)(pOt_bofrec_COCD);
#line 310 "cocd.mod"
  }
#line 310 "cocd.mod"

#line 310 "cocd.mod"
pOt__Epilogue:;
#line 310 "cocd.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 310 "cocd.mod"
}
#line 310 "cocd.mod"

#line 310 "cocd.mod"
void pOt_COCD__body()
#line 312 "cocd.mod"
{
#line 312 "cocd.mod"
  static int pOt_COCD__loaded=0;
#line 312 "cocd.mod"
  if(!pOt_COCD__loaded){
#line 312 "cocd.mod"
    pOt_COCD__loaded=1;
#line 312 "cocd.mod"

#line 312 "cocd.mod"
    pOt_Strings__body();
#line 312 "cocd.mod"
    pOt_COCS__body();
#line 312 "cocd.mod"
    pOt_COCT__body();
#line 312 "cocd.mod"
    pOt_COCQ__body();
#line 312 "cocd.mod"
    pOt_COCN__body();
#line 312 "cocd.mod"
    pOt_COCY__body();
#line 312 "cocd.mod"
    pOt_COCO__body();
#line 312 "cocd.mod"

#line 312 "cocd.mod"
    pOt__gc_ptrs.next=pOt__gc_root;
#line 312 "cocd.mod"
    pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 312 "cocd.mod"

#line 312 "cocd.mod"
    pOt__init_var((pOt__TypDsc**)&pOt_constant_COCD,(pOt__TypDsc*)&pOt__td_0_COCD);
#line 312 "cocd.mod"
    pOt__init_var((pOt__TypDsc**)&pOt_RecTab_COCD,(pOt__TypDsc*)&pOt__td_1_COCD);
#line 312 "cocd.mod"

#line 312 "cocd.mod"
    pOt_PtrSize_COCD=(pOt_LONGINT)(4);

#line 313 "cocd.mod"
  pOt__Epilogue:;
#line 313 "cocd.mod"
  }
#line 313 "cocd.mod"
}
#line 313 "cocd.mod"
