/* This code is generated by pOt. */
#line 15 "coch.mod"

#line 15 "coch.mod"
#include <pOtRTL.h>
#line 15 "coch.mod"
#include "COCS.h"
#line 15 "coch.mod"
#include "COCT.h"
#line 15 "coch.mod"
#include "COCD.h"
#line 15 "coch.mod"
#include "COCQ.h"
#line 15 "coch.mod"
#include "COCP.h"
#line 15 "coch.mod"

#line 15 "coch.mod"
#include "COCH.hi"
#line 15 "coch.mod"

#line 15 "coch.mod"

#line 15 "coch.mod"

#line 15 "coch.mod"

#line 15 "coch.mod"
static struct {void *next, *vars[0x1];} pOt__gc_ptrs = {pOt_NIL,{
#line 15 "coch.mod"
  pOt_NIL
#line 15 "coch.mod"
}};
#line 15 "coch.mod"
static struct {void *next, *vars[0x1];} pOt__gc_strs = {&pOt__gc_ptrs,{
#line 15 "coch.mod"
  pOt_NIL
#line 15 "coch.mod"
}};
#line 15 "coch.mod"

#line 15 "coch.mod"

#line 17 "coch.mod"

#line 17 "coch.mod"

#line 17 "coch.mod"
extern pOt_INTEGER pOt_StartLinStmt_COCH
#line 17 "coch.mod"
#if pOt__ANSI_C
#line 17 "coch.mod"
  (struct pOt__tag_3_COCT *pOt_x)
#line 17 "coch.mod"
#else
#line 17 "coch.mod"
  (pOt_x)
#line 17 "coch.mod"
  struct pOt__tag_3_COCT *pOt_x;
#line 17 "coch.mod"

#line 17 "coch.mod"
#endif
#line 17 "coch.mod"
{
#line 17 "coch.mod"
  pOt_INTEGER pOt__retval;
#line 17 "coch.mod"
  pOt_INTEGER pOt_qoffs;
#line 17 "coch.mod"
  int pOt__gc_enabled_prev;
#line 17 "coch.mod"
  pOt__gc_enabled_prev=pOt__gc_enabled;
#line 17 "coch.mod"
  pOt__gc_enabled=0;
#line 17 "coch.mod"

#line 17 "coch.mod"
  pOt_qoffs=(pOt_INTEGER)((*pOt_x).pOt_qoffs);
#line 17 "coch.mod"
  pOt_Link_COCQ((struct pOt__tag_3_COCT*)&(*pOt_x));
#line 17 "coch.mod"
  if(( (*pOt_x).pOt_qoffs==((pOt_INTEGER)(0)))) {
    pOt_Dummy_COCQ();
#line 18 "coch.mod"
  }
#line 18 "coch.mod"
  pOt__retval =(pOt_INTEGER)(pOt_qoffs);
#line 20 "coch.mod"
  goto pOt__Epilogue;
#line 20 "coch.mod"

#line 20 "coch.mod"
  pOt__halt(__FILE__,__LINE__,0x11);
#line 20 "coch.mod"
pOt__Epilogue:;
#line 20 "coch.mod"
  pOt__gc_enabled=pOt__gc_enabled_prev;
#line 20 "coch.mod"
  return pOt__retval;
#line 20 "coch.mod"
}
#line 20 "coch.mod"

#line 20 "coch.mod"

#line 24 "coch.mod"

#line 24 "coch.mod"

#line 24 "coch.mod"
extern void pOt_StopLinStmt_COCH
#line 24 "coch.mod"
#if pOt__ANSI_C
#line 24 "coch.mod"
  (struct pOt__tag_3_COCT *pOt_x, pOt_INTEGER pOt_qoffs)
#line 24 "coch.mod"
#else
#line 24 "coch.mod"
  (pOt_x, pOt_qoffs)
#line 24 "coch.mod"
  struct pOt__tag_3_COCT *pOt_x;
#line 24 "coch.mod"
  pOt_INTEGER pOt_qoffs;
#line 24 "coch.mod"

#line 24 "coch.mod"
#endif
#line 24 "coch.mod"
{
#line 24 "coch.mod"
  pOt_INTEGER pOt_np;
#line 24 "coch.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 24 "coch.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 24 "coch.mod"

#line 24 "coch.mod"
  pOt_Unlink_COCQ((struct pOt__tag_3_COCT*)&(*pOt_x));
#line 24 "coch.mod"
  (*pOt_x).pOt_qoffs=(pOt_INTEGER)(pOt_qoffs);

#line 25 "coch.mod"
pOt__Epilogue:;
#line 25 "coch.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 25 "coch.mod"
}
#line 25 "coch.mod"

#line 25 "coch.mod"

#line 29 "coch.mod"

#line 29 "coch.mod"

#line 29 "coch.mod"
static void pOt_DynArrBnd_COCH
#line 29 "coch.mod"
#if pOt__ANSI_C
#line 29 "coch.mod"
  (pOt_Struct_COCT pOt_ftyp, pOt_Struct_COCT pOt_atyp, pOt_BOOLEAN pOt_varpar)
#line 29 "coch.mod"
#else
#line 29 "coch.mod"
  (pOt_ftyp, pOt_atyp, pOt_varpar)
#line 29 "coch.mod"
  pOt_Struct_COCT pOt_ftyp, pOt_atyp;
#line 29 "coch.mod"
  pOt_BOOLEAN pOt_varpar;
#line 29 "coch.mod"

#line 29 "coch.mod"
#endif
#line 29 "coch.mod"
{
#line 29 "coch.mod"
  pOt_INTEGER pOt_f;
#line 29 "coch.mod"
  struct {void *next, *vars[0x3];} pOt__gc_ptrs;
#line 29 "coch.mod"
  struct {void *next, *vars[0x1];} pOt__gc_strs;
#line 29 "coch.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 29 "coch.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 29 "coch.mod"
  pOt__gc_ptrs.vars[0x2]=pOt_NIL;
#line 29 "coch.mod"
  pOt__gc_strs.vars[0x0]=pOt_NIL;
#line 29 "coch.mod"
  pOt__gc_ptrs.vars[0x1]=&pOt_ftyp;
#line 29 "coch.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_atyp;
#line 29 "coch.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 29 "coch.mod"

#line 29 "coch.mod"
  if((pOt_varpar&&(((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_ftyp))).pOt_BaseTyp))).pOt_form==1)))) {
#line 31 "coch.mod"
    if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_atyp))).pOt_form!=16)) {
      if(((((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_atyp))).pOt_form!=15))||(((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_atyp))).pOt_BaseTyp))).pOt_form>4)))) {
#line 32 "coch.mod"
        pOt_Mark_COCS((pOt_INTEGER)(-1));
#line 32 "coch.mod"
      }
#line 32 "coch.mod"
    } else {
      pOt_atyp=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_atyp))).pOt_BaseTyp);
#line 33 "coch.mod"
      if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_atyp))).pOt_form!=16)) {
#line 35 "coch.mod"
        if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_atyp))).pOt_form>4)) {
#line 35 "coch.mod"
          pOt_Mark_COCS((pOt_INTEGER)(-1));
#line 35 "coch.mod"
        }
#line 35 "coch.mod"
      } else {
        pOt_Mark_COCS((pOt_INTEGER)(-1));
#line 36 "coch.mod"
        for(;;) {
          pOt_atyp=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_atyp))).pOt_BaseTyp);
#line 37 "coch.mod"
          if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_atyp))).pOt_form!=16)) break;
        }
#line 38 "coch.mod"
      }
#line 38 "coch.mod"
    }
  } else {
#line 41 "coch.mod"
    for(;;) {
#line 41 "coch.mod"
      pOt_f=(pOt_INTEGER)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_atyp))).pOt_form);
#line 41 "coch.mod"
      if((((pOt_f!=((pOt_INTEGER)(15))))&&((pOt_f!=((pOt_INTEGER)(16)))))) {
        pOt_Mark_COCS((pOt_INTEGER)(66));
#line 42 "coch.mod"
        goto pOt__LoopLabel_1;
#line 42 "coch.mod"
      }
#line 42 "coch.mod"
      pOt_ftyp=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_ftyp))).pOt_BaseTyp);
      pOt_atyp=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_atyp))).pOt_BaseTyp);
#line 43 "coch.mod"
      if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_ftyp))).pOt_form!=16)) {
#line 45 "coch.mod"
        if(( pOt_ftyp!=pOt_atyp)) {
#line 45 "coch.mod"
          pOt_Mark_COCS((pOt_INTEGER)(67));
#line 45 "coch.mod"
        }
#line 45 "coch.mod"
        goto pOt__LoopLabel_1;
#line 47 "coch.mod"
      }
#line 47 "coch.mod"
    }
  pOt__LoopLabel_1:;
#line 48 "coch.mod"
  }

pOt__Epilogue:;
#line 50 "coch.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 50 "coch.mod"
}
#line 50 "coch.mod"

#line 50 "coch.mod"

#line 54 "coch.mod"

#line 54 "coch.mod"

#line 54 "coch.mod"
extern void pOt_CompareParLists_COCH
#line 54 "coch.mod"
#if pOt__ANSI_C
#line 54 "coch.mod"
  (pOt_Object_COCT pOt_x, pOt_Object_COCT pOt_y)
#line 54 "coch.mod"
#else
#line 54 "coch.mod"
  (pOt_x, pOt_y)
#line 54 "coch.mod"
  pOt_Object_COCT pOt_x, pOt_y;
#line 54 "coch.mod"

#line 54 "coch.mod"
#endif
#line 54 "coch.mod"
{
#line 54 "coch.mod"
  pOt_Struct_COCT pOt_xt, pOt_yt;
#line 54 "coch.mod"
  struct {void *next, *vars[0x5];} pOt__gc_ptrs;
#line 54 "coch.mod"
  struct {void *next, *vars[0x1];} pOt__gc_strs;
#line 54 "coch.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 54 "coch.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 54 "coch.mod"
  pOt__gc_ptrs.vars[0x4]=pOt_NIL;
#line 54 "coch.mod"
  pOt__gc_strs.vars[0x0]=pOt_NIL;
#line 54 "coch.mod"
  pOt__gc_ptrs.vars[0x3]=&pOt_x;
#line 54 "coch.mod"
  pOt__gc_ptrs.vars[0x2]=&pOt_y;
#line 54 "coch.mod"
  pOt__gc_ptrs.vars[0x1]=&pOt_xt;
#line 54 "coch.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_yt;
#line 54 "coch.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 54 "coch.mod"
  pOt_xt=pOt_NIL;
#line 54 "coch.mod"
  pOt_yt=pOt_NIL;
#line 54 "coch.mod"

#line 54 "coch.mod"
  for(;;) {
    if(( pOt_x!=pOt_NIL)); else break;
#line 55 "coch.mod"
    if(( pOt_y!=pOt_NIL)) {
#line 57 "coch.mod"
      pOt_xt=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_x))).pOt_typ);
#line 57 "coch.mod"
      pOt_yt=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_y))).pOt_typ);
#line 57 "coch.mod"
      for(;;) {
        if(((((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_xt))).pOt_form==16))&&(((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_yt))).pOt_form==16)))); else break;
#line 58 "coch.mod"
        pOt_xt=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_xt))).pOt_BaseTyp);
        pOt_yt=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_yt))).pOt_BaseTyp);
      }
#line 60 "coch.mod"
      if(( (*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_x))).pOt_mode!=(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_y))).pOt_mode)) {
        pOt_Mark_COCS((pOt_INTEGER)(115));
      } else if(( pOt_xt!=pOt_yt)) {
        if(((((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_xt))).pOt_form==14))&&(((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_yt))).pOt_form==14)))) {
          pOt_CompareParLists_COCH((struct pOt__tag_1_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_xt))).pOt_link),(struct pOt__tag_1_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_yt))).pOt_link));
        } else {
#line 65 "coch.mod"
          pOt_Mark_COCS((pOt_INTEGER)(115));
        }
#line 66 "coch.mod"
      }
      pOt_y=(struct pOt__tag_1_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_y))).pOt_next);
#line 69 "coch.mod"
    } else {
#line 69 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(116));
    }
#line 70 "coch.mod"
    pOt_x=(struct pOt__tag_1_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_x))).pOt_next);
#line 72 "coch.mod"
  }
#line 72 "coch.mod"
  if(((((pOt_y!=pOt_NIL))&&(((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_y))).pOt_mode<=3)))&&(((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_y))).pOt_intval==((pOt_LONGINT)(1)))))) {
    pOt_Mark_COCS((pOt_INTEGER)(117));
#line 73 "coch.mod"
  }
#line 73 "coch.mod"

pOt__Epilogue:;
#line 74 "coch.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 74 "coch.mod"
}
#line 74 "coch.mod"

#line 74 "coch.mod"

#line 77 "coch.mod"

#line 77 "coch.mod"

#line 77 "coch.mod"
extern void pOt_AssignPrefix_COCH
#line 77 "coch.mod"
#if pOt__ANSI_C
#line 77 "coch.mod"
  (struct pOt__tag_3_COCT *pOt_x)
#line 77 "coch.mod"
#else
#line 77 "coch.mod"
  (pOt_x)
#line 77 "coch.mod"
  struct pOt__tag_3_COCT *pOt_x;
#line 77 "coch.mod"

#line 77 "coch.mod"
#endif
#line 77 "coch.mod"
{
#line 77 "coch.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 77 "coch.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 77 "coch.mod"

#line 77 "coch.mod"
  if(( (*pOt_x).pOt_mode>=8)) {
    pOt_Mark_COCS((pOt_INTEGER)(56));
  } else if(((((*pOt_x).pOt_mode==1))&&(((*pOt_x).pOt_mnolev<((pOt_INTEGER)(0)))))) {
#line 79 "coch.mod"
    pOt_Mark_COCS((pOt_INTEGER)(-3));
  }
#line 80 "coch.mod"
  pOt_AssignPfx_COCP((struct pOt__tag_3_COCT*)&(*pOt_x),pOt_typchk_COCT);
#line 82 "coch.mod"

#line 82 "coch.mod"
pOt__Epilogue:;
#line 82 "coch.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 82 "coch.mod"
}
#line 82 "coch.mod"

#line 82 "coch.mod"

#line 87 "coch.mod"

#line 87 "coch.mod"

#line 87 "coch.mod"
extern void pOt_Assign_COCH
#line 87 "coch.mod"
#if pOt__ANSI_C
#line 87 "coch.mod"
  (struct pOt__tag_3_COCT *pOt_x, struct pOt__tag_3_COCT *pOt_y)
#line 87 "coch.mod"
#else
#line 87 "coch.mod"
  (pOt_x, pOt_y)
#line 87 "coch.mod"
  struct pOt__tag_3_COCT *pOt_x, *pOt_y;
#line 87 "coch.mod"

#line 87 "coch.mod"
#endif
#line 87 "coch.mod"
{
#line 87 "coch.mod"
  pOt_INTEGER pOt_f, pOt_g, pOt_L;
#line 87 "coch.mod"
  pOt_Struct_COCT pOt_p, pOt_q;
#line 87 "coch.mod"
  struct {void *next, *vars[0x3];} pOt__gc_ptrs;
#line 87 "coch.mod"
  struct {void *next, *vars[0x1];} pOt__gc_strs;
#line 87 "coch.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 87 "coch.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 87 "coch.mod"
  pOt__gc_ptrs.vars[0x2]=pOt_NIL;
#line 87 "coch.mod"
  pOt__gc_strs.vars[0x0]=pOt_NIL;
#line 87 "coch.mod"
  pOt__gc_ptrs.vars[0x1]=&pOt_p;
#line 87 "coch.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_q;
#line 87 "coch.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 87 "coch.mod"
  pOt_p=pOt_NIL;
#line 87 "coch.mod"
  pOt_q=pOt_NIL;
#line 87 "coch.mod"

#line 87 "coch.mod"
  if(( (*pOt_y).pOt_mode==13)) {
#line 87 "coch.mod"
    pOt_Mark_COCS((pOt_INTEGER)(126));
#line 87 "coch.mod"
  }
#line 87 "coch.mod"
  pOt_f=(pOt_INTEGER)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_form);
  pOt_g=(pOt_INTEGER)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_y).pOt_typ))).pOt_form);
#line 88 "coch.mod"
  switch(pOt_f) {
#line 90 "coch.mod"
  case 0:
#line 90 "coch.mod"
  case 10:
#line 90 "coch.mod"
  break;
  case 1:
#line 91 "coch.mod"
    if(!(((unsigned long)0!=((unsigned long)1<<pOt__rngchk_se(__FILE__,__LINE__,pOt_g)&(pOt_SET)0x1BL)))) {
#line 91 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(113));
    }
#line 92 "coch.mod"
  break;
#line 92 "coch.mod"
  case 2:
#line 92 "coch.mod"
  case 3:
#line 92 "coch.mod"
  case 4:
#line 92 "coch.mod"
  case 9:
#line 92 "coch.mod"
    if(( pOt_g!=pOt_f)) {
#line 92 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(113));
#line 92 "coch.mod"
    }
#line 92 "coch.mod"
  break;
  case 5:
#line 93 "coch.mod"
    if(!(((unsigned long)0!=((unsigned long)1<<pOt__rngchk_se(__FILE__,__LINE__,pOt_g)&(pOt_SET)0x30L)))) {
#line 93 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(113));
    }
#line 94 "coch.mod"
  break;
#line 94 "coch.mod"
  case 6:
#line 94 "coch.mod"
    if(!(((unsigned long)0!=((unsigned long)1<<pOt__rngchk_se(__FILE__,__LINE__,pOt_g)&(pOt_SET)0x70L)))) {
#line 94 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(113));
    }
#line 95 "coch.mod"
  break;
#line 95 "coch.mod"
  case 7:
#line 95 "coch.mod"
    if(!(((unsigned long)0!=((unsigned long)1<<pOt__rngchk_se(__FILE__,__LINE__,pOt_g)&(pOt_SET)0xF0L)))) {
#line 95 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(113));
    }
#line 96 "coch.mod"
  break;
#line 96 "coch.mod"
  case 8:
#line 96 "coch.mod"
    if(!(((unsigned long)0!=((unsigned long)1<<pOt__rngchk_se(__FILE__,__LINE__,pOt_g)&(pOt_SET)0x1F0L)))) {
#line 96 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(113));
    }
#line 97 "coch.mod"
  break;
#line 97 "coch.mod"
  case 13:
#line 97 "coch.mod"
    if(((((*pOt_x).pOt_typ==(*pOt_y).pOt_typ))||((pOt_g==((pOt_INTEGER)(11)))))) {
#line 99 "coch.mod"
    } else if(( pOt_g==((pOt_INTEGER)(13)))) {
      pOt_p=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_BaseTyp);
#line 100 "coch.mod"
      pOt_q=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_y).pOt_typ))).pOt_BaseTyp);
#line 100 "coch.mod"
      if(((((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_p))).pOt_form==17))&&(((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_q))).pOt_form==17)))) {
#line 102 "coch.mod"
        for(;;) {
#line 102 "coch.mod"
          if((((pOt_q!=pOt_p))&&((pOt_q!=pOt_NIL)))); else break;
#line 102 "coch.mod"
          pOt_q=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_q))).pOt_BaseTyp);
#line 102 "coch.mod"
        }
#line 102 "coch.mod"
        if(( pOt_q==pOt_NIL)) {
          pOt_Mark_COCS((pOt_INTEGER)(113));
#line 103 "coch.mod"
        }
#line 103 "coch.mod"
      } else {
        pOt_Mark_COCS((pOt_INTEGER)(113));
      }
#line 105 "coch.mod"
    } else {
      pOt_Mark_COCS((pOt_INTEGER)(113));
    }
#line 107 "coch.mod"
  break;
  case 15:
#line 108 "coch.mod"
    if(( (*pOt_x).pOt_typ==(*pOt_y).pOt_typ)) {
#line 110 "coch.mod"
    } else if((((pOt_g==((pOt_INTEGER)(10))))&&(((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_BaseTyp==pOt_chartyp_COCT)))) {
      pOt_L=(pOt_INTEGER)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__rngchk_i(__FILE__,__LINE__,(pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)((*pOt_y).pOt_intval),(pOt_LONGINT)(256),6))),(pOt_LONGINT)(1),5));
      if((((pOt_LONGINT)( pOt_L))>(*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_n)) {
#line 112 "coch.mod"
        pOt_Mark_COCS((pOt_INTEGER)(114));
      } else if((((pOt_LONGINT)( (pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_L),(pOt_LONGINT)(2048),5)))<(*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_n)) {
#line 113 "coch.mod"
        pOt_Mark_COCS((pOt_INTEGER)(244));
#line 115 "coch.mod"
      }
#line 115 "coch.mod"
    } else {
#line 115 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(113));
    }
#line 116 "coch.mod"
  break;
  case 16:
#line 117 "coch.mod"
    if((((pOt_g==((pOt_INTEGER)(10))))&&(((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_BaseTyp))).pOt_form==3)))) {
#line 119 "coch.mod"
    } else if(( (*pOt_y).pOt_mode>3)) {
#line 119 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(59));
    } else {
#line 120 "coch.mod"
      pOt_DynArrBnd_COCH((struct pOt__tag_2_COCT*)((*pOt_x).pOt_typ),(struct pOt__tag_2_COCT*)((*pOt_y).pOt_typ),(pOt_BOOLEAN)0);
    }
#line 121 "coch.mod"
  break;
  case 17:
#line 122 "coch.mod"
    if(( (*pOt_x).pOt_typ!=(*pOt_y).pOt_typ)) {
#line 124 "coch.mod"
      if(( pOt_g==((pOt_INTEGER)(17)))) {
        pOt_q=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_y).pOt_typ))).pOt_BaseTyp);
#line 125 "coch.mod"
        for(;;) {
          if((((pOt_q!=pOt_NIL))&&((pOt_q!=(*pOt_x).pOt_typ)))); else break;
#line 126 "coch.mod"
          pOt_q=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_q))).pOt_BaseTyp);
#line 126 "coch.mod"
        }
#line 126 "coch.mod"
        if(( pOt_q==pOt_NIL)) {
          pOt_Mark_COCS((pOt_INTEGER)(113));
#line 127 "coch.mod"
        }
#line 127 "coch.mod"
      } else {
        pOt_Mark_COCS((pOt_INTEGER)(113));
      }
#line 129 "coch.mod"
    }
#line 131 "coch.mod"
  break;
#line 131 "coch.mod"
  case 14:
#line 131 "coch.mod"
    if(((((*pOt_x).pOt_typ==(*pOt_y).pOt_typ))||(((*pOt_y).pOt_typ==pOt_niltyp_COCT)))) {
#line 133 "coch.mod"
    } else if(((((*pOt_y).pOt_mode==15))||(((*pOt_y).pOt_mode==18)))) {
#line 135 "coch.mod"
      if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_BaseTyp==(*pOt_y).pOt_typ)) {
        pOt_CompareParLists_COCH((struct pOt__tag_1_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_link),(struct pOt__tag_1_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_y).pOt_obj))).pOt_dsc));
      } else {
#line 137 "coch.mod"
        pOt_Mark_COCS((pOt_INTEGER)(118));
      }
#line 138 "coch.mod"
    } else if(( (*pOt_y).pOt_mode==14)) {
      pOt_Mark_COCS((pOt_INTEGER)(119));
    } else {
#line 140 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(111));
    }
#line 141 "coch.mod"
  break;
  case 12:
#line 142 "coch.mod"
  case 11:
#line 142 "coch.mod"
    pOt_Mark_COCS((pOt_INTEGER)(111));
  break;
#line 143 "coch.mod"
  default:;
#line 143 "coch.mod"
    pOt__halt(__FILE__,__LINE__,0x10);
#line 143 "coch.mod"
  }
#line 143 "coch.mod"
  pOt_AssignSfx_COCP((struct pOt__tag_3_COCT*)&(*pOt_x),(struct pOt__tag_3_COCT*)&(*pOt_y));
#line 145 "coch.mod"

#line 145 "coch.mod"
pOt__Epilogue:;
#line 145 "coch.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 145 "coch.mod"
}
#line 145 "coch.mod"

#line 145 "coch.mod"

#line 149 "coch.mod"

#line 149 "coch.mod"

#line 149 "coch.mod"
extern pOt_INTEGER pOt_PrepCall_COCH
#line 149 "coch.mod"
#if pOt__ANSI_C
#line 149 "coch.mod"
  (struct pOt__tag_3_COCT *pOt_x, pOt_Object_COCT *pOt_fpar)
#line 149 "coch.mod"
#else
#line 149 "coch.mod"
  (pOt_x, pOt_fpar)
#line 149 "coch.mod"
  struct pOt__tag_3_COCT *pOt_x;
#line 149 "coch.mod"
  pOt_Object_COCT *pOt_fpar;
#line 149 "coch.mod"

#line 149 "coch.mod"
#endif
#line 149 "coch.mod"
{
#line 149 "coch.mod"
  pOt_INTEGER pOt__retval;
#line 149 "coch.mod"
  pOt_INTEGER pOt_qoffs;
#line 149 "coch.mod"
  int pOt__gc_enabled_prev;
#line 149 "coch.mod"
  pOt__gc_enabled_prev=pOt__gc_enabled;
#line 149 "coch.mod"
  pOt__gc_enabled=0;
#line 149 "coch.mod"

#line 149 "coch.mod"
  pOt_qoffs=(pOt_INTEGER)((*pOt_x).pOt_qoffs);
#line 149 "coch.mod"
  pOt_Link_COCQ((struct pOt__tag_3_COCT*)&(*pOt_x));
#line 149 "coch.mod"
  pOt_ParamListPfx_COCP();
  if((((((*pOt_x).pOt_mode==14))||(((*pOt_x).pOt_mode==15)))||(((*pOt_x).pOt_mode==17)))) {
    (*pOt_fpar)=(struct pOt__tag_1_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_obj))).pOt_dsc);
  } else if(((((*pOt_x).pOt_typ!=pOt_NIL))&&(((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_form==14)))) {
    (*pOt_fpar)=(struct pOt__tag_1_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_link);
  } else {
#line 154 "coch.mod"
    pOt_Mark_COCS((pOt_INTEGER)(121));
#line 154 "coch.mod"
    (*pOt_fpar)=(struct pOt__tag_1_COCT*)(pOt_NIL);
#line 154 "coch.mod"
    (*pOt_x).pOt_typ=(struct pOt__tag_2_COCT*)(pOt_undftyp_COCT);
  }
#line 155 "coch.mod"
  pOt__retval =(pOt_INTEGER)(pOt_qoffs);
#line 157 "coch.mod"
  goto pOt__Epilogue;
#line 157 "coch.mod"

#line 157 "coch.mod"
  pOt__halt(__FILE__,__LINE__,0x11);
#line 157 "coch.mod"
pOt__Epilogue:;
#line 157 "coch.mod"
  pOt__gc_enabled=pOt__gc_enabled_prev;
#line 157 "coch.mod"
  return pOt__retval;
#line 157 "coch.mod"
}
#line 157 "coch.mod"

#line 157 "coch.mod"

#line 160 "coch.mod"

#line 160 "coch.mod"

#line 160 "coch.mod"
extern void pOt_ParamPrefix_COCH
#line 160 "coch.mod"
#if pOt__ANSI_C
#line 160 "coch.mod"
  (pOt_Object_COCT pOt_f)
#line 160 "coch.mod"
#else
#line 160 "coch.mod"
  (pOt_f)
#line 160 "coch.mod"
  pOt_Object_COCT pOt_f;
#line 160 "coch.mod"

#line 160 "coch.mod"
#endif
#line 160 "coch.mod"
{
#line 160 "coch.mod"
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
#line 160 "coch.mod"
  struct {void *next, *vars[0x1];} pOt__gc_strs;
#line 160 "coch.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 160 "coch.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 160 "coch.mod"
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
#line 160 "coch.mod"
  pOt__gc_strs.vars[0x0]=pOt_NIL;
#line 160 "coch.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_f;
#line 160 "coch.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 160 "coch.mod"

#line 160 "coch.mod"
  pOt_ParamPfx_COCP((struct pOt__tag_1_COCT*)(pOt_f));

#line 161 "coch.mod"
pOt__Epilogue:;
#line 161 "coch.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 161 "coch.mod"
}
#line 161 "coch.mod"

#line 161 "coch.mod"

#line 167 "coch.mod"

#line 167 "coch.mod"
static struct pOt__tag_3_COCT *pOt_ap_Param_COCH;
#line 167 "coch.mod"
static pOt_Object_COCT (*pOt_f_Param_COCH);
#line 167 "coch.mod"
static pOt_Struct_COCT (*pOt_q_Param_COCH);
#line 167 "coch.mod"
static struct pOt__tag_3_COCT (*pOt_fp_Param_COCH);
#line 167 "coch.mod"

#line 167 "coch.mod"
extern void pOt_Param_COCH pOt__ARGS((struct pOt__tag_3_COCT *, pOt_Object_COCT ));
#line 167 "coch.mod"

#line 167 "coch.mod"

#line 169 "coch.mod"

#line 169 "coch.mod"

#line 169 "coch.mod"
static void pOt_ValParam_Param_COCH
#line 169 "coch.mod"
#if pOt__ANSI_C
#line 169 "coch.mod"
  (struct pOt__tag_3_COCT *pOt_x, struct pOt__tag_3_COCT *pOt_y)
#line 169 "coch.mod"
#else
#line 169 "coch.mod"
  (pOt_x, pOt_y)
#line 169 "coch.mod"
  struct pOt__tag_3_COCT *pOt_x, *pOt_y;
#line 169 "coch.mod"

#line 169 "coch.mod"
#endif
#line 169 "coch.mod"
{
#line 169 "coch.mod"
  pOt_INTEGER pOt_f, pOt_g, pOt_L;
#line 169 "coch.mod"
  pOt_Struct_COCT pOt_p;
#line 169 "coch.mod"
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
#line 169 "coch.mod"
  struct {void *next, *vars[0x1];} pOt__gc_strs;
#line 169 "coch.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 169 "coch.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 169 "coch.mod"
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
#line 169 "coch.mod"
  pOt__gc_strs.vars[0x0]=pOt_NIL;
#line 169 "coch.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_p;
#line 169 "coch.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 169 "coch.mod"
  pOt_p=pOt_NIL;
#line 169 "coch.mod"

#line 169 "coch.mod"
  if(( (*pOt_y).pOt_mode==13)) {
    pOt_Mark_COCS((pOt_INTEGER)(126));
#line 170 "coch.mod"
  }
#line 170 "coch.mod"
  pOt_f=(pOt_INTEGER)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_form);
  pOt_g=(pOt_INTEGER)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_y).pOt_typ))).pOt_form);
#line 171 "coch.mod"
  switch(pOt_f) {
#line 173 "coch.mod"
  case 0:
#line 173 "coch.mod"
  case 10:
#line 173 "coch.mod"
  break;
  case 1:
#line 174 "coch.mod"
    if(!(((unsigned long)0!=((unsigned long)1<<pOt__rngchk_se(__FILE__,__LINE__,pOt_g)&(pOt_SET)0x1BL)))) {
#line 174 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(113));
    }
#line 175 "coch.mod"
  break;
#line 175 "coch.mod"
  case 2:
#line 175 "coch.mod"
  case 3:
#line 175 "coch.mod"
  case 4:
#line 175 "coch.mod"
  case 9:
#line 175 "coch.mod"
    if(( pOt_g!=pOt_f)) {
#line 175 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(113));
#line 175 "coch.mod"
    }
#line 175 "coch.mod"
  break;
  case 5:
#line 176 "coch.mod"
    if(!(((unsigned long)0!=((unsigned long)1<<pOt__rngchk_se(__FILE__,__LINE__,pOt_g)&(pOt_SET)0x30L)))) {
#line 176 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(113));
    }
#line 177 "coch.mod"
  break;
#line 177 "coch.mod"
  case 6:
#line 177 "coch.mod"
    if(!(((unsigned long)0!=((unsigned long)1<<pOt__rngchk_se(__FILE__,__LINE__,pOt_g)&(pOt_SET)0x70L)))) {
#line 177 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(113));
    }
#line 178 "coch.mod"
  break;
#line 178 "coch.mod"
  case 7:
#line 178 "coch.mod"
    if(!(((unsigned long)0!=((unsigned long)1<<pOt__rngchk_se(__FILE__,__LINE__,pOt_g)&(pOt_SET)0xF0L)))) {
#line 178 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(113));
    }
#line 179 "coch.mod"
  break;
#line 179 "coch.mod"
  case 8:
#line 179 "coch.mod"
    if(!(((unsigned long)0!=((unsigned long)1<<pOt__rngchk_se(__FILE__,__LINE__,pOt_g)&(pOt_SET)0x1F0L)))) {
#line 179 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(113));
    }
#line 180 "coch.mod"
  break;
#line 180 "coch.mod"
  case 13:
#line 180 "coch.mod"
    if(((((*pOt_x).pOt_typ==(*pOt_y).pOt_typ))||((pOt_g==((pOt_INTEGER)(11)))))) {
#line 182 "coch.mod"
    } else if(( pOt_g==((pOt_INTEGER)(13)))) {
      pOt_p=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_BaseTyp);
#line 183 "coch.mod"
      (*pOt_q_Param_COCH)=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_y).pOt_typ))).pOt_BaseTyp);
#line 183 "coch.mod"
      if(((((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_p))).pOt_form==17))&&(((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_q_Param_COCH)))).pOt_form==17)))) {
#line 185 "coch.mod"
        for(;;) {
#line 185 "coch.mod"
          if(((((*pOt_q_Param_COCH)!=pOt_p))&&(((*pOt_q_Param_COCH)!=pOt_NIL)))); else break;
#line 185 "coch.mod"
          (*pOt_q_Param_COCH)=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_q_Param_COCH)))).pOt_BaseTyp);
#line 185 "coch.mod"
        }
#line 185 "coch.mod"
        if(( (*pOt_q_Param_COCH)==pOt_NIL)) {
          pOt_Mark_COCS((pOt_INTEGER)(113));
#line 186 "coch.mod"
        }
#line 186 "coch.mod"
      } else {
        pOt_Mark_COCS((pOt_INTEGER)(113));
      }
#line 188 "coch.mod"
    } else {
      pOt_Mark_COCS((pOt_INTEGER)(113));
    }
#line 190 "coch.mod"
  break;
  case 15:
#line 191 "coch.mod"
    if(( (*pOt_x).pOt_typ==(*pOt_y).pOt_typ)) {
#line 193 "coch.mod"
    } else if((((pOt_g==((pOt_INTEGER)(10))))&&(((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_BaseTyp==pOt_chartyp_COCT)))) {
      pOt_L=(pOt_INTEGER)((pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)((pOt_LONGINT)pOt__rngchk_i(__FILE__,__LINE__,(pOt_LONGINT)pOt__modchk(__FILE__,__LINE__,(pOt_LONGINT)((*pOt_y).pOt_intval),(pOt_LONGINT)(256),6))),(pOt_LONGINT)(1),5));
      if((((pOt_LONGINT)( pOt_L))>(*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_n)) {
#line 195 "coch.mod"
        pOt_Mark_COCS((pOt_INTEGER)(114));
      } else if((((pOt_LONGINT)( (pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_L),(pOt_LONGINT)(2048),5)))<(*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_n)) {
#line 196 "coch.mod"
        pOt_Mark_COCS((pOt_INTEGER)(244));
#line 198 "coch.mod"
      }
#line 198 "coch.mod"
    } else {
#line 198 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(113));
    }
#line 199 "coch.mod"
  break;
  case 16:
#line 200 "coch.mod"
    if((((pOt_g==((pOt_INTEGER)(10))))&&(((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_BaseTyp))).pOt_form==3)))) {
#line 202 "coch.mod"
    } else if(( (*pOt_y).pOt_mode>3)) {
#line 202 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(59));
    } else {
#line 203 "coch.mod"
      pOt_DynArrBnd_COCH((struct pOt__tag_2_COCT*)((*pOt_x).pOt_typ),(struct pOt__tag_2_COCT*)((*pOt_y).pOt_typ),(pOt_BOOLEAN)0);
    }
#line 204 "coch.mod"
  break;
  case 17:
#line 205 "coch.mod"
    if(( (*pOt_x).pOt_typ!=(*pOt_y).pOt_typ)) {
#line 207 "coch.mod"
      if(( pOt_g==((pOt_INTEGER)(17)))) {
        (*pOt_q_Param_COCH)=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_y).pOt_typ))).pOt_BaseTyp);
#line 208 "coch.mod"
        for(;;) {
          if(((((*pOt_q_Param_COCH)!=pOt_NIL))&&(((*pOt_q_Param_COCH)!=(*pOt_x).pOt_typ)))); else break;
#line 209 "coch.mod"
          (*pOt_q_Param_COCH)=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_q_Param_COCH)))).pOt_BaseTyp);
#line 209 "coch.mod"
        }
#line 209 "coch.mod"
        if(( (*pOt_q_Param_COCH)==pOt_NIL)) {
          pOt_Mark_COCS((pOt_INTEGER)(113));
#line 210 "coch.mod"
        }
#line 210 "coch.mod"
      } else {
        pOt_Mark_COCS((pOt_INTEGER)(113));
      }
#line 212 "coch.mod"
    }
#line 214 "coch.mod"
  break;
#line 214 "coch.mod"
  case 14:
#line 214 "coch.mod"
    if(((((*pOt_x).pOt_typ==(*pOt_y).pOt_typ))||(((*pOt_y).pOt_typ==pOt_niltyp_COCT)))) {
#line 216 "coch.mod"
    } else if(((((*pOt_y).pOt_mode==15))||(((*pOt_y).pOt_mode==18)))) {
#line 218 "coch.mod"
      if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_BaseTyp==(*pOt_y).pOt_typ)) {
        pOt_CompareParLists_COCH((struct pOt__tag_1_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_link),(struct pOt__tag_1_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_y).pOt_obj))).pOt_dsc));
      } else {
#line 220 "coch.mod"
        pOt_Mark_COCS((pOt_INTEGER)(118));
      }
#line 221 "coch.mod"
    } else if(( (*pOt_y).pOt_mode==14)) {
      pOt_Mark_COCS((pOt_INTEGER)(119));
    } else {
#line 223 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(111));
    }
#line 224 "coch.mod"
  break;
  case 12:
#line 225 "coch.mod"
  case 11:
#line 225 "coch.mod"
    pOt_Mark_COCS((pOt_INTEGER)(111));
  break;
#line 226 "coch.mod"
  default:;
#line 226 "coch.mod"
    pOt__halt(__FILE__,__LINE__,0x10);
#line 226 "coch.mod"
  }
#line 226 "coch.mod"

pOt__Epilogue:;
#line 227 "coch.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 227 "coch.mod"
}
#line 227 "coch.mod"

#line 227 "coch.mod"
extern void pOt_Param_COCH
#line 229 "coch.mod"
#if pOt__ANSI_C
#line 229 "coch.mod"
  (struct pOt__tag_3_COCT *pOt_ap, pOt_Object_COCT pOt_f)
#line 229 "coch.mod"
#else
#line 229 "coch.mod"
  (pOt_ap, pOt_f)
#line 229 "coch.mod"
  struct pOt__tag_3_COCT *pOt_ap;
#line 229 "coch.mod"
  pOt_Object_COCT pOt_f;
#line 229 "coch.mod"

#line 229 "coch.mod"
#endif
#line 229 "coch.mod"
{
#line 229 "coch.mod"
  struct pOt__tag_3_COCT *pOt_ap_;
#line 229 "coch.mod"
  pOt_Object_COCT (*pOt_f_);
#line 229 "coch.mod"
  pOt_Struct_COCT pOt_q, (*pOt_q_);
#line 229 "coch.mod"
  struct pOt__tag_3_COCT pOt_fp, (*pOt_fp_);
#line 229 "coch.mod"
  struct {void *next, *vars[0x3];} pOt__gc_ptrs;
#line 229 "coch.mod"
  struct {void *next, *vars[0x2];} pOt__gc_strs;
#line 229 "coch.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 229 "coch.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 229 "coch.mod"
  pOt__gc_ptrs.vars[0x2]=pOt_NIL;
#line 229 "coch.mod"
  pOt__gc_strs.vars[0x1]=pOt_NIL;
#line 229 "coch.mod"
  pOt__gc_ptrs.vars[0x1]=&pOt_f;
#line 229 "coch.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_q;
#line 229 "coch.mod"
  pOt__gc_strs.vars[0x0]=&pOt_fp;
#line 229 "coch.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 229 "coch.mod"
  pOt_ap_=pOt_ap_Param_COCH;
#line 229 "coch.mod"
  pOt_ap_Param_COCH=pOt_ap;
#line 229 "coch.mod"
  pOt_f_=pOt_f_Param_COCH;
#line 229 "coch.mod"
  pOt_f_Param_COCH=&pOt_f;
#line 229 "coch.mod"
  pOt_q_=pOt_q_Param_COCH;
#line 229 "coch.mod"
  pOt_q_Param_COCH=&pOt_q;
#line 229 "coch.mod"
  pOt_q=pOt_NIL;
#line 229 "coch.mod"
  pOt_fp_=pOt_fp_Param_COCH;
#line 229 "coch.mod"
  pOt_fp_Param_COCH=&pOt_fp;
#line 229 "coch.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_fp,(pOt__TypDsc*)&pOt__td_3_COCT);
#line 229 "coch.mod"

#line 229 "coch.mod"
  pOt_fp.pOt_mode=9;
#line 229 "coch.mod"
  pOt_fp.pOt_typ=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_f))).pOt_typ);
#line 229 "coch.mod"
  if(( (*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_f))).pOt_mode==3)) {
#line 231 "coch.mod"
    if(( (*pOt_ap).pOt_mode>=8)) {
#line 231 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(122));
#line 231 "coch.mod"
    }
#line 231 "coch.mod"
    if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_fp.pOt_typ))).pOt_form==16)) {
#line 233 "coch.mod"
      pOt_DynArrBnd_COCH((struct pOt__tag_2_COCT*)(pOt_fp.pOt_typ),(struct pOt__tag_2_COCT*)((*pOt_ap).pOt_typ),(pOt_BOOLEAN)1);
    } else if(((((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_f))).pOt_typ))).pOt_form==17))&&(((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_ap).pOt_typ))).pOt_form==17)))) {
      pOt_q=(struct pOt__tag_2_COCT*)((*pOt_ap).pOt_typ);
#line 235 "coch.mod"
      for(;;) {
        if((((pOt_q!=(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_f))).pOt_typ))&&((pOt_q!=pOt_NIL)))); else break;
#line 236 "coch.mod"
        pOt_q=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_q))).pOt_BaseTyp);
#line 236 "coch.mod"
      }
#line 236 "coch.mod"
      if(( pOt_q==pOt_NIL)) {
        pOt_Mark_COCS((pOt_INTEGER)(111));
#line 237 "coch.mod"
      }
#line 237 "coch.mod"
    } else if(((((*pOt_ap).pOt_typ==(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_f))).pOt_typ))||(((((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_f))).pOt_typ))).pOt_form==1))&&(((unsigned long)0!=((unsigned long)1<<pOt__rngchk_se(__FILE__,__LINE__,(*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_ap).pOt_typ))).pOt_form)&(pOt_SET)0x18L))))))) {
#line 239 "coch.mod"
    } else {
#line 239 "coch.mod"
      pOt_Mark_COCS((pOt_INTEGER)(123));
    }
#line 240 "coch.mod"
  } else {
    pOt_ValParam_Param_COCH((struct pOt__tag_3_COCT*)&pOt_fp,(struct pOt__tag_3_COCT*)&(*pOt_ap));
  }
#line 242 "coch.mod"
  pOt_ParamSfx_COCP((struct pOt__tag_3_COCT*)&(*pOt_ap),(struct pOt__tag_1_COCT*)(pOt_f));
#line 244 "coch.mod"

#line 244 "coch.mod"
pOt__Epilogue:;
#line 244 "coch.mod"
  pOt_ap_Param_COCH=pOt_ap_;
#line 244 "coch.mod"
  pOt_f_Param_COCH=pOt_f_;
#line 244 "coch.mod"
  pOt_q_Param_COCH=pOt_q_;
#line 244 "coch.mod"
  pOt_fp_Param_COCH=pOt_fp_;
#line 244 "coch.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 244 "coch.mod"
}
#line 244 "coch.mod"

#line 244 "coch.mod"

#line 247 "coch.mod"

#line 247 "coch.mod"

#line 247 "coch.mod"
extern void pOt_NextParam_COCH()
#line 247 "coch.mod"
{
#line 247 "coch.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 247 "coch.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 247 "coch.mod"

#line 247 "coch.mod"
  pOt_NextParam_COCP();

#line 248 "coch.mod"
pOt__Epilogue:;
#line 248 "coch.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 248 "coch.mod"
}
#line 248 "coch.mod"

#line 248 "coch.mod"

#line 251 "coch.mod"

#line 251 "coch.mod"

#line 251 "coch.mod"
extern void pOt_Call_COCH
#line 251 "coch.mod"
#if pOt__ANSI_C
#line 251 "coch.mod"
  (struct pOt__tag_3_COCT *pOt_x, pOt_INTEGER pOt_qoffs)
#line 251 "coch.mod"
#else
#line 251 "coch.mod"
  (pOt_x, pOt_qoffs)
#line 251 "coch.mod"
  struct pOt__tag_3_COCT *pOt_x;
#line 251 "coch.mod"
  pOt_INTEGER pOt_qoffs;
#line 251 "coch.mod"

#line 251 "coch.mod"
#endif
#line 251 "coch.mod"
{
#line 251 "coch.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 251 "coch.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 251 "coch.mod"

#line 251 "coch.mod"
  pOt_ParamListSfx_COCP();
#line 251 "coch.mod"
  pOt_Unlink_COCQ((struct pOt__tag_3_COCT*)&(*pOt_x));
#line 251 "coch.mod"
  (*pOt_x).pOt_qoffs=(pOt_INTEGER)(pOt_qoffs);
  if(((((*pOt_x).pOt_mode<8))&&(((*pOt_x).pOt_typ!=pOt_undftyp_COCT)))) {
#line 252 "coch.mod"
    (*pOt_x).pOt_typ=(struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_BaseTyp);
  } else if(!(((unsigned long)0!=((unsigned long)1<<pOt__rngchk_se(__FILE__,__LINE__,(*pOt_x).pOt_mode)&(pOt_SET)0x7C000L)))) {
#line 253 "coch.mod"
    pOt_Mark_COCS((pOt_INTEGER)(121));
  }
#line 254 "coch.mod"
  if(( (*pOt_x).pOt_typ!=pOt_notyp_COCT)) {
    (*pOt_x).pOt_mode=11;
  }
#line 256 "coch.mod"

#line 256 "coch.mod"
pOt__Epilogue:;
#line 256 "coch.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 256 "coch.mod"
}
#line 256 "coch.mod"

#line 256 "coch.mod"

#line 260 "coch.mod"

#line 260 "coch.mod"

#line 260 "coch.mod"
extern void pOt_Trap_COCH
#line 260 "coch.mod"
#if pOt__ANSI_C
#line 260 "coch.mod"
  (pOt_SHORTINT pOt_num)
#line 260 "coch.mod"
#else
#line 260 "coch.mod"
  (pOt_num)
#line 260 "coch.mod"
  pOt_SHORTINT pOt_num;
#line 260 "coch.mod"

#line 260 "coch.mod"
#endif
#line 260 "coch.mod"
{
#line 260 "coch.mod"
  struct pOt__tag_3_COCT pOt_x;
#line 260 "coch.mod"
  pOt_INTEGER pOt_qoffs;
#line 260 "coch.mod"
  struct {void *next, *vars[0x1];} pOt__gc_ptrs;
#line 260 "coch.mod"
  struct {void *next, *vars[0x2];} pOt__gc_strs;
#line 260 "coch.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 260 "coch.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 260 "coch.mod"
  pOt__gc_ptrs.vars[0x0]=pOt_NIL;
#line 260 "coch.mod"
  pOt__gc_strs.vars[0x1]=pOt_NIL;
#line 260 "coch.mod"
  pOt__gc_strs.vars[0x0]=&pOt_x;
#line 260 "coch.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 260 "coch.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_x,(pOt__TypDsc*)&pOt__td_3_COCT);
#line 260 "coch.mod"

#line 260 "coch.mod"
  if(( pOt_num>=32)) {
#line 260 "coch.mod"
    pOt__halt(__FILE__,__LINE__,32);
#line 260 "coch.mod"
  }
#line 260 "coch.mod"
  pOt_x.pOt_intval=(pOt_LONGINT)(pOt_num);
#line 262 "coch.mod"
  pOt_qoffs=(pOt_INTEGER)(pOt_StartLinStmt_COCH((struct pOt__tag_3_COCT*)&pOt_x));
#line 262 "coch.mod"
  pOt_Trap_COCP((struct pOt__tag_3_COCT*)&pOt_x);
#line 262 "coch.mod"
  pOt_StopLinStmt_COCH((struct pOt__tag_3_COCT*)&pOt_x,(pOt_INTEGER)(pOt_qoffs));

#line 263 "coch.mod"
pOt__Epilogue:;
#line 263 "coch.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 263 "coch.mod"
}
#line 263 "coch.mod"

#line 263 "coch.mod"
void pOt_COCH__body()
#line 265 "coch.mod"
{
#line 265 "coch.mod"
  static int pOt_COCH__loaded=0;
#line 265 "coch.mod"
  if(!pOt_COCH__loaded){
#line 265 "coch.mod"
    pOt_COCH__loaded=1;
#line 265 "coch.mod"

#line 265 "coch.mod"
    pOt_COCS__body();
#line 265 "coch.mod"
    pOt_COCT__body();
#line 265 "coch.mod"
    pOt_COCD__body();
#line 265 "coch.mod"
    pOt_COCQ__body();
#line 265 "coch.mod"
    pOt_COCP__body();
#line 265 "coch.mod"

#line 265 "coch.mod"
    pOt__gc_ptrs.next=pOt__gc_root;
#line 265 "coch.mod"
    pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 265 "coch.mod"

#line 265 "coch.mod"

#line 265 "coch.mod"

#line 265 "coch.mod"
  pOt__Epilogue:;
#line 265 "coch.mod"
  }
#line 265 "coch.mod"
}
#line 265 "coch.mod"
