/* This code is generated by pOt. */
#line 16 "cocn.mod"

#line 16 "cocn.mod"
#include <pOtRTL.h>
#line 16 "cocn.mod"
#include "Strings.h"
#line 16 "cocn.mod"
#include "Reals.h"
#line 16 "cocn.mod"
#include "COCT.h"
#line 16 "cocn.mod"
#include "COCQ.h"
#line 16 "cocn.mod"

#line 16 "cocn.mod"
#include "COCN.hi"
#line 16 "cocn.mod"

#line 16 "cocn.mod"

#line 16 "cocn.mod"

#line 16 "cocn.mod"

#line 16 "cocn.mod"
static struct {void *next, *vars[0x1];} pOt__gc_ptrs = {pOt_NIL,{
#line 16 "cocn.mod"
  pOt_NIL
#line 16 "cocn.mod"
}};
#line 16 "cocn.mod"
static struct {void *next, *vars[0x1];} pOt__gc_strs = {&pOt__gc_ptrs,{
#line 16 "cocn.mod"
  pOt_NIL
#line 16 "cocn.mod"
}};
#line 16 "cocn.mod"

#line 16 "cocn.mod"

#line 19 "cocn.mod"

#line 19 "cocn.mod"

#line 19 "cocn.mod"
extern void pOt_CObjBaseName_COCN
#line 19 "cocn.mod"
#if pOt__ANSI_C
#line 19 "cocn.mod"
  (struct pOt__tag_3_COCT *pOt_x, pOt_INTEGER pOt_pos, pOt_INTEGER *pOt_nextpos)
#line 19 "cocn.mod"
#else
#line 19 "cocn.mod"
  (pOt_x, pOt_pos, pOt_nextpos)
#line 19 "cocn.mod"
  struct pOt__tag_3_COCT *pOt_x;
#line 19 "cocn.mod"
  pOt_INTEGER pOt_pos, *pOt_nextpos;
#line 19 "cocn.mod"

#line 19 "cocn.mod"
#endif
#line 19 "cocn.mod"
{
#line 19 "cocn.mod"
  pOt_Object_COCT pOt_head;
#line 19 "cocn.mod"
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
#line 19 "cocn.mod"
  struct {void *next, *vars[0x1];} pOt__gc_strs;
#line 19 "cocn.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 19 "cocn.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 19 "cocn.mod"
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
#line 19 "cocn.mod"
  pOt__gc_strs.vars[0x0]=pOt_NIL;
#line 19 "cocn.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_head;
#line 19 "cocn.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 19 "cocn.mod"
  pOt_head=pOt_NIL;
#line 19 "cocn.mod"

#line 19 "cocn.mod"
  (*pOt_nextpos)=(pOt_INTEGER)(pOt_pos);
  if(( (*pOt_x).pOt_obj==pOt_NIL)) {
#line 20 "cocn.mod"
    goto pOt__Epilogue;
#line 20 "cocn.mod"
  }
#line 20 "cocn.mod"
  if(( (*pOt_x).pOt_mode==17)) {
#line 22 "cocn.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_obj))).pOt_name),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 24 "cocn.mod"
  } else {
#line 24 "cocn.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x4]))),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_obj))).pOt_name),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
    if(( (*pOt_x).pOt_mode!=12)) {
      if(( (*pOt_x).pOt_mnolev<((pOt_INTEGER)(0)))) {
        pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xCL],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 28 "cocn.mod"
        pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_GlbMod_COCT.arr[pOt__inxchk(__FILE__,__LINE__,0x40, (pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)(-(*pOt_x).pOt_mnolev),(pOt_LONGINT)(1),5))]))).pOt_name),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 30 "cocn.mod"
      } else if(( (*pOt_x).pOt_mnolev==((pOt_INTEGER)(0)))) {
        switch((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_obj))).pOt_mnolev) {
#line 31 "cocn.mod"
        case 0:
          pOt_head=(struct pOt__tag_1_COCT*)(pOt_topScope_COCT);
          for(;;) {
#line 33 "cocn.mod"
            if(( (*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_head))).pOt_mnolev!=((pOt_INTEGER)(0)))); else break;
#line 33 "cocn.mod"
            pOt_head=(struct pOt__tag_1_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_head))).pOt_dsc);
#line 33 "cocn.mod"
          }
#line 33 "cocn.mod"
          pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xCL],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 35 "cocn.mod"
          pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_head))).pOt_name),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
        break;
#line 36 "cocn.mod"
        case 1:
        break;
#line 37 "cocn.mod"
        case 2:
#line 37 "cocn.mod"
          pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x14L],&pOt__str_td[0x7]))),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 39 "cocn.mod"
        break;
#line 39 "cocn.mod"
        default:;
#line 39 "cocn.mod"
          pOt__halt(__FILE__,__LINE__,0x10);
#line 39 "cocn.mod"
        }
#line 39 "cocn.mod"
      } else {
        if(((((*pOt_x).pOt_mode>=8))||(((*pOt_x).pOt_mnolev<pOt_level_COCT)))) {
          pOt_head=(struct pOt__tag_1_COCT*)(pOt_topScope_COCT);
          for(;;) {
#line 42 "cocn.mod"
            if(( (*pOt_x).pOt_mnolev!=(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_head))).pOt_mnolev)); else break;
#line 42 "cocn.mod"
            pOt_head=(struct pOt__tag_1_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_head))).pOt_dsc);
#line 42 "cocn.mod"
          }
#line 42 "cocn.mod"
          for(;;) {
#line 44 "cocn.mod"
            pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xCL],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 44 "cocn.mod"
            pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_head))).pOt_name),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
            if(( (*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_head))).pOt_mnolev==((pOt_INTEGER)(0)))) {
              goto pOt__LoopLabel_1;
#line 46 "cocn.mod"
            }
#line 46 "cocn.mod"
            pOt_head=(struct pOt__tag_1_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_head))).pOt_dsc);
#line 49 "cocn.mod"
          }
#line 49 "cocn.mod"
        pOt__LoopLabel_1:;
#line 49 "cocn.mod"
        } else if(( (*pOt_x).pOt_mnolev>pOt_level_COCT)) {
          pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xCL],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 52 "cocn.mod"
        }
#line 52 "cocn.mod"
      }
    }
  }

#line 55 "cocn.mod"
pOt__Epilogue:;
#line 55 "cocn.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 55 "cocn.mod"
}
#line 55 "cocn.mod"

#line 55 "cocn.mod"

#line 59 "cocn.mod"

#line 59 "cocn.mod"

#line 59 "cocn.mod"
extern void pOt_CObjName_COCN
#line 59 "cocn.mod"
#if pOt__ANSI_C
#line 59 "cocn.mod"
  (struct pOt__tag_3_COCT *pOt_x, pOt_INTEGER pOt_pos, pOt_INTEGER *pOt_nextpos)
#line 59 "cocn.mod"
#else
#line 59 "cocn.mod"
  (pOt_x, pOt_pos, pOt_nextpos)
#line 59 "cocn.mod"
  struct pOt__tag_3_COCT *pOt_x;
#line 59 "cocn.mod"
  pOt_INTEGER pOt_pos, *pOt_nextpos;
#line 59 "cocn.mod"

#line 59 "cocn.mod"
#endif
#line 59 "cocn.mod"
{
#line 59 "cocn.mod"
  pOt_BOOLEAN pOt_viaref;
#line 59 "cocn.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 59 "cocn.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 59 "cocn.mod"

#line 59 "cocn.mod"
  (*pOt_nextpos)=(pOt_INTEGER)(pOt_pos);
  pOt_viaref=(((((*pOt_x).pOt_mode==1))&&(((*pOt_x).pOt_mnolev>((pOt_INTEGER)(0)))))&&(((*pOt_x).pOt_mnolev!=pOt_level_COCT)));
  if(pOt_viaref) {
#line 61 "cocn.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x20L],&pOt__str_td[0x2]))),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 61 "cocn.mod"
  }
#line 61 "cocn.mod"
  pOt_CObjBaseName_COCN((struct pOt__tag_3_COCT*)&(*pOt_x),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 63 "cocn.mod"
  if(pOt_viaref) {
#line 63 "cocn.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x28L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
  }
#line 64 "cocn.mod"

#line 64 "cocn.mod"
pOt__Epilogue:;
#line 64 "cocn.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 64 "cocn.mod"
}
#line 64 "cocn.mod"

#line 64 "cocn.mod"

#line 67 "cocn.mod"

#line 67 "cocn.mod"

#line 67 "cocn.mod"
extern void pOt_CRetName_COCN
#line 67 "cocn.mod"
#if pOt__ANSI_C
#line 67 "cocn.mod"
  (pOt_INTEGER pOt_pos, pOt_INTEGER *pOt_nextpos)
#line 67 "cocn.mod"
#else
#line 67 "cocn.mod"
  (pOt_pos, pOt_nextpos)
#line 67 "cocn.mod"
  pOt_INTEGER pOt_pos, *pOt_nextpos;
#line 67 "cocn.mod"

#line 67 "cocn.mod"
#endif
#line 67 "cocn.mod"
{
#line 67 "cocn.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 67 "cocn.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 67 "cocn.mod"

#line 67 "cocn.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x30L],&pOt__str_td[0xB]))),(pOt_INTEGER)(pOt_pos),&(*pOt_nextpos));

#line 68 "cocn.mod"
pOt__Epilogue:;
#line 68 "cocn.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 68 "cocn.mod"
}
#line 68 "cocn.mod"

#line 68 "cocn.mod"

#line 74 "cocn.mod"
struct pOt__tag_0_COCN {
#line 74 "cocn.mod"
  pOt__ArrTypDsc *td;
#line 74 "cocn.mod"
  pOt_CHAR arr[0x5L];
#line 74 "cocn.mod"
} ;
#line 74 "cocn.mod"
static pOt__ArrTypDsc pOt__td_0_COCN= {
#line 74 "cocn.mod"
  1,
#line 74 "cocn.mod"
  0x5L, sizeof(pOt_CHAR)
#line 74 "cocn.mod"
};
#line 74 "cocn.mod"

#line 74 "cocn.mod"

#line 74 "cocn.mod"
extern void pOt_CTDName_COCN
#line 74 "cocn.mod"
#if pOt__ANSI_C
#line 74 "cocn.mod"
  (pOt_Struct_COCT pOt_typ, pOt_INTEGER pOt_pos, pOt_INTEGER *pOt_nextpos)
#line 74 "cocn.mod"
#else
#line 74 "cocn.mod"
  (pOt_typ, pOt_pos, pOt_nextpos)
#line 74 "cocn.mod"
  pOt_Struct_COCT pOt_typ;
#line 74 "cocn.mod"
  pOt_INTEGER pOt_pos, *pOt_nextpos;
#line 74 "cocn.mod"

#line 74 "cocn.mod"
#endif
#line 74 "cocn.mod"
{
#line 74 "cocn.mod"
  pOt_Object_COCT pOt_head;
#line 74 "cocn.mod"
  struct pOt__tag_0_COCN pOt_s;
#line 74 "cocn.mod"
  struct {void *next, *vars[0x3];} pOt__gc_ptrs;
#line 74 "cocn.mod"
  struct {void *next, *vars[0x1];} pOt__gc_strs;
#line 74 "cocn.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 74 "cocn.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 74 "cocn.mod"
  pOt__gc_ptrs.vars[0x2]=pOt_NIL;
#line 74 "cocn.mod"
  pOt__gc_strs.vars[0x0]=pOt_NIL;
#line 74 "cocn.mod"
  pOt__gc_ptrs.vars[0x1]=&pOt_typ;
#line 74 "cocn.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_head;
#line 74 "cocn.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 74 "cocn.mod"
  pOt_head=pOt_NIL;
#line 74 "cocn.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_s,(pOt__TypDsc*)&pOt__td_0_COCN);
#line 74 "cocn.mod"

#line 74 "cocn.mod"
  (*pOt_nextpos)=(pOt_INTEGER)(pOt_pos);
#line 76 "cocn.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x40L],&pOt__str_td[0x8]))),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
  pOt_FromLInt_Strings((pOt_LONGINT)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_descr),16,(pOt__ArrTypDsc**)&pOt_s);
#line 77 "cocn.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&pOt_s),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xCL],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
  if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_mno==((pOt_INTEGER)(0)))) {
    pOt_head=(struct pOt__tag_1_COCT*)(pOt_topScope_COCT);
    for(;;) {
#line 81 "cocn.mod"
      if(( (*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_head))).pOt_mnolev!=((pOt_INTEGER)(0)))); else break;
#line 81 "cocn.mod"
      pOt_head=(struct pOt__tag_1_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_head))).pOt_dsc);
#line 81 "cocn.mod"
    }
#line 81 "cocn.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_head))).pOt_name),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 83 "cocn.mod"
  } else {
#line 83 "cocn.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_GlbMod_COCT.arr[pOt__inxchk(__FILE__,__LINE__,0x40, (pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_mno),(pOt_LONGINT)(1),5))]))).pOt_name),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 85 "cocn.mod"
  }
#line 85 "cocn.mod"

#line 85 "cocn.mod"
pOt__Epilogue:;
#line 85 "cocn.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 85 "cocn.mod"
}
#line 85 "cocn.mod"

#line 85 "cocn.mod"

#line 91 "cocn.mod"
struct pOt__tag_1_COCN {
#line 91 "cocn.mod"
  pOt__ArrTypDsc *td;
#line 91 "cocn.mod"
  pOt_CHAR arr[0x5L];
#line 91 "cocn.mod"
} ;
#line 91 "cocn.mod"
static pOt__ArrTypDsc pOt__td_1_COCN= {
#line 91 "cocn.mod"
  1,
#line 91 "cocn.mod"
  0x5L, sizeof(pOt_CHAR)
#line 91 "cocn.mod"
};
#line 91 "cocn.mod"

#line 91 "cocn.mod"

#line 91 "cocn.mod"
extern void pOt_CTagName_COCN
#line 91 "cocn.mod"
#if pOt__ANSI_C
#line 91 "cocn.mod"
  (pOt_Struct_COCT pOt_typ, pOt_INTEGER pOt_pos, pOt_INTEGER *pOt_nextpos)
#line 91 "cocn.mod"
#else
#line 91 "cocn.mod"
  (pOt_typ, pOt_pos, pOt_nextpos)
#line 91 "cocn.mod"
  pOt_Struct_COCT pOt_typ;
#line 91 "cocn.mod"
  pOt_INTEGER pOt_pos, *pOt_nextpos;
#line 91 "cocn.mod"

#line 91 "cocn.mod"
#endif
#line 91 "cocn.mod"
{
#line 91 "cocn.mod"
  pOt_Object_COCT pOt_head;
#line 91 "cocn.mod"
  struct pOt__tag_1_COCN pOt_s;
#line 91 "cocn.mod"
  struct {void *next, *vars[0x3];} pOt__gc_ptrs;
#line 91 "cocn.mod"
  struct {void *next, *vars[0x1];} pOt__gc_strs;
#line 91 "cocn.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 91 "cocn.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 91 "cocn.mod"
  pOt__gc_ptrs.vars[0x2]=pOt_NIL;
#line 91 "cocn.mod"
  pOt__gc_strs.vars[0x0]=pOt_NIL;
#line 91 "cocn.mod"
  pOt__gc_ptrs.vars[0x1]=&pOt_typ;
#line 91 "cocn.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_head;
#line 91 "cocn.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 91 "cocn.mod"
  pOt_head=pOt_NIL;
#line 91 "cocn.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_s,(pOt__TypDsc*)&pOt__td_1_COCN);
#line 91 "cocn.mod"

#line 91 "cocn.mod"
  (*pOt_nextpos)=(pOt_INTEGER)(pOt_pos);
#line 93 "cocn.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x50L],&pOt__str_td[0x10]))),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 93 "cocn.mod"
  pOt_FromLInt_Strings((pOt_LONGINT)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_descr),16,(pOt__ArrTypDsc**)&pOt_s);
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&pOt_s),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xCL],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
  if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_mno==((pOt_INTEGER)(0)))) {
    pOt_head=(struct pOt__tag_1_COCT*)(pOt_topScope_COCT);
    for(;;) {
#line 98 "cocn.mod"
      if(( (*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_head))).pOt_mnolev!=((pOt_INTEGER)(0)))); else break;
#line 98 "cocn.mod"
      pOt_head=(struct pOt__tag_1_COCT*)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_head))).pOt_dsc);
#line 98 "cocn.mod"
    }
#line 98 "cocn.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_head))).pOt_name),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 100 "cocn.mod"
  } else {
#line 100 "cocn.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_GlbMod_COCT.arr[pOt__inxchk(__FILE__,__LINE__,0x40, (pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_mno),(pOt_LONGINT)(1),5))]))).pOt_name),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 102 "cocn.mod"
  }
#line 102 "cocn.mod"

#line 102 "cocn.mod"
pOt__Epilogue:;
#line 102 "cocn.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 102 "cocn.mod"
}
#line 102 "cocn.mod"

#line 102 "cocn.mod"

#line 108 "cocn.mod"

#line 108 "cocn.mod"

#line 108 "cocn.mod"
extern void pOt_CTDenoter_COCN
#line 108 "cocn.mod"
#if pOt__ANSI_C
#line 108 "cocn.mod"
  (pOt_Struct_COCT pOt_typ, pOt_INTEGER pOt_pos, pOt_INTEGER *pOt_nextpos)
#line 108 "cocn.mod"
#else
#line 108 "cocn.mod"
  (pOt_typ, pOt_pos, pOt_nextpos)
#line 108 "cocn.mod"
  pOt_Struct_COCT pOt_typ;
#line 108 "cocn.mod"
  pOt_INTEGER pOt_pos, *pOt_nextpos;
#line 108 "cocn.mod"

#line 108 "cocn.mod"
#endif
#line 108 "cocn.mod"
{
#line 108 "cocn.mod"
  struct pOt__tag_3_COCT pOt_y;
#line 108 "cocn.mod"
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
#line 108 "cocn.mod"
  struct {void *next, *vars[0x2];} pOt__gc_strs;
#line 108 "cocn.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 108 "cocn.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 108 "cocn.mod"
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
#line 108 "cocn.mod"
  pOt__gc_strs.vars[0x1]=pOt_NIL;
#line 108 "cocn.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_typ;
#line 108 "cocn.mod"
  pOt__gc_strs.vars[0x0]=&pOt_y;
#line 108 "cocn.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 108 "cocn.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_y,(pOt__TypDsc*)&pOt__td_3_COCT);
#line 108 "cocn.mod"

#line 108 "cocn.mod"
  (*pOt_nextpos)=(pOt_INTEGER)(pOt_pos);
  switch((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_form) {
#line 109 "cocn.mod"
  case 0:
  break;
#line 110 "cocn.mod"
  case 2:
#line 110 "cocn.mod"
  case 3:
#line 110 "cocn.mod"
  case 4:
#line 110 "cocn.mod"
  case 5:
#line 110 "cocn.mod"
  case 6:
#line 110 "cocn.mod"
  case 7:
#line 110 "cocn.mod"
  case 8:
#line 110 "cocn.mod"
  case 9:
#line 110 "cocn.mod"
    pOt_y.pOt_mode=13;
    pOt_y.pOt_typ=(struct pOt__tag_2_COCT*)(pOt_typ);
#line 111 "cocn.mod"
    pOt_y.pOt_obj=(struct pOt__tag_1_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_strobj);
    if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_mno>((pOt_INTEGER)(0)))) {
#line 112 "cocn.mod"
      pOt_y.pOt_mnolev=(pOt_INTEGER)(-(*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_mno);
    } else {
#line 113 "cocn.mod"
      pOt_FindObj_COCT((struct pOt__tag_1_COCT*)(pOt_y.pOt_obj),&pOt_y.pOt_mnolev);
    }
#line 114 "cocn.mod"
    pOt_CObjName_COCN((struct pOt__tag_3_COCT*)&pOt_y,(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 116 "cocn.mod"
  break;
#line 116 "cocn.mod"
  case 10:
#line 116 "cocn.mod"
  case 11:
#line 116 "cocn.mod"
  break;
  case 12:
#line 117 "cocn.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x68L],&pOt__str_td[0x4]))),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
  break;
#line 118 "cocn.mod"
  case 13:
#line 118 "cocn.mod"
    pOt_CTDenoter_COCN((struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_BaseTyp),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 118 "cocn.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x74L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
  break;
#line 119 "cocn.mod"
  case 14:
#line 119 "cocn.mod"
    pOt_CTDenoter_COCN((struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_typ))).pOt_BaseTyp),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 119 "cocn.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x7CL],&pOt__str_td[0x5]))),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
  break;
#line 120 "cocn.mod"
  case 16:
#line 120 "cocn.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x88L],&pOt__str_td[0x10]))),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
  break;
#line 121 "cocn.mod"
  case 15:
#line 121 "cocn.mod"
  case 17:
#line 121 "cocn.mod"
    pOt_CTagName_COCN((struct pOt__tag_2_COCT*)(pOt_typ),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 123 "cocn.mod"
  break;
#line 123 "cocn.mod"
  default:;
#line 123 "cocn.mod"
    pOt__halt(__FILE__,__LINE__,0x10);
#line 123 "cocn.mod"
  }
#line 123 "cocn.mod"

#line 123 "cocn.mod"
pOt__Epilogue:;
#line 123 "cocn.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 123 "cocn.mod"
}
#line 123 "cocn.mod"

#line 123 "cocn.mod"

#line 127 "cocn.mod"

#line 127 "cocn.mod"

#line 127 "cocn.mod"
extern void pOt_CTSize_COCN
#line 127 "cocn.mod"
#if pOt__ANSI_C
#line 127 "cocn.mod"
  (pOt_Struct_COCT pOt_typ, pOt_INTEGER pOt_pos, pOt_INTEGER *pOt_nextpos)
#line 127 "cocn.mod"
#else
#line 127 "cocn.mod"
  (pOt_typ, pOt_pos, pOt_nextpos)
#line 127 "cocn.mod"
  pOt_Struct_COCT pOt_typ;
#line 127 "cocn.mod"
  pOt_INTEGER pOt_pos, *pOt_nextpos;
#line 127 "cocn.mod"

#line 127 "cocn.mod"
#endif
#line 127 "cocn.mod"
{
#line 127 "cocn.mod"
  struct pOt__tag_3_COCT pOt_y;
#line 127 "cocn.mod"
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
#line 127 "cocn.mod"
  struct {void *next, *vars[0x2];} pOt__gc_strs;
#line 127 "cocn.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 127 "cocn.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 127 "cocn.mod"
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
#line 127 "cocn.mod"
  pOt__gc_strs.vars[0x1]=pOt_NIL;
#line 127 "cocn.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_typ;
#line 127 "cocn.mod"
  pOt__gc_strs.vars[0x0]=&pOt_y;
#line 127 "cocn.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 127 "cocn.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_y,(pOt__TypDsc*)&pOt__td_3_COCT);
#line 127 "cocn.mod"

#line 127 "cocn.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xA0L],&pOt__str_td[0x7]))),(pOt_INTEGER)(pOt_pos),&(*pOt_nextpos));
  pOt_CTDenoter_COCN((struct pOt__tag_2_COCT*)(pOt_typ),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 130 "cocn.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x28L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));

#line 131 "cocn.mod"
pOt__Epilogue:;
#line 131 "cocn.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 131 "cocn.mod"
}
#line 131 "cocn.mod"

#line 131 "cocn.mod"

#line 134 "cocn.mod"

#line 134 "cocn.mod"

#line 134 "cocn.mod"
extern void pOt_CBodyName_COCN
#line 134 "cocn.mod"
#if pOt__ANSI_C
#line 134 "cocn.mod"
  (pOt_Object_COCT pOt_obj, pOt_INTEGER pOt_pos, pOt_INTEGER *pOt_nextpos)
#line 134 "cocn.mod"
#else
#line 134 "cocn.mod"
  (pOt_obj, pOt_pos, pOt_nextpos)
#line 134 "cocn.mod"
  pOt_Object_COCT pOt_obj;
#line 134 "cocn.mod"
  pOt_INTEGER pOt_pos, *pOt_nextpos;
#line 134 "cocn.mod"

#line 134 "cocn.mod"
#endif
#line 134 "cocn.mod"
{
#line 134 "cocn.mod"
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
#line 134 "cocn.mod"
  struct {void *next, *vars[0x1];} pOt__gc_strs;
#line 134 "cocn.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 134 "cocn.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 134 "cocn.mod"
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
#line 134 "cocn.mod"
  pOt__gc_strs.vars[0x0]=pOt_NIL;
#line 134 "cocn.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_obj;
#line 134 "cocn.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 134 "cocn.mod"

#line 134 "cocn.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x4]))),(pOt_INTEGER)(pOt_pos),&(*pOt_nextpos));
#line 134 "cocn.mod"
  if(( (*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_obj))).pOt_mnolev==((pOt_INTEGER)(0)))) {
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_obj))).pOt_name),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
  } else {
#line 136 "cocn.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_GlbMod_COCT.arr[pOt__inxchk(__FILE__,__LINE__,0x40, (pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_obj))).pOt_mnolev),(pOt_LONGINT)(1),5))]))).pOt_name),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
  }
#line 137 "cocn.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xACL],&pOt__str_td[0x6]))),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 139 "cocn.mod"

#line 139 "cocn.mod"
pOt__Epilogue:;
#line 139 "cocn.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 139 "cocn.mod"
}
#line 139 "cocn.mod"

#line 139 "cocn.mod"

#line 142 "cocn.mod"

#line 142 "cocn.mod"

#line 142 "cocn.mod"
extern void pOt_CBodyFlagName_COCN
#line 142 "cocn.mod"
#if pOt__ANSI_C
#line 142 "cocn.mod"
  (pOt_Object_COCT pOt_obj, pOt_INTEGER pOt_pos, pOt_INTEGER *pOt_nextpos)
#line 142 "cocn.mod"
#else
#line 142 "cocn.mod"
  (pOt_obj, pOt_pos, pOt_nextpos)
#line 142 "cocn.mod"
  pOt_Object_COCT pOt_obj;
#line 142 "cocn.mod"
  pOt_INTEGER pOt_pos, *pOt_nextpos;
#line 142 "cocn.mod"

#line 142 "cocn.mod"
#endif
#line 142 "cocn.mod"
{
#line 142 "cocn.mod"
  struct {void *next, *vars[0x2];} pOt__gc_ptrs;
#line 142 "cocn.mod"
  struct {void *next, *vars[0x1];} pOt__gc_strs;
#line 142 "cocn.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 142 "cocn.mod"
  pOt__gc_strs.next = &pOt__gc_ptrs;
#line 142 "cocn.mod"
  pOt__gc_ptrs.vars[0x1]=pOt_NIL;
#line 142 "cocn.mod"
  pOt__gc_strs.vars[0x0]=pOt_NIL;
#line 142 "cocn.mod"
  pOt__gc_ptrs.vars[0x0]=&pOt_obj;
#line 142 "cocn.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 142 "cocn.mod"

#line 142 "cocn.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x4]))),(pOt_INTEGER)(pOt_pos),&(*pOt_nextpos));
#line 142 "cocn.mod"
  if(( (*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_obj))).pOt_mnolev==((pOt_INTEGER)(0)))) {
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_obj))).pOt_name),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
  } else {
#line 144 "cocn.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_GlbMod_COCT.arr[pOt__inxchk(__FILE__,__LINE__,0x40, (pOt_INTEGER)pOt__subchk(__FILE__,__LINE__,(pOt_LONGINT)((*((struct pOt__tag_1_COCT*)pOt__nilchk(__FILE__,__LINE__,pOt_obj))).pOt_mnolev),(pOt_LONGINT)(1),5))]))).pOt_name),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
  }
#line 145 "cocn.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xB8L],&pOt__str_td[0x8]))),(pOt_INTEGER)((*pOt_nextpos)),&(*pOt_nextpos));
#line 147 "cocn.mod"

#line 147 "cocn.mod"
pOt__Epilogue:;
#line 147 "cocn.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 147 "cocn.mod"
}
#line 147 "cocn.mod"

#line 147 "cocn.mod"
void pOt_COCN__body()
#line 149 "cocn.mod"
{
#line 149 "cocn.mod"
  static int pOt_COCN__loaded=0;
#line 149 "cocn.mod"
  if(!pOt_COCN__loaded){
#line 149 "cocn.mod"
    pOt_COCN__loaded=1;
#line 149 "cocn.mod"

#line 149 "cocn.mod"
    pOt_Strings__body();
#line 149 "cocn.mod"
    pOt_Reals__body();
#line 149 "cocn.mod"
    pOt_COCT__body();
#line 149 "cocn.mod"
    pOt_COCQ__body();
#line 149 "cocn.mod"

#line 149 "cocn.mod"
    pOt__gc_ptrs.next=pOt__gc_root;
#line 149 "cocn.mod"
    pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 149 "cocn.mod"

#line 149 "cocn.mod"

#line 149 "cocn.mod"

#line 149 "cocn.mod"
  pOt__Epilogue:;
#line 149 "cocn.mod"
  }
#line 149 "cocn.mod"
}
#line 149 "cocn.mod"
