/* This code is generated by pOt. */
#line 20 "coco.mod"

#line 20 "coco.mod"
#include <pOtRTL.h>
#line 20 "coco.mod"
#include "Files.h"
#line 20 "coco.mod"
#include "Strings.h"
#line 20 "coco.mod"
#include "COCS.h"
#line 20 "coco.mod"

#line 20 "coco.mod"
#include "COCO.hi"
#line 20 "coco.mod"

#line 20 "coco.mod"

#line 20 "coco.mod"
struct pOt__tag_0_COCO {
#line 20 "coco.mod"
  pOt__ArrTypDsc *td;
#line 20 "coco.mod"
  pOt_CHAR arr[0x2L];
#line 20 "coco.mod"
} ;
#line 20 "coco.mod"
pOt__ArrTypDsc pOt__td_0_COCO= {
#line 20 "coco.mod"
  1,
#line 20 "coco.mod"
  0x2L, sizeof(pOt_CHAR)
#line 20 "coco.mod"
};
#line 20 "coco.mod"

#line 20 "coco.mod"
pOt_BOOLEAN pOt_fold_COCO, pOt_linenum_COCO, pOt_macwrap_COCO, pOt_unxwrap_COCO;
#line 20 "coco.mod"
static struct pOt__tag_0_COCO pOt_NL_COCO;
#line 20 "coco.mod"
static pOt_INTEGER pOt_NLlen_COCO;
#line 20 "coco.mod"
static pOt_File_Files pOt_ofile_COCO;
#line 20 "coco.mod"
static struct pOt__tag_2_Files pOt_Output_COCO;
#line 20 "coco.mod"
static pOt_INTEGER pOt_indlevel_COCO;
#line 20 "coco.mod"
static pOt_BOOLEAN pOt_newline_COCO;
#line 20 "coco.mod"
static pOt_LONGINT pOt_txtline_COCO;
#line 20 "coco.mod"
static pOt_INTEGER pOt_cpos_COCO;
#line 20 "coco.mod"

#line 20 "coco.mod"
static struct {void *next, *vars[0x2];} pOt__gc_ptrs = {pOt_NIL,{
#line 20 "coco.mod"
  &pOt_ofile_COCO,
#line 20 "coco.mod"
  pOt_NIL
#line 20 "coco.mod"
}};
#line 20 "coco.mod"
static struct {void *next, *vars[0x2];} pOt__gc_strs = {&pOt__gc_ptrs,{
#line 20 "coco.mod"
  &pOt_Output_COCO,
#line 20 "coco.mod"
  pOt_NIL
#line 20 "coco.mod"
}};
#line 20 "coco.mod"

#line 20 "coco.mod"


#line 21 "coco.mod"

#line 21 "coco.mod"
extern pOt_LONGINT pOt_Size_COCO()
#line 21 "coco.mod"
{
#line 21 "coco.mod"
  pOt_LONGINT pOt__retval;
#line 21 "coco.mod"
  int pOt__gc_enabled_prev;
#line 21 "coco.mod"
  pOt__gc_enabled_prev=pOt__gc_enabled;
#line 21 "coco.mod"
  pOt__gc_enabled=0;
#line 21 "coco.mod"

#line 21 "coco.mod"
  pOt__retval =(pOt_LONGINT)((pOt_LONGINT)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_Pos_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO)),(pOt_LONGINT)(1),6));
  goto pOt__Epilogue;
#line 22 "coco.mod"

#line 22 "coco.mod"
  pOt__halt(__FILE__,__LINE__,0x11);
#line 22 "coco.mod"
pOt__Epilogue:;
#line 22 "coco.mod"
  pOt__gc_enabled=pOt__gc_enabled_prev;
#line 22 "coco.mod"
  return pOt__retval;
#line 22 "coco.mod"
}
#line 22 "coco.mod"

#line 22 "coco.mod"

#line 25 "coco.mod"

#line 25 "coco.mod"

#line 25 "coco.mod"
extern void pOt_Open_COCO
#line 25 "coco.mod"
#if pOt__ANSI_C
#line 25 "coco.mod"
  (pOt__DynArr *pOt_name)
#line 25 "coco.mod"
#else
#line 25 "coco.mod"
  (pOt_name)
#line 25 "coco.mod"
  pOt__DynArr *pOt_name;
#line 25 "coco.mod"

#line 25 "coco.mod"
#endif
#line 25 "coco.mod"
{
#line 25 "coco.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 25 "coco.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 25 "coco.mod"

#line 25 "coco.mod"
  pOt_ofile_COCO=(struct pOt__tag_1_Files*)(pOt_New_Files(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt_name))));
#line 25 "coco.mod"
  if(( pOt_ofile_COCO==pOt_NIL)) {
#line 25 "coco.mod"
    pOt__halt(__FILE__,__LINE__,33);
#line 25 "coco.mod"
  }
#line 25 "coco.mod"
  pOt_Set_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,(struct pOt__tag_1_Files*)(pOt_ofile_COCO),(pOt_LONGINT)(0));
#line 27 "coco.mod"
  pOt_indlevel_COCO=(pOt_INTEGER)(0);
#line 27 "coco.mod"
  pOt_txtline_COCO=(pOt_LONGINT)(1);
#line 27 "coco.mod"
  pOt_newline_COCO=(pOt_BOOLEAN)1;
#line 27 "coco.mod"
  pOt_cpos_COCO=(pOt_INTEGER)(0);
  pOt_NLlen_COCO=(pOt_INTEGER)(0);
  if(pOt_macwrap_COCO) {
#line 29 "coco.mod"
    pOt_NL_COCO.arr[pOt__inxchk(__FILE__,__LINE__,0x2, pOt_NLlen_COCO)]='\15';
#line 29 "coco.mod"
    pOt_NLlen_COCO+=(1);
#line 29 "coco.mod"
  }
#line 29 "coco.mod"
  if(pOt_unxwrap_COCO) {
    pOt_NL_COCO.arr[pOt__inxchk(__FILE__,__LINE__,0x2, pOt_NLlen_COCO)]='\12';
#line 30 "coco.mod"
    pOt_NLlen_COCO+=(1);
#line 30 "coco.mod"
  }
#line 30 "coco.mod"
  if(( pOt_NLlen_COCO==((pOt_INTEGER)(0)))) {
    pOt_NL_COCO.arr[pOt__inxchk(__FILE__,__LINE__,0x2, pOt_NLlen_COCO)]='\12';
#line 31 "coco.mod"
    pOt_NLlen_COCO+=(1);
  }
#line 32 "coco.mod"

#line 32 "coco.mod"
pOt__Epilogue:;
#line 32 "coco.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 32 "coco.mod"
}
#line 32 "coco.mod"

#line 32 "coco.mod"

#line 35 "coco.mod"

#line 35 "coco.mod"

#line 35 "coco.mod"
extern void pOt_Close_COCO()
#line 35 "coco.mod"
{
#line 35 "coco.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 35 "coco.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 35 "coco.mod"

#line 35 "coco.mod"
  pOt_Set_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,(struct pOt__tag_1_Files*)(pOt_NIL),(pOt_LONGINT)(0));
#line 35 "coco.mod"
  pOt_Close_Files((struct pOt__tag_1_Files*)(pOt_ofile_COCO));

#line 36 "coco.mod"
pOt__Epilogue:;
#line 36 "coco.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 36 "coco.mod"
}
#line 36 "coco.mod"

#line 36 "coco.mod"

#line 39 "coco.mod"

#line 39 "coco.mod"

#line 39 "coco.mod"
extern void pOt_Purge_COCO()
#line 39 "coco.mod"
{
#line 39 "coco.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 39 "coco.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 39 "coco.mod"

#line 39 "coco.mod"
  pOt_Set_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,(struct pOt__tag_1_Files*)(pOt_NIL),(pOt_LONGINT)(0));
#line 39 "coco.mod"
  pOt_Purge_Files((struct pOt__tag_1_Files*)(pOt_ofile_COCO));

#line 40 "coco.mod"
pOt__Epilogue:;
#line 40 "coco.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 40 "coco.mod"
}
#line 40 "coco.mod"

#line 40 "coco.mod"

#line 43 "coco.mod"

#line 43 "coco.mod"

#line 43 "coco.mod"
extern void pOt_Indent_COCO()
#line 43 "coco.mod"
{
#line 43 "coco.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 43 "coco.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 43 "coco.mod"

#line 43 "coco.mod"
  pOt_indlevel_COCO+=(2);

#line 44 "coco.mod"
pOt__Epilogue:;
#line 44 "coco.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 44 "coco.mod"
}
#line 44 "coco.mod"

#line 44 "coco.mod"

#line 47 "coco.mod"

#line 47 "coco.mod"

#line 47 "coco.mod"
extern void pOt_Undent_COCO()
#line 47 "coco.mod"
{
#line 47 "coco.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 47 "coco.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 47 "coco.mod"

#line 47 "coco.mod"
  if(( pOt_indlevel_COCO>=((pOt_INTEGER)(2)))) {
#line 47 "coco.mod"
    pOt_indlevel_COCO-=(2);
  }
#line 48 "coco.mod"

#line 48 "coco.mod"
pOt__Epilogue:;
#line 48 "coco.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 48 "coco.mod"
}
#line 48 "coco.mod"

#line 48 "coco.mod"

#line 51 "coco.mod"

#line 51 "coco.mod"

#line 51 "coco.mod"
extern void pOt_Separate_COCO()
#line 51 "coco.mod"
{
#line 51 "coco.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 51 "coco.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 51 "coco.mod"

#line 51 "coco.mod"
  pOt_Write_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,' ');

#line 52 "coco.mod"
pOt__Epilogue:;
#line 52 "coco.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 52 "coco.mod"
}
#line 52 "coco.mod"

#line 52 "coco.mod"

#line 59 "coco.mod"
struct pOt__tag_1_COCO {
#line 59 "coco.mod"
  pOt__ArrTypDsc *td;
#line 59 "coco.mod"
  pOt_CHAR arr[0x7L];
#line 59 "coco.mod"
} ;
#line 59 "coco.mod"
static pOt__ArrTypDsc pOt__td_1_COCO= {
#line 59 "coco.mod"
  1,
#line 59 "coco.mod"
  0x7L, sizeof(pOt_CHAR)
#line 59 "coco.mod"
};
#line 59 "coco.mod"
struct pOt__tag_2_COCO {
#line 59 "coco.mod"
  pOt__ArrTypDsc *td;
#line 59 "coco.mod"
  pOt_CHAR arr[0xBL];
#line 59 "coco.mod"
} ;
#line 59 "coco.mod"
static pOt__ArrTypDsc pOt__td_2_COCO= {
#line 59 "coco.mod"
  1,
#line 59 "coco.mod"
  0xBL, sizeof(pOt_CHAR)
#line 59 "coco.mod"
};
#line 59 "coco.mod"

#line 59 "coco.mod"

#line 59 "coco.mod"
extern void pOt_Wrap_COCO()
#line 59 "coco.mod"
{
#line 59 "coco.mod"
  pOt_INTEGER pOt_i;
#line 59 "coco.mod"
  struct pOt__tag_1_COCO pOt_linepgm;
#line 59 "coco.mod"
  struct pOt__tag_2_COCO pOt_lineno;
#line 59 "coco.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 59 "coco.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 59 "coco.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_linepgm,(pOt__TypDsc*)&pOt__td_1_COCO);
#line 59 "coco.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_lineno,(pOt__TypDsc*)&pOt__td_2_COCO);
#line 59 "coco.mod"

#line 59 "coco.mod"
  pOt_newline_COCO=(pOt_BOOLEAN)1;
  pOt_WriteBytes_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,pOt__make_byte_arr((void*)&pOt_NL_COCO,1,0),(pOt_LONGINT)(pOt_NLlen_COCO));
  if((pOt_linenum_COCO&&((pOt_txtline_COCO!=pOt_txtpos_COCS.pOt_line)))) {
    pOt__arr_assign((pOt__ArrTypDsc**)& pOt_linepgm,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__td_1_COCO)));
#line 62 "coco.mod"
    pOt_FromLInt_Strings((pOt_LONGINT)(pOt_txtpos_COCS.pOt_line),10,(pOt__ArrTypDsc**)&pOt_lineno);
#line 64 "coco.mod"
    pOt_WriteBytes_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,pOt__make_byte_arr((void*)&pOt_linepgm,1,0),(pOt_LONGINT)(pOt_Length_Strings(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&pOt_linepgm))));
    pOt_WriteBytes_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,pOt__make_byte_arr((void*)&pOt_lineno,1,0),(pOt_LONGINT)(pOt_Length_Strings(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&pOt_lineno))));
    pOt_Write_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,' ');
#line 66 "coco.mod"
    pOt_Write_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,'\"');
#line 66 "coco.mod"
    pOt_WriteBytes_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,pOt__make_byte_arr((void*)&pOt_txtpos_COCS.pOt_name,1,0),(pOt_LONGINT)(pOt_Length_Strings(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&pOt_txtpos_COCS.pOt_name))));
    pOt_Write_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,'\"');
    pOt_WriteBytes_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,pOt__make_byte_arr((void*)&pOt_NL_COCO,1,0),(pOt_LONGINT)(pOt_NLlen_COCO));
    pOt_txtline_COCO=(pOt_LONGINT)(pOt_txtpos_COCS.pOt_line);
  }
#line 70 "coco.mod"
  pOt_txtline_COCO+=(1);
#line 72 "coco.mod"

#line 72 "coco.mod"
pOt__Epilogue:;
#line 72 "coco.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 72 "coco.mod"
}
#line 72 "coco.mod"

#line 72 "coco.mod"

#line 76 "coco.mod"

#line 76 "coco.mod"

#line 76 "coco.mod"
extern void pOt_PutSeq_COCO
#line 76 "coco.mod"
#if pOt__ANSI_C
#line 76 "coco.mod"
  (pOt__DynArr *pOt_s)
#line 76 "coco.mod"
#else
#line 76 "coco.mod"
  (pOt_s)
#line 76 "coco.mod"
  pOt__DynArr *pOt_s;
#line 76 "coco.mod"

#line 76 "coco.mod"
#endif
#line 76 "coco.mod"
{
#line 76 "coco.mod"
  pOt_INTEGER pOt_i, pOt_j;
#line 76 "coco.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 76 "coco.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 76 "coco.mod"

#line 76 "coco.mod"
  if(pOt_newline_COCO) {
#line 78 "coco.mod"
    pOt_newline_COCO=(pOt_BOOLEAN)0;
#line 78 "coco.mod"
    pOt_i=(pOt_INTEGER)(0);
#line 78 "coco.mod"
    for(;;) {
      if(( pOt_i!=pOt_indlevel_COCO)); else break;
#line 79 "coco.mod"
      pOt_Write_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,' ');
#line 79 "coco.mod"
      pOt_i+=(1);
#line 79 "coco.mod"
    }
#line 79 "coco.mod"
    pOt_cpos_COCO=(pOt_INTEGER)(pOt_i);
#line 81 "coco.mod"
  }
#line 81 "coco.mod"
  pOt_i=(pOt_INTEGER)(0);
  pOt_j=(pOt_INTEGER)(0);
#line 82 "coco.mod"
  for(;;) {
#line 82 "coco.mod"
    if(((unsigned char) (*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i)))))==(unsigned char)' ')); else break;
#line 82 "coco.mod"
    pOt_i+=(1);
#line 82 "coco.mod"
  }
#line 82 "coco.mod"
  if(pOt_fold_COCO) {
#line 85 "coco.mod"
    for(;;) {
#line 85 "coco.mod"
      if(( pOt_i!=pOt_j)) {
#line 85 "coco.mod"
        (*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_j)))))=(*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i)))));
#line 85 "coco.mod"
      }
#line 85 "coco.mod"
      if(((unsigned char) (*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_j)))))==(unsigned char)'\0')) {
        goto pOt__LoopLabel_1;
#line 86 "coco.mod"
      }
#line 86 "coco.mod"
      pOt_i+=(1);
      pOt_j+=(1);
      if((((pOt_cpos_COCO>=((pOt_INTEGER)(80))))&&(((((unsigned char)(*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i)))))==(unsigned char)'('))||(((unsigned char)(*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i)))))==(unsigned char)')')))))) {
        pOt_WriteBytes_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,pOt__make_byte_arr((void*)&(*pOt_s),1,0),(pOt_LONGINT)(pOt_j));
        pOt_Write_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,'\\');
#line 90 "coco.mod"
        pOt_WriteBytes_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,pOt__make_byte_arr((void*)&pOt_NL_COCO,1,0),(pOt_LONGINT)(pOt_NLlen_COCO));
        pOt_j=(pOt_INTEGER)(0);
#line 91 "coco.mod"
        pOt_cpos_COCO=(pOt_INTEGER)(0);
      } else {
#line 92 "coco.mod"
        pOt_cpos_COCO+=(1);
#line 94 "coco.mod"
      }
#line 94 "coco.mod"
    }
  pOt__LoopLabel_1:;
#line 95 "coco.mod"
  } else if(( pOt_i!=pOt_j)) {
    for(;;) {
#line 96 "coco.mod"
      (*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_j)))))=(*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i)))));
#line 96 "coco.mod"
      if(((unsigned char) (*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_j)))))==(unsigned char)'\0')) {
#line 96 "coco.mod"
        goto pOt__LoopLabel_2;
#line 96 "coco.mod"
      }
#line 96 "coco.mod"
      pOt_i+=(1);
      pOt_j+=(1);
#line 99 "coco.mod"
    }
#line 99 "coco.mod"
  pOt__LoopLabel_2:;
#line 99 "coco.mod"
  } else {
#line 99 "coco.mod"
    pOt_j=(pOt_INTEGER)((pOt_LONGINT)pOt__rngchk_i(__FILE__,__LINE__,pOt_Length_Strings(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt_s)))));
  }
#line 100 "coco.mod"
  pOt_WriteBytes_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,pOt__make_byte_arr((void*)&(*pOt_s),1,0),(pOt_LONGINT)(pOt_j));
#line 102 "coco.mod"

#line 102 "coco.mod"
pOt__Epilogue:;
#line 102 "coco.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 102 "coco.mod"
  pOt__rm_par((pOt__TypDsc**)pOt_s);
#line 102 "coco.mod"
}
#line 102 "coco.mod"

#line 102 "coco.mod"

#line 106 "coco.mod"

#line 106 "coco.mod"

#line 106 "coco.mod"
extern void pOt_PutPP_COCO
#line 106 "coco.mod"
#if pOt__ANSI_C
#line 106 "coco.mod"
  (pOt__DynArr *pOt_s)
#line 106 "coco.mod"
#else
#line 106 "coco.mod"
  (pOt_s)
#line 106 "coco.mod"
  pOt__DynArr *pOt_s;
#line 106 "coco.mod"

#line 106 "coco.mod"
#endif
#line 106 "coco.mod"
{
#line 106 "coco.mod"
  pOt_INTEGER pOt_i, pOt_j;
#line 106 "coco.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 106 "coco.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 106 "coco.mod"

#line 106 "coco.mod"
  pOt_Wrap_COCO();
  pOt_Write_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,'#');
#line 109 "coco.mod"
  if(( pOt_indlevel_COCO!=((pOt_INTEGER)(0)))) {
#line 109 "coco.mod"
    pOt_i=(pOt_INTEGER)(2);
#line 109 "coco.mod"
  }
#line 109 "coco.mod"
  for(;;) {
    if(( pOt_i!=pOt_indlevel_COCO)); else break;
#line 110 "coco.mod"
    pOt_Write_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,' ');
#line 110 "coco.mod"
    pOt_i+=(1);
#line 110 "coco.mod"
  }
#line 110 "coco.mod"
  pOt_WriteBytes_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,pOt__make_byte_arr((void*)&(*pOt_s),1,0),(pOt_LONGINT)(pOt_Length_Strings(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt_s)))));
#line 112 "coco.mod"
  pOt_Wrap_COCO();

#line 113 "coco.mod"
pOt__Epilogue:;
#line 113 "coco.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 113 "coco.mod"
  pOt__rm_par((pOt__TypDsc**)pOt_s);
#line 113 "coco.mod"
}
#line 113 "coco.mod"

#line 113 "coco.mod"

#line 119 "coco.mod"
struct pOt__tag_3_COCO {
#line 119 "coco.mod"
  pOt__ArrTypDsc *td;
#line 119 "coco.mod"
  pOt_CHAR arr[0x4L];
#line 119 "coco.mod"
} ;
#line 119 "coco.mod"
static pOt__ArrTypDsc pOt__td_3_COCO= {
#line 119 "coco.mod"
  1,
#line 119 "coco.mod"
  0x4L, sizeof(pOt_CHAR)
#line 119 "coco.mod"
};
#line 119 "coco.mod"

#line 119 "coco.mod"

#line 119 "coco.mod"
extern void pOt_PutComment_COCO
#line 119 "coco.mod"
#if pOt__ANSI_C
#line 119 "coco.mod"
  (pOt__DynArr *pOt_s)
#line 119 "coco.mod"
#else
#line 119 "coco.mod"
  (pOt_s)
#line 119 "coco.mod"
  pOt__DynArr *pOt_s;
#line 119 "coco.mod"

#line 119 "coco.mod"
#endif
#line 119 "coco.mod"
{
#line 119 "coco.mod"
  pOt_INTEGER pOt_i;
#line 119 "coco.mod"
  struct pOt__tag_3_COCO pOt_str;
#line 119 "coco.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 119 "coco.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 119 "coco.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_str,(pOt__TypDsc*)&pOt__td_3_COCO);
#line 119 "coco.mod"

#line 119 "coco.mod"
  pOt_i=(pOt_INTEGER)(0);
  pOt__arr_assign((pOt__ArrTypDsc**)& pOt_str,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xCL],&pOt__td_3_COCO)));
#line 120 "coco.mod"
  pOt_WriteBytes_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,pOt__make_byte_arr((void*)&pOt_str,1,0),(pOt_LONGINT)(pOt_Length_Strings(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&pOt_str))));
  for(;;) {
#line 121 "coco.mod"
    if(((unsigned char) (*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i)))))!=(unsigned char)'\0')); else break;
    pOt_Write_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,(*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i))))));
    if(((((unsigned char)(*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,pOt_i)))))==(unsigned char)'*'))&&(((unsigned char)(*((pOt_CHAR*)(((char *)pOt_s+sizeof(pOt__ArrTypDsc*)+sizeof(pOt_CHAR)*pOt__inxchk(__FILE__,__LINE__,(*(pOt_s))->nofel,(pOt_INTEGER)pOt__addchk(__FILE__,__LINE__,(pOt_LONGINT)(pOt_i),(pOt_LONGINT)(1),5))))))==(unsigned char)'/')))) {
#line 123 "coco.mod"
      pOt_Write_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,'@');
#line 123 "coco.mod"
    }
#line 123 "coco.mod"
    pOt_i+=(1);
#line 125 "coco.mod"
  }
#line 125 "coco.mod"
  pOt__arr_assign((pOt__ArrTypDsc**)& pOt_str,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x14L],&pOt__td_3_COCO)));
  pOt_WriteBytes_Files((struct pOt__tag_2_Files*)&pOt_Output_COCO,pOt__make_byte_arr((void*)&pOt_str,1,0),(pOt_LONGINT)(pOt_Length_Strings(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&pOt_str))));

#line 127 "coco.mod"
pOt__Epilogue:;
#line 127 "coco.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 127 "coco.mod"
  pOt__rm_par((pOt__TypDsc**)pOt_s);
#line 127 "coco.mod"
}
#line 127 "coco.mod"

#line 127 "coco.mod"
void pOt_COCO__body()
#line 129 "coco.mod"
{
#line 129 "coco.mod"
  static int pOt_COCO__loaded=0;
#line 129 "coco.mod"
  if(!pOt_COCO__loaded){
#line 129 "coco.mod"
    pOt_COCO__loaded=1;
#line 129 "coco.mod"

#line 129 "coco.mod"
    pOt_Files__body();
#line 129 "coco.mod"
    pOt_Strings__body();
#line 129 "coco.mod"
    pOt_COCS__body();
#line 129 "coco.mod"

#line 129 "coco.mod"
    pOt__gc_ptrs.next=pOt__gc_root;
#line 129 "coco.mod"
    pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 129 "coco.mod"

#line 129 "coco.mod"
    pOt__init_var((pOt__TypDsc**)&pOt_NL_COCO,(pOt__TypDsc*)&pOt__td_0_COCO);
#line 129 "coco.mod"
    pOt_ofile_COCO=pOt_NIL;
#line 129 "coco.mod"
    pOt__init_var((pOt__TypDsc**)&pOt_Output_COCO,(pOt__TypDsc*)&pOt__td_2_Files);
#line 129 "coco.mod"

#line 129 "coco.mod"
    pOt_fold_COCO=(pOt_BOOLEAN)0;
#line 129 "coco.mod"
    pOt_linenum_COCO=(pOt_BOOLEAN)0;
#line 129 "coco.mod"
    pOt_macwrap_COCO=(pOt_BOOLEAN)0;
#line 129 "coco.mod"
    pOt_unxwrap_COCO=(pOt_BOOLEAN)1;

#line 130 "coco.mod"
  pOt__Epilogue:;
#line 130 "coco.mod"
  }
#line 130 "coco.mod"
}
#line 130 "coco.mod"
