#ifndef pOt_COCO__INC
#define pOt_COCO__INC
/* This code is generated by pOt. */




extern pOt_BOOLEAN pOt_fold_COCO, pOt_linenum_COCO, pOt_macwrap_COCO, pOt_unxwrap_COCO;

extern pOt_LONGINT pOt_Size_COCO pOt__ARGS((void));
extern void pOt_Open_COCO pOt__ARGS((pOt__DynArr *));
extern void pOt_Close_COCO pOt__ARGS((void));
extern void pOt_Purge_COCO pOt__ARGS((void));
extern void pOt_Indent_COCO pOt__ARGS((void));
extern void pOt_Undent_COCO pOt__ARGS((void));
extern void pOt_Separate_COCO pOt__ARGS((void));
extern void pOt_Wrap_COCO pOt__ARGS((void));
extern void pOt_PutSeq_COCO pOt__ARGS((pOt__DynArr *));
extern void pOt_PutPP_COCO pOt__ARGS((pOt__DynArr *));
extern void pOt_PutComment_COCO pOt__ARGS((pOt__DynArr *));
extern void pOt_COCO__body pOt__ARGS((void));

#endif
