#ifndef pOt_COCP__INC
#define pOt_COCP__INC
/* This code is generated by pOt. */

#include "COCT.h"




extern void pOt_AssignPfx_COCP pOt__ARGS((struct pOt__tag_3_COCT *, pOt_BOOLEAN ));
extern void pOt_AssignSfx_COCP pOt__ARGS((struct pOt__tag_3_COCT *, struct pOt__tag_3_COCT *));
extern void pOt_ParamPfx_COCP pOt__ARGS((pOt_Object_COCT ));
extern void pOt_ParamSfx_COCP pOt__ARGS((struct pOt__tag_3_COCT *, pOt_Object_COCT ));
extern void pOt_ParamListPfx_COCP pOt__ARGS((void));
extern void pOt_NextParam_COCP pOt__ARGS((void));
extern void pOt_ParamListSfx_COCP pOt__ARGS((void));
extern void pOt_Trap_COCP pOt__ARGS((struct pOt__tag_3_COCT *));
extern void pOt_COCP__body pOt__ARGS((void));

#endif
