#ifndef pOt_COCQ__INC
#define pOt_COCQ__INC
/* This code is generated by pOt. */

#include "COCT.h"



extern pOt_INTEGER pOt_cslen_COCQ;

extern void pOt_Append_COCQ pOt__ARGS((pOt__DynArr *));
extern void pOt_Prepend_COCQ pOt__ARGS((pOt__DynArr *, pOt_INTEGER , pOt_INTEGER *));
extern void pOt_Rewind_COCQ pOt__ARGS((void));
extern void pOt_Drop_COCQ pOt__ARGS((struct pOt__tag_3_COCT *));
extern void pOt_Link_COCQ pOt__ARGS((struct pOt__tag_3_COCT *));
extern void pOt_Unlink_COCQ pOt__ARGS((struct pOt__tag_3_COCT *));
extern void pOt_Mark_COCQ pOt__ARGS((struct pOt__tag_3_COCT *));
extern void pOt_Release_COCQ pOt__ARGS((struct pOt__tag_3_COCT *));
extern void pOt_Dummy_COCQ pOt__ARGS((void));
extern void pOt_COCQ__body pOt__ARGS((void));

#endif
