#ifndef pOt_COCS__INC
#define pOt_COCS__INC
/* This code is generated by pOt. */



struct pOt__tag_0_COCS {
  pOt__ArrTypDsc *td;
  pOt_CHAR arr[0x80L];
} ;
extern pOt__ArrTypDsc pOt__td_0_COCS;
struct pOt__tag_1_COCS {
  pOt__ArrTypDsc *td;
  pOt_CHAR arr[0x400L];
} ;
extern pOt__ArrTypDsc pOt__td_1_COCS;
struct pOt__tag_2_COCS {
  pOt__RecTypDsc *td;
  struct pOt__tag_1_COCS pOt_name;
  pOt_LONGINT pOt_line;
  pOt_INTEGER pOt_col;
} ;
extern pOt__RecTypDsc pOt__td_2_COCS;

extern pOt_BOOLEAN pOt_linecol_COCS;
extern pOt_INTEGER pOt_numtyp_COCS;
extern pOt_LONGINT pOt_intval_COCS;
extern pOt_REAL pOt_realval_COCS;
extern pOt_LONGREAL pOt_lrlval_COCS;
extern pOt_BOOLEAN pOt_scanerr_COCS;
extern struct pOt__tag_0_COCS pOt_name_COCS;
extern struct pOt__tag_2_COCS pOt_txtpos_COCS;

extern void pOt_Mark_COCS pOt__ARGS((pOt_INTEGER ));
extern void pOt_Get_COCS pOt__ARGS((pOt_INTEGER *));
extern void pOt_Open_COCS pOt__ARGS((pOt__DynArr *));
extern void pOt_Close_COCS pOt__ARGS((void));
extern void pOt_COCS__body pOt__ARGS((void));

#endif
