#ifndef pOt_COCX__INC
#define pOt_COCX__INC
/* This code is generated by pOt. */

#include "COCT.h"




extern void pOt_SubExprPrefix_COCX pOt__ARGS((void));
extern void pOt_SubExprSuffix_COCX pOt__ARGS((void));
extern void pOt_Set00_COCX pOt__ARGS((struct pOt__tag_3_COCT *, pOt_BOOLEAN ));
extern void pOt_Set10_COCX pOt__ARGS((struct pOt__tag_3_COCT *, pOt_BOOLEAN ));
extern void pOt_Set11_COCX pOt__ARGS((struct pOt__tag_3_COCT *, pOt_BOOLEAN ));
extern void pOt_InPfx_COCX pOt__ARGS((struct pOt__tag_3_COCT *, pOt_BOOLEAN ));
extern void pOt_InSfx_COCX pOt__ARGS((void));
extern void pOt_TypTest_COCX pOt__ARGS((struct pOt__tag_3_COCT *, struct pOt__tag_3_COCT *));
extern void pOt_MOp_COCX pOt__ARGS((pOt_INTEGER , struct pOt__tag_3_COCT *, pOt_BOOLEAN ));
extern void pOt_NumOp_COCX pOt__ARGS((pOt_INTEGER , pOt_SET , struct pOt__tag_3_COCT *, struct pOt__tag_3_COCT *, pOt_BOOLEAN ));
extern void pOt_SetOp_COCX pOt__ARGS((pOt_INTEGER , struct pOt__tag_3_COCT *, struct pOt__tag_3_COCT *));
extern void pOt_BoolOp_COCX pOt__ARGS((pOt_INTEGER , struct pOt__tag_3_COCT *, struct pOt__tag_3_COCT *));
extern void pOt_NumRel_COCX pOt__ARGS((pOt_INTEGER , pOt_SET , struct pOt__tag_3_COCT *, struct pOt__tag_3_COCT *));
extern void pOt_StrRel_COCX pOt__ARGS((pOt_INTEGER , struct pOt__tag_3_COCT *, struct pOt__tag_3_COCT *));
extern void pOt_CharRel_COCX pOt__ARGS((pOt_INTEGER , struct pOt__tag_3_COCT *, struct pOt__tag_3_COCT *));
extern void pOt_StProcPfx_COCX pOt__ARGS((pOt_INTEGER , pOt_BOOLEAN ));
extern void pOt_StPar1Sfx_COCX pOt__ARGS((struct pOt__tag_3_COCT *, pOt_INTEGER , pOt_BOOLEAN ));
extern void pOt_StPar2Sfx_COCX pOt__ARGS((struct pOt__tag_3_COCT *, pOt_INTEGER , pOt_BOOLEAN ));
extern void pOt_StPar3Sfx_COCX pOt__ARGS((struct pOt__tag_3_COCT *, pOt_INTEGER , pOt_BOOLEAN ));
extern void pOt_StFakeSfx_COCX pOt__ARGS((pOt_INTEGER , pOt_BOOLEAN ));
extern void pOt_StFctSfx_COCX pOt__ARGS((pOt_INTEGER , pOt_BOOLEAN ));
extern void pOt_COCX__body pOt__ARGS((void));

#endif
