/* This code is generated by pOt. */
#line 16 "cocx.mod"

#line 16 "cocx.mod"
#include <pOtRTL.h>
#line 16 "cocx.mod"
#include "Strings.h"
#line 16 "cocx.mod"
#include "COCT.h"
#line 16 "cocx.mod"
#include "COCQ.h"
#line 16 "cocx.mod"
#include "COCN.h"
#line 16 "cocx.mod"
#include "COCJ.h"
#line 16 "cocx.mod"

#line 16 "cocx.mod"
#include "COCX.hi"
#line 16 "cocx.mod"

#line 16 "cocx.mod"

#line 16 "cocx.mod"

#line 16 "cocx.mod"

#line 16 "cocx.mod"
static struct {void *next, *vars[0x1];} pOt__gc_ptrs = {pOt_NIL,{
#line 16 "cocx.mod"
  pOt_NIL
#line 16 "cocx.mod"
}};
#line 16 "cocx.mod"
static struct {void *next, *vars[0x1];} pOt__gc_strs = {&pOt__gc_ptrs,{
#line 16 "cocx.mod"
  pOt_NIL
#line 16 "cocx.mod"
}};
#line 16 "cocx.mod"

#line 16 "cocx.mod"


#line 17 "cocx.mod"

#line 17 "cocx.mod"
extern void pOt_SubExprPrefix_COCX()
#line 17 "cocx.mod"
{
#line 17 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 17 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 17 "cocx.mod"

#line 17 "cocx.mod"
  pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x1]))));

#line 18 "cocx.mod"
pOt__Epilogue:;
#line 18 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 18 "cocx.mod"
}
#line 18 "cocx.mod"

#line 18 "cocx.mod"

#line 21 "cocx.mod"

#line 21 "cocx.mod"

#line 21 "cocx.mod"
extern void pOt_SubExprSuffix_COCX()
#line 21 "cocx.mod"
{
#line 21 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 21 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 21 "cocx.mod"

#line 21 "cocx.mod"
  pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x8L],&pOt__str_td[0x1]))));

#line 22 "cocx.mod"
pOt__Epilogue:;
#line 22 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 22 "cocx.mod"
}
#line 22 "cocx.mod"

#line 22 "cocx.mod"

#line 26 "cocx.mod"

#line 26 "cocx.mod"

#line 26 "cocx.mod"
extern void pOt_Set00_COCX
#line 26 "cocx.mod"
#if pOt__ANSI_C
#line 26 "cocx.mod"
  (struct pOt__tag_3_COCT *pOt_x, pOt_BOOLEAN pOt_rngchk)
#line 26 "cocx.mod"
#else
#line 26 "cocx.mod"
  (pOt_x, pOt_rngchk)
#line 26 "cocx.mod"
  struct pOt__tag_3_COCT *pOt_x;
#line 26 "cocx.mod"
  pOt_BOOLEAN pOt_rngchk;
#line 26 "cocx.mod"

#line 26 "cocx.mod"
#endif
#line 26 "cocx.mod"
{
#line 26 "cocx.mod"
  pOt_INTEGER pOt_np;
#line 26 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 26 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 26 "cocx.mod"

#line 26 "cocx.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x10L],&pOt__str_td[0x13]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
#line 26 "cocx.mod"
  if(pOt_rngchk) {
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x28L],&pOt__str_td[0x21]))),(pOt_INTEGER)(pOt_np),&pOt_np);
  } else {
#line 28 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x1]))),(pOt_INTEGER)(pOt_np),&pOt_np);
  }
#line 29 "cocx.mod"
  pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x50L],&pOt__str_td[0x2]))));
#line 31 "cocx.mod"

#line 31 "cocx.mod"
pOt__Epilogue:;
#line 31 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 31 "cocx.mod"
}
#line 31 "cocx.mod"

#line 31 "cocx.mod"

#line 36 "cocx.mod"

#line 36 "cocx.mod"

#line 36 "cocx.mod"
extern void pOt_Set10_COCX
#line 36 "cocx.mod"
#if pOt__ANSI_C
#line 36 "cocx.mod"
  (struct pOt__tag_3_COCT *pOt_x, pOt_BOOLEAN pOt_rngchk)
#line 36 "cocx.mod"
#else
#line 36 "cocx.mod"
  (pOt_x, pOt_rngchk)
#line 36 "cocx.mod"
  struct pOt__tag_3_COCT *pOt_x;
#line 36 "cocx.mod"
  pOt_BOOLEAN pOt_rngchk;
#line 36 "cocx.mod"

#line 36 "cocx.mod"
#endif
#line 36 "cocx.mod"
{
#line 36 "cocx.mod"
  pOt_INTEGER pOt_np;
#line 36 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 36 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 36 "cocx.mod"

#line 36 "cocx.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x58L],&pOt__str_td[0x15]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
  if(pOt_rngchk) {
#line 37 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x28L],&pOt__str_td[0x21]))),(pOt_INTEGER)(pOt_np),&pOt_np);
  } else {
#line 38 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x1]))),(pOt_INTEGER)(pOt_np),&pOt_np);
  }
#line 39 "cocx.mod"
  pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x74L],&pOt__str_td[0x19]))));
#line 41 "cocx.mod"
  if(pOt_rngchk) {
#line 41 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x28L],&pOt__str_td[0x21]))));
  } else {
#line 42 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x1]))));
  }
#line 43 "cocx.mod"

pOt__Epilogue:;
#line 44 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 44 "cocx.mod"
}
#line 44 "cocx.mod"

#line 44 "cocx.mod"

#line 47 "cocx.mod"

#line 47 "cocx.mod"

#line 47 "cocx.mod"
extern void pOt_Set11_COCX
#line 47 "cocx.mod"
#if pOt__ANSI_C
#line 47 "cocx.mod"
  (struct pOt__tag_3_COCT *pOt_x, pOt_BOOLEAN pOt_rngchk)
#line 47 "cocx.mod"
#else
#line 47 "cocx.mod"
  (pOt_x, pOt_rngchk)
#line 47 "cocx.mod"
  struct pOt__tag_3_COCT *pOt_x;
#line 47 "cocx.mod"
  pOt_BOOLEAN pOt_rngchk;
#line 47 "cocx.mod"

#line 47 "cocx.mod"
#endif
#line 47 "cocx.mod"
{
#line 47 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 47 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 47 "cocx.mod"

#line 47 "cocx.mod"
  pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x94L],&pOt__str_td[0x4]))));

#line 48 "cocx.mod"
pOt__Epilogue:;
#line 48 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 48 "cocx.mod"
}
#line 48 "cocx.mod"

#line 48 "cocx.mod"

#line 52 "cocx.mod"

#line 52 "cocx.mod"

#line 52 "cocx.mod"
extern void pOt_InPfx_COCX
#line 52 "cocx.mod"
#if pOt__ANSI_C
#line 52 "cocx.mod"
  (struct pOt__tag_3_COCT *pOt_x, pOt_BOOLEAN pOt_rngchk)
#line 52 "cocx.mod"
#else
#line 52 "cocx.mod"
  (pOt_x, pOt_rngchk)
#line 52 "cocx.mod"
  struct pOt__tag_3_COCT *pOt_x;
#line 52 "cocx.mod"
  pOt_BOOLEAN pOt_rngchk;
#line 52 "cocx.mod"

#line 52 "cocx.mod"
#endif
#line 52 "cocx.mod"
{
#line 52 "cocx.mod"
  pOt_INTEGER pOt_np;
#line 52 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 52 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 52 "cocx.mod"

#line 52 "cocx.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xA0L],&pOt__str_td[0x26]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
#line 52 "cocx.mod"
  if(pOt_rngchk) {
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x28L],&pOt__str_td[0x21]))),(pOt_INTEGER)(pOt_np),&pOt_np);
  } else {
#line 54 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x1]))),(pOt_INTEGER)(pOt_np),&pOt_np);
  }
#line 55 "cocx.mod"
  pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xCCL],&pOt__str_td[0x2]))));
#line 57 "cocx.mod"

#line 57 "cocx.mod"
pOt__Epilogue:;
#line 57 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 57 "cocx.mod"
}
#line 57 "cocx.mod"

#line 57 "cocx.mod"

#line 60 "cocx.mod"

#line 60 "cocx.mod"

#line 60 "cocx.mod"
extern void pOt_InSfx_COCX()
#line 60 "cocx.mod"
{
#line 60 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 60 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 60 "cocx.mod"

#line 60 "cocx.mod"
  pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x50L],&pOt__str_td[0x2]))));

#line 61 "cocx.mod"
pOt__Epilogue:;
#line 61 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 61 "cocx.mod"
}
#line 61 "cocx.mod"

#line 61 "cocx.mod"

#line 65 "cocx.mod"
struct pOt__tag_0_COCX {
#line 65 "cocx.mod"
  pOt__ArrTypDsc *td;
#line 65 "cocx.mod"
  pOt_CHAR arr[0x9L];
#line 65 "cocx.mod"
} ;
#line 65 "cocx.mod"
static pOt__ArrTypDsc pOt__td_0_COCX= {
#line 65 "cocx.mod"
  1,
#line 65 "cocx.mod"
  0x9L, sizeof(pOt_CHAR)
#line 65 "cocx.mod"
};
#line 65 "cocx.mod"

#line 65 "cocx.mod"

#line 65 "cocx.mod"
extern void pOt_TypTest_COCX
#line 65 "cocx.mod"
#if pOt__ANSI_C
#line 65 "cocx.mod"
  (struct pOt__tag_3_COCT *pOt_x, struct pOt__tag_3_COCT *pOt_y)
#line 65 "cocx.mod"
#else
#line 65 "cocx.mod"
  (pOt_x, pOt_y)
#line 65 "cocx.mod"
  struct pOt__tag_3_COCT *pOt_x, *pOt_y;
#line 65 "cocx.mod"

#line 65 "cocx.mod"
#endif
#line 65 "cocx.mod"
{
#line 65 "cocx.mod"
  pOt_INTEGER pOt_np;
#line 65 "cocx.mod"
  struct pOt__tag_0_COCX pOt_s;
#line 65 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 65 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 65 "cocx.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_s,(pOt__TypDsc*)&pOt__td_0_COCX);
#line 65 "cocx.mod"

#line 65 "cocx.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xD4L],&pOt__str_td[0x1F]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
  if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_form==17)) {
#line 66 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xF8L],&pOt__str_td[0x1]))),(pOt_INTEGER)(pOt_np),&pOt_np);
#line 66 "cocx.mod"
  }
#line 66 "cocx.mod"
  pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x100L],&pOt__str_td[0x13]))));
#line 68 "cocx.mod"
  if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_y).pOt_typ))).pOt_form==17)) {
#line 68 "cocx.mod"
    pOt_CTDName_COCN((struct pOt__tag_2_COCT*)((*pOt_y).pOt_typ),(pOt_INTEGER)(pOt_cslen_COCQ),&pOt_np);
  } else {
#line 69 "cocx.mod"
    pOt_CTDName_COCN((struct pOt__tag_2_COCT*)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_y).pOt_typ))).pOt_BaseTyp),(pOt_INTEGER)(pOt_cslen_COCQ),&pOt_np);
  }
#line 70 "cocx.mod"
  pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x118L],&pOt__str_td[0x3]))));
#line 72 "cocx.mod"
  if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_y).pOt_typ))).pOt_form==17)) {
#line 72 "cocx.mod"
    pOt_FromLInt_Strings((pOt_LONGINT)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_y).pOt_typ))).pOt_n),16,(pOt__ArrTypDsc**)&pOt_s);
  } else {
#line 73 "cocx.mod"
    pOt_FromLInt_Strings((pOt_LONGINT)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_y).pOt_typ))).pOt_BaseTyp))).pOt_n),16,(pOt__ArrTypDsc**)&pOt_s);
  }
#line 74 "cocx.mod"
  pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&pOt_s));
  pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x120L],&pOt__str_td[0x2]))));

#line 76 "cocx.mod"
pOt__Epilogue:;
#line 76 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 76 "cocx.mod"
}
#line 76 "cocx.mod"

#line 76 "cocx.mod"

#line 80 "cocx.mod"

#line 80 "cocx.mod"

#line 80 "cocx.mod"
extern void pOt_MOp_COCX
#line 80 "cocx.mod"
#if pOt__ANSI_C
#line 80 "cocx.mod"
  (pOt_INTEGER pOt_op, struct pOt__tag_3_COCT *pOt_x, pOt_BOOLEAN pOt_rngchk)
#line 80 "cocx.mod"
#else
#line 80 "cocx.mod"
  (pOt_op, pOt_x, pOt_rngchk)
#line 80 "cocx.mod"
  pOt_INTEGER pOt_op;
#line 80 "cocx.mod"
  struct pOt__tag_3_COCT *pOt_x;
#line 80 "cocx.mod"
  pOt_BOOLEAN pOt_rngchk;
#line 80 "cocx.mod"

#line 80 "cocx.mod"
#endif
#line 80 "cocx.mod"
{
#line 80 "cocx.mod"
  pOt_INTEGER pOt_np, pOt_f;
#line 80 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 80 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 80 "cocx.mod"

#line 80 "cocx.mod"
  pOt_f=(pOt_INTEGER)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_form);
  switch(pOt_op) {
  case 6:
#line 82 "cocx.mod"
  break;
  case 7:
#line 83 "cocx.mod"
    if(((unsigned long)0!=((unsigned long)1<<pOt__rngchk_se(__FILE__,__LINE__, pOt_f)&(pOt_SET)0x1F0L))) {
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x128L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
    } else if(( pOt_f==((pOt_INTEGER)(9)))) {
#line 85 "cocx.mod"
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x130L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
#line 87 "cocx.mod"
    }
#line 87 "cocx.mod"
  break;
#line 87 "cocx.mod"
  case 32:
#line 87 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x138L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
#line 89 "cocx.mod"
  break;
#line 89 "cocx.mod"
  default:;
#line 89 "cocx.mod"
    pOt__halt(__FILE__,__LINE__,0x10);
#line 89 "cocx.mod"
  }
#line 89 "cocx.mod"

#line 89 "cocx.mod"
pOt__Epilogue:;
#line 89 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 89 "cocx.mod"
}
#line 89 "cocx.mod"

#line 89 "cocx.mod"

#line 94 "cocx.mod"
struct pOt__tag_1_COCX {
#line 94 "cocx.mod"
  pOt__ArrTypDsc *td;
#line 94 "cocx.mod"
  pOt_CHAR arr[0x4L];
#line 94 "cocx.mod"
} ;
#line 94 "cocx.mod"
static pOt__ArrTypDsc pOt__td_1_COCX= {
#line 94 "cocx.mod"
  1,
#line 94 "cocx.mod"
  0x4L, sizeof(pOt_CHAR)
#line 94 "cocx.mod"
};
#line 94 "cocx.mod"

#line 94 "cocx.mod"
static pOt_INTEGER (*pOt_op_NumOp_COCX);
#line 94 "cocx.mod"
static pOt_SET (*pOt_convert_NumOp_COCX);
#line 94 "cocx.mod"
static struct pOt__tag_3_COCT *pOt_x_NumOp_COCX, *pOt_y_NumOp_COCX;
#line 94 "cocx.mod"
static pOt_BOOLEAN (*pOt_rngchk_NumOp_COCX);
#line 94 "cocx.mod"
static pOt_INTEGER (*pOt_np_NumOp_COCX);
#line 94 "cocx.mod"
static struct pOt__tag_1_COCX (*pOt_s_NumOp_COCX);
#line 94 "cocx.mod"

#line 94 "cocx.mod"
extern void pOt_NumOp_COCX pOt__ARGS((pOt_INTEGER , pOt_SET , struct pOt__tag_3_COCT *, struct pOt__tag_3_COCT *, pOt_BOOLEAN ));
#line 94 "cocx.mod"

#line 94 "cocx.mod"


#line 95 "cocx.mod"

#line 95 "cocx.mod"
static void pOt_CastX_NumOp_COCX()
#line 95 "cocx.mod"
{
#line 95 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 95 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 95 "cocx.mod"

#line 95 "cocx.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x50L],&pOt__str_td[0x2]))),(pOt_INTEGER)((*pOt_y_NumOp_COCX).pOt_qoffs),&(*pOt_np_NumOp_COCX));
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x140L],&pOt__str_td[0x2]))),(pOt_INTEGER)((*pOt_x_NumOp_COCX).pOt_qoffs),&(*pOt_np_NumOp_COCX));
  pOt_CTDenoter_COCN((struct pOt__tag_2_COCT*)((*pOt_x_NumOp_COCX).pOt_typ),(pOt_INTEGER)((*pOt_np_NumOp_COCX)),&(*pOt_np_NumOp_COCX));
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x148L],&pOt__str_td[0x2]))),(pOt_INTEGER)((*pOt_np_NumOp_COCX)),&(*pOt_np_NumOp_COCX));
#line 100 "cocx.mod"

#line 100 "cocx.mod"
pOt__Epilogue:;
#line 100 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 100 "cocx.mod"
}
#line 100 "cocx.mod"

#line 100 "cocx.mod"
extern void pOt_NumOp_COCX
#line 103 "cocx.mod"
#if pOt__ANSI_C
#line 103 "cocx.mod"
  (pOt_INTEGER pOt_op, pOt_SET pOt_convert, struct pOt__tag_3_COCT *pOt_x, struct pOt__tag_3_COCT *pOt_y, pOt_BOOLEAN pOt_rngchk)
#line 103 "cocx.mod"
#else
#line 103 "cocx.mod"
  (pOt_op, pOt_convert, pOt_x, pOt_y, pOt_rngchk)
#line 103 "cocx.mod"
  pOt_INTEGER pOt_op;
#line 103 "cocx.mod"
  pOt_SET pOt_convert;
#line 103 "cocx.mod"
  struct pOt__tag_3_COCT *pOt_x, *pOt_y;
#line 103 "cocx.mod"
  pOt_BOOLEAN pOt_rngchk;
#line 103 "cocx.mod"

#line 103 "cocx.mod"
#endif
#line 103 "cocx.mod"
{
#line 103 "cocx.mod"
  pOt_INTEGER (*pOt_op_);
#line 103 "cocx.mod"
  pOt_SET (*pOt_convert_);
#line 103 "cocx.mod"
  struct pOt__tag_3_COCT *pOt_x_, *pOt_y_;
#line 103 "cocx.mod"
  pOt_BOOLEAN (*pOt_rngchk_);
#line 103 "cocx.mod"
  pOt_INTEGER pOt_np, (*pOt_np_);
#line 103 "cocx.mod"
  struct pOt__tag_1_COCX pOt_s, (*pOt_s_);
#line 103 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 103 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 103 "cocx.mod"
  pOt_op_=pOt_op_NumOp_COCX;
#line 103 "cocx.mod"
  pOt_op_NumOp_COCX=&pOt_op;
#line 103 "cocx.mod"
  pOt_convert_=pOt_convert_NumOp_COCX;
#line 103 "cocx.mod"
  pOt_convert_NumOp_COCX=&pOt_convert;
#line 103 "cocx.mod"
  pOt_x_=pOt_x_NumOp_COCX;
#line 103 "cocx.mod"
  pOt_x_NumOp_COCX=pOt_x;
#line 103 "cocx.mod"
  pOt_y_=pOt_y_NumOp_COCX;
#line 103 "cocx.mod"
  pOt_y_NumOp_COCX=pOt_y;
#line 103 "cocx.mod"
  pOt_rngchk_=pOt_rngchk_NumOp_COCX;
#line 103 "cocx.mod"
  pOt_rngchk_NumOp_COCX=&pOt_rngchk;
#line 103 "cocx.mod"
  pOt_np_=pOt_np_NumOp_COCX;
#line 103 "cocx.mod"
  pOt_np_NumOp_COCX=&pOt_np;
#line 103 "cocx.mod"
  pOt_s_=pOt_s_NumOp_COCX;
#line 103 "cocx.mod"
  pOt_s_NumOp_COCX=&pOt_s;
#line 103 "cocx.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_s,(pOt__TypDsc*)&pOt__td_1_COCX);
#line 103 "cocx.mod"

#line 103 "cocx.mod"
  if(((pOt_rngchk&&(((unsigned long)0!=((unsigned long)1<<pOt__rngchk_se(__FILE__,__LINE__,(*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_form)&(pOt_SET)0x70L))))&&((pOt_op!=((pOt_INTEGER)(2)))))) {
    pOt_FromLInt_Strings((pOt_LONGINT)((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_form),10,(pOt__ArrTypDsc**)&pOt_s);
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x150L],&pOt__str_td[0x2]))));
#line 105 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&pOt_s));
#line 105 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x8L],&pOt__str_td[0x1]))));
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x158L],&pOt__str_td[0x10]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x170L],&pOt__str_td[0x24]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
    switch(pOt_op) {
#line 108 "cocx.mod"
    case 1:
#line 108 "cocx.mod"
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x19CL],&pOt__str_td[0x3]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
    break;
#line 109 "cocx.mod"
    case 3:
#line 109 "cocx.mod"
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1A4L],&pOt__str_td[0x3]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
    break;
#line 110 "cocx.mod"
    case 4:
#line 110 "cocx.mod"
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1ACL],&pOt__str_td[0x3]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
    break;
#line 111 "cocx.mod"
    case 6:
#line 111 "cocx.mod"
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1B4L],&pOt__str_td[0x3]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
    break;
#line 112 "cocx.mod"
    case 7:
#line 112 "cocx.mod"
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1BCL],&pOt__str_td[0x3]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
    break;
#line 113 "cocx.mod"
    default:;
#line 113 "cocx.mod"
      pOt__halt(__FILE__,__LINE__,0x10);
#line 113 "cocx.mod"
    }
#line 113 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
#line 115 "cocx.mod"
    pOt_CTDenoter_COCN((struct pOt__tag_2_COCT*)((*pOt_x).pOt_typ),(pOt_INTEGER)(pOt_np),&pOt_np);
#line 115 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1C4L],&pOt__str_td[0x6]))),(pOt_INTEGER)(pOt_np),&pOt_np);
#line 118 "cocx.mod"
  } else {
#line 118 "cocx.mod"
    if(((unsigned long)0!=((unsigned long)1<<( 1)&pOt_convert))) {
#line 118 "cocx.mod"
      pOt_Cast_COCJ((struct pOt__tag_3_COCT*)&(*pOt_y));
#line 118 "cocx.mod"
    }
#line 118 "cocx.mod"
    switch(pOt_op) {
    case 1:
#line 119 "cocx.mod"
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1D0L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
#line 121 "cocx.mod"
      if(((unsigned long)0!=((unsigned long)1<<( 0)&pOt_convert))) {
#line 121 "cocx.mod"
        pOt_CastX_NumOp_COCX();
      }
#line 122 "cocx.mod"
    break;
#line 122 "cocx.mod"
    case 2:
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1D8L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
      if(((unsigned long)0!=((unsigned long)1<<( 0)&pOt_convert))) {
#line 124 "cocx.mod"
        pOt_CastX_NumOp_COCX();
      }
#line 125 "cocx.mod"
    break;
#line 125 "cocx.mod"
    case 3:
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1E0L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
#line 126 "cocx.mod"
      pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x8L],&pOt__str_td[0x1]))));
      if(((unsigned long)0!=((unsigned long)1<<( 0)&pOt_convert))) {
#line 127 "cocx.mod"
        pOt_CastX_NumOp_COCX();
#line 127 "cocx.mod"
      }
#line 127 "cocx.mod"
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
#line 129 "cocx.mod"
      pOt_CTDenoter_COCN((struct pOt__tag_2_COCT*)((*pOt_x).pOt_typ),(pOt_INTEGER)(pOt_np),&pOt_np);
#line 129 "cocx.mod"
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1E8L],&pOt__str_td[0xA]))),(pOt_INTEGER)(pOt_np),&pOt_np);
#line 131 "cocx.mod"
    break;
#line 131 "cocx.mod"
    case 4:
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1E0L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
#line 132 "cocx.mod"
      pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x8L],&pOt__str_td[0x1]))));
      if(((unsigned long)0!=((unsigned long)1<<( 0)&pOt_convert))) {
#line 133 "cocx.mod"
        pOt_CastX_NumOp_COCX();
#line 133 "cocx.mod"
      }
#line 133 "cocx.mod"
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
#line 135 "cocx.mod"
      pOt_CTDenoter_COCN((struct pOt__tag_2_COCT*)((*pOt_x).pOt_typ),(pOt_INTEGER)(pOt_np),&pOt_np);
#line 135 "cocx.mod"
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1F8L],&pOt__str_td[0xA]))),(pOt_INTEGER)(pOt_np),&pOt_np);
#line 137 "cocx.mod"
    break;
#line 137 "cocx.mod"
    case 6:
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x208L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
      if(((unsigned long)0!=((unsigned long)1<<( 0)&pOt_convert))) {
#line 139 "cocx.mod"
        pOt_CastX_NumOp_COCX();
      }
#line 140 "cocx.mod"
    break;
#line 140 "cocx.mod"
    case 7:
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x128L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
      if(((unsigned long)0!=((unsigned long)1<<( 0)&pOt_convert))) {
#line 142 "cocx.mod"
        pOt_CastX_NumOp_COCX();
      }
#line 143 "cocx.mod"
    break;
    default:;
#line 144 "cocx.mod"
      pOt__halt(__FILE__,__LINE__,0x10);
#line 144 "cocx.mod"
    }
#line 144 "cocx.mod"
  }

#line 145 "cocx.mod"
pOt__Epilogue:;
#line 145 "cocx.mod"
  pOt_op_NumOp_COCX=pOt_op_;
#line 145 "cocx.mod"
  pOt_convert_NumOp_COCX=pOt_convert_;
#line 145 "cocx.mod"
  pOt_x_NumOp_COCX=pOt_x_;
#line 145 "cocx.mod"
  pOt_y_NumOp_COCX=pOt_y_;
#line 145 "cocx.mod"
  pOt_rngchk_NumOp_COCX=pOt_rngchk_;
#line 145 "cocx.mod"
  pOt_np_NumOp_COCX=pOt_np_;
#line 145 "cocx.mod"
  pOt_s_NumOp_COCX=pOt_s_;
#line 145 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 145 "cocx.mod"
}
#line 145 "cocx.mod"

#line 145 "cocx.mod"

#line 150 "cocx.mod"

#line 150 "cocx.mod"

#line 150 "cocx.mod"
extern void pOt_SetOp_COCX
#line 150 "cocx.mod"
#if pOt__ANSI_C
#line 150 "cocx.mod"
  (pOt_INTEGER pOt_op, struct pOt__tag_3_COCT *pOt_x, struct pOt__tag_3_COCT *pOt_y)
#line 150 "cocx.mod"
#else
#line 150 "cocx.mod"
  (pOt_op, pOt_x, pOt_y)
#line 150 "cocx.mod"
  pOt_INTEGER pOt_op;
#line 150 "cocx.mod"
  struct pOt__tag_3_COCT *pOt_x, *pOt_y;
#line 150 "cocx.mod"

#line 150 "cocx.mod"
#endif
#line 150 "cocx.mod"
{
#line 150 "cocx.mod"
  pOt_INTEGER pOt_np;
#line 150 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 150 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 150 "cocx.mod"

#line 150 "cocx.mod"
  switch(pOt_op) {
  case 1:
#line 151 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xF8L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
  break;
#line 152 "cocx.mod"
  case 2:
#line 152 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x210L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
  break;
#line 153 "cocx.mod"
  case 6:
#line 153 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x218L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
  break;
#line 154 "cocx.mod"
  case 7:
#line 154 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x220L],&pOt__str_td[0x2]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
  break;
#line 155 "cocx.mod"
  default:;
#line 155 "cocx.mod"
    pOt__halt(__FILE__,__LINE__,0x10);
#line 155 "cocx.mod"
  }
#line 155 "cocx.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
  pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x8L],&pOt__str_td[0x1]))));

#line 157 "cocx.mod"
pOt__Epilogue:;
#line 157 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 157 "cocx.mod"
}
#line 157 "cocx.mod"

#line 157 "cocx.mod"

#line 162 "cocx.mod"

#line 162 "cocx.mod"

#line 162 "cocx.mod"
extern void pOt_BoolOp_COCX
#line 162 "cocx.mod"
#if pOt__ANSI_C
#line 162 "cocx.mod"
  (pOt_INTEGER pOt_op, struct pOt__tag_3_COCT *pOt_x, struct pOt__tag_3_COCT *pOt_y)
#line 162 "cocx.mod"
#else
#line 162 "cocx.mod"
  (pOt_op, pOt_x, pOt_y)
#line 162 "cocx.mod"
  pOt_INTEGER pOt_op;
#line 162 "cocx.mod"
  struct pOt__tag_3_COCT *pOt_x, *pOt_y;
#line 162 "cocx.mod"

#line 162 "cocx.mod"
#endif
#line 162 "cocx.mod"
{
#line 162 "cocx.mod"
  pOt_INTEGER pOt_np;
#line 162 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 162 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 162 "cocx.mod"

#line 162 "cocx.mod"
  switch(pOt_op) {
  case 5:
#line 163 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x228L],&pOt__str_td[0x2]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
  break;
#line 164 "cocx.mod"
  case 8:
#line 164 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x230L],&pOt__str_td[0x2]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
  break;
#line 165 "cocx.mod"
  default:;
#line 165 "cocx.mod"
    pOt__halt(__FILE__,__LINE__,0x10);
#line 165 "cocx.mod"
  }
#line 165 "cocx.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
  pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x8L],&pOt__str_td[0x1]))));

#line 167 "cocx.mod"
pOt__Epilogue:;
#line 167 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 167 "cocx.mod"
}
#line 167 "cocx.mod"

#line 167 "cocx.mod"

#line 172 "cocx.mod"

#line 172 "cocx.mod"
static pOt_INTEGER (*pOt_op_NumRel_COCX);
#line 172 "cocx.mod"
static pOt_SET (*pOt_convert_NumRel_COCX);
#line 172 "cocx.mod"
static struct pOt__tag_3_COCT *pOt_x_NumRel_COCX, *pOt_y_NumRel_COCX;
#line 172 "cocx.mod"
static pOt_INTEGER (*pOt_np_NumRel_COCX);
#line 172 "cocx.mod"

#line 172 "cocx.mod"
extern void pOt_NumRel_COCX pOt__ARGS((pOt_INTEGER , pOt_SET , struct pOt__tag_3_COCT *, struct pOt__tag_3_COCT *));
#line 172 "cocx.mod"

#line 172 "cocx.mod"


#line 173 "cocx.mod"

#line 173 "cocx.mod"
static void pOt_CastX_NumRel_COCX()
#line 173 "cocx.mod"
{
#line 173 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 173 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 173 "cocx.mod"

#line 173 "cocx.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x50L],&pOt__str_td[0x2]))),(pOt_INTEGER)((*pOt_y_NumRel_COCX).pOt_qoffs),&(*pOt_np_NumRel_COCX));
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x140L],&pOt__str_td[0x2]))),(pOt_INTEGER)((*pOt_x_NumRel_COCX).pOt_qoffs),&(*pOt_np_NumRel_COCX));
  pOt_CTDenoter_COCN((struct pOt__tag_2_COCT*)((*pOt_x_NumRel_COCX).pOt_typ),(pOt_INTEGER)((*pOt_np_NumRel_COCX)),&(*pOt_np_NumRel_COCX));
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x148L],&pOt__str_td[0x2]))),(pOt_INTEGER)((*pOt_np_NumRel_COCX)),&(*pOt_np_NumRel_COCX));
#line 178 "cocx.mod"

#line 178 "cocx.mod"
pOt__Epilogue:;
#line 178 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 178 "cocx.mod"
}
#line 178 "cocx.mod"

#line 178 "cocx.mod"
extern void pOt_NumRel_COCX
#line 181 "cocx.mod"
#if pOt__ANSI_C
#line 181 "cocx.mod"
  (pOt_INTEGER pOt_op, pOt_SET pOt_convert, struct pOt__tag_3_COCT *pOt_x, struct pOt__tag_3_COCT *pOt_y)
#line 181 "cocx.mod"
#else
#line 181 "cocx.mod"
  (pOt_op, pOt_convert, pOt_x, pOt_y)
#line 181 "cocx.mod"
  pOt_INTEGER pOt_op;
#line 181 "cocx.mod"
  pOt_SET pOt_convert;
#line 181 "cocx.mod"
  struct pOt__tag_3_COCT *pOt_x, *pOt_y;
#line 181 "cocx.mod"

#line 181 "cocx.mod"
#endif
#line 181 "cocx.mod"
{
#line 181 "cocx.mod"
  pOt_INTEGER (*pOt_op_);
#line 181 "cocx.mod"
  pOt_SET (*pOt_convert_);
#line 181 "cocx.mod"
  struct pOt__tag_3_COCT *pOt_x_, *pOt_y_;
#line 181 "cocx.mod"
  pOt_INTEGER pOt_np, (*pOt_np_);
#line 181 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 181 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 181 "cocx.mod"
  pOt_op_=pOt_op_NumRel_COCX;
#line 181 "cocx.mod"
  pOt_op_NumRel_COCX=&pOt_op;
#line 181 "cocx.mod"
  pOt_convert_=pOt_convert_NumRel_COCX;
#line 181 "cocx.mod"
  pOt_convert_NumRel_COCX=&pOt_convert;
#line 181 "cocx.mod"
  pOt_x_=pOt_x_NumRel_COCX;
#line 181 "cocx.mod"
  pOt_x_NumRel_COCX=pOt_x;
#line 181 "cocx.mod"
  pOt_y_=pOt_y_NumRel_COCX;
#line 181 "cocx.mod"
  pOt_y_NumRel_COCX=pOt_y;
#line 181 "cocx.mod"
  pOt_np_=pOt_np_NumRel_COCX;
#line 181 "cocx.mod"
  pOt_np_NumRel_COCX=&pOt_np;
#line 181 "cocx.mod"

#line 181 "cocx.mod"
  if(((unsigned long)0!=((unsigned long)1<<( 1)&pOt_convert))) {
#line 181 "cocx.mod"
    pOt_Cast_COCJ((struct pOt__tag_3_COCT*)&(*pOt_y));
#line 181 "cocx.mod"
  }
#line 181 "cocx.mod"
  switch(pOt_op) {
#line 183 "cocx.mod"
  case 9:
#line 183 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x238L],&pOt__str_td[0x2]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
  break;
#line 184 "cocx.mod"
  case 10:
#line 184 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x240L],&pOt__str_td[0x2]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
  break;
#line 185 "cocx.mod"
  case 11:
#line 185 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x248L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
  break;
#line 186 "cocx.mod"
  case 12:
#line 186 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x250L],&pOt__str_td[0x2]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
  break;
#line 187 "cocx.mod"
  case 13:
#line 187 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x258L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
  break;
#line 188 "cocx.mod"
  case 14:
#line 188 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x260L],&pOt__str_td[0x2]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
  break;
#line 189 "cocx.mod"
  default:;
#line 189 "cocx.mod"
    pOt__halt(__FILE__,__LINE__,0x10);
#line 189 "cocx.mod"
  }
#line 189 "cocx.mod"
  if(((unsigned long)0!=((unsigned long)1<<( 0)&pOt_convert))) {
    pOt_CastX_NumRel_COCX();
#line 190 "cocx.mod"
  }
#line 190 "cocx.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
  pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x8L],&pOt__str_td[0x1]))));

#line 192 "cocx.mod"
pOt__Epilogue:;
#line 192 "cocx.mod"
  pOt_op_NumRel_COCX=pOt_op_;
#line 192 "cocx.mod"
  pOt_convert_NumRel_COCX=pOt_convert_;
#line 192 "cocx.mod"
  pOt_x_NumRel_COCX=pOt_x_;
#line 192 "cocx.mod"
  pOt_y_NumRel_COCX=pOt_y_;
#line 192 "cocx.mod"
  pOt_np_NumRel_COCX=pOt_np_;
#line 192 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 192 "cocx.mod"
}
#line 192 "cocx.mod"

#line 192 "cocx.mod"

#line 197 "cocx.mod"
struct pOt__tag_2_COCX {
#line 197 "cocx.mod"
  pOt__ArrTypDsc *td;
#line 197 "cocx.mod"
  pOt_CHAR arr[0x9L];
#line 197 "cocx.mod"
} ;
#line 197 "cocx.mod"
static pOt__ArrTypDsc pOt__td_2_COCX= {
#line 197 "cocx.mod"
  1,
#line 197 "cocx.mod"
  0x9L, sizeof(pOt_CHAR)
#line 197 "cocx.mod"
};
#line 197 "cocx.mod"

#line 197 "cocx.mod"

#line 197 "cocx.mod"
extern void pOt_StrRel_COCX
#line 197 "cocx.mod"
#if pOt__ANSI_C
#line 197 "cocx.mod"
  (pOt_INTEGER pOt_op, struct pOt__tag_3_COCT *pOt_x, struct pOt__tag_3_COCT *pOt_y)
#line 197 "cocx.mod"
#else
#line 197 "cocx.mod"
  (pOt_op, pOt_x, pOt_y)
#line 197 "cocx.mod"
  pOt_INTEGER pOt_op;
#line 197 "cocx.mod"
  struct pOt__tag_3_COCT *pOt_x, *pOt_y;
#line 197 "cocx.mod"

#line 197 "cocx.mod"
#endif
#line 197 "cocx.mod"
{
#line 197 "cocx.mod"
  pOt_INTEGER pOt_np;
#line 197 "cocx.mod"
  struct pOt__tag_2_COCX pOt_s;
#line 197 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 197 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 197 "cocx.mod"
  pOt__init_var((pOt__TypDsc**)&pOt_s,(pOt__TypDsc*)&pOt__td_2_COCX);
#line 197 "cocx.mod"

#line 197 "cocx.mod"
  pOt_s.arr[pOt__inxchk(__FILE__,__LINE__,0x9, 0)]='s';
#line 197 "cocx.mod"
  pOt_s.arr[pOt__inxchk(__FILE__,__LINE__,0x9, 1)]='s';
#line 197 "cocx.mod"
  pOt_s.arr[pOt__inxchk(__FILE__,__LINE__,0x9, 2)]='\0';
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1E0L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
  if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_y).pOt_typ))).pOt_form==3)) {
#line 199 "cocx.mod"
    pOt_s.arr[pOt__inxchk(__FILE__,__LINE__,0x9, 1)]='c';
#line 201 "cocx.mod"
  } else {
#line 201 "cocx.mod"
    if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_y).pOt_typ))).pOt_form!=10)) {
#line 201 "cocx.mod"
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x268L],&pOt__str_td[0xC]))),(pOt_INTEGER)(pOt_np),&pOt_np);
#line 201 "cocx.mod"
    }
#line 201 "cocx.mod"
    if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_form==3)) {
      pOt_s.arr[pOt__inxchk(__FILE__,__LINE__,0x9, 0)]='c';
    } else if(( (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_form!=10)) {
#line 203 "cocx.mod"
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x268L],&pOt__str_td[0xC]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
#line 205 "cocx.mod"
    }
#line 205 "cocx.mod"
  }
#line 205 "cocx.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x27CL],&pOt__str_td[0x8]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
#line 207 "cocx.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&pOt_s),(pOt_INTEGER)(pOt_np),&pOt_np);
#line 207 "cocx.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x1]))),(pOt_INTEGER)(pOt_np),&pOt_np);
  pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x118L],&pOt__str_td[0x3]))));
#line 208 "cocx.mod"
  pOt_FromLInt_Strings((pOt_LONGINT)((pOt_INTEGER)(pOt_op)),16,(pOt__ArrTypDsc**)&pOt_s);
  pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&pOt_s));
#line 209 "cocx.mod"
  pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x8L],&pOt__str_td[0x1]))));

#line 210 "cocx.mod"
pOt__Epilogue:;
#line 210 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 210 "cocx.mod"
}
#line 210 "cocx.mod"

#line 210 "cocx.mod"

#line 215 "cocx.mod"

#line 215 "cocx.mod"

#line 215 "cocx.mod"
extern void pOt_CharRel_COCX
#line 215 "cocx.mod"
#if pOt__ANSI_C
#line 215 "cocx.mod"
  (pOt_INTEGER pOt_op, struct pOt__tag_3_COCT *pOt_x, struct pOt__tag_3_COCT *pOt_y)
#line 215 "cocx.mod"
#else
#line 215 "cocx.mod"
  (pOt_op, pOt_x, pOt_y)
#line 215 "cocx.mod"
  pOt_INTEGER pOt_op;
#line 215 "cocx.mod"
  struct pOt__tag_3_COCT *pOt_x, *pOt_y;
#line 215 "cocx.mod"

#line 215 "cocx.mod"
#endif
#line 215 "cocx.mod"
{
#line 215 "cocx.mod"
  pOt_INTEGER pOt_np;
#line 215 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 215 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 215 "cocx.mod"

#line 215 "cocx.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x28CL],&pOt__str_td[0xF]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
  switch(pOt_op) {
  case 9:
#line 217 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x238L],&pOt__str_td[0x2]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
  break;
#line 218 "cocx.mod"
  case 10:
#line 218 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x240L],&pOt__str_td[0x2]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
  break;
#line 219 "cocx.mod"
  case 11:
#line 219 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x248L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
  break;
#line 220 "cocx.mod"
  case 12:
#line 220 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x250L],&pOt__str_td[0x2]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
  break;
#line 221 "cocx.mod"
  case 13:
#line 221 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x258L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
  break;
#line 222 "cocx.mod"
  case 14:
#line 222 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x260L],&pOt__str_td[0x2]))),(pOt_INTEGER)((*pOt_y).pOt_qoffs),&pOt_np);
  break;
#line 223 "cocx.mod"
  default:;
#line 223 "cocx.mod"
    pOt__halt(__FILE__,__LINE__,0x10);
#line 223 "cocx.mod"
  }
#line 223 "cocx.mod"
  pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x2A0L],&pOt__str_td[0x10]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
  pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x8L],&pOt__str_td[0x1]))));

#line 225 "cocx.mod"
pOt__Epilogue:;
#line 225 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 225 "cocx.mod"
}
#line 225 "cocx.mod"

#line 225 "cocx.mod"

#line 229 "cocx.mod"

#line 229 "cocx.mod"

#line 229 "cocx.mod"
extern void pOt_StProcPfx_COCX
#line 229 "cocx.mod"
#if pOt__ANSI_C
#line 229 "cocx.mod"
  (pOt_INTEGER pOt_fctno, pOt_BOOLEAN pOt_rngchk)
#line 229 "cocx.mod"
#else
#line 229 "cocx.mod"
  (pOt_fctno, pOt_rngchk)
#line 229 "cocx.mod"
  pOt_INTEGER pOt_fctno;
#line 229 "cocx.mod"
  pOt_BOOLEAN pOt_rngchk;
#line 229 "cocx.mod"

#line 229 "cocx.mod"
#endif
#line 229 "cocx.mod"
{
#line 229 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 229 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 229 "cocx.mod"

#line 229 "cocx.mod"
  switch(pOt_fctno) {
#line 229 "cocx.mod"
  case 0:
#line 229 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x2B8L],&pOt__str_td[0x1C]))));
  break;
#line 230 "cocx.mod"
  case 1:
#line 230 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x2DCL],&pOt__str_td[0x2C]))));
  break;
#line 231 "cocx.mod"
  case 2:
#line 231 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x1]))));
  break;
#line 232 "cocx.mod"
  case 3:
  break;
#line 233 "cocx.mod"
  case 4:
#line 233 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x310L],&pOt__str_td[0x18]))));
  break;
#line 234 "cocx.mod"
  case 5:
#line 234 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x330L],&pOt__str_td[0x1D]))));
  break;
#line 235 "cocx.mod"
  case 6:
#line 235 "cocx.mod"
    if(pOt_rngchk) {
      pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x354L],&pOt__str_td[0x21]))));
    } else {
#line 237 "cocx.mod"
      pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x37CL],&pOt__str_td[0xC]))));
#line 239 "cocx.mod"
    }
#line 239 "cocx.mod"
  break;
#line 239 "cocx.mod"
  case 7:
#line 239 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x390L],&pOt__str_td[0x15]))));
  break;
#line 240 "cocx.mod"
  case 8:
#line 240 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x3ACL],&pOt__str_td[0x13]))));
  break;
#line 241 "cocx.mod"
  case 9:
#line 241 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x3C4L],&pOt__str_td[0xF]))));
  break;
#line 242 "cocx.mod"
  case 10:
#line 242 "cocx.mod"
  case 11:
#line 242 "cocx.mod"
  break;
  case 12:
#line 243 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x3D8L],&pOt__str_td[0xA]))));
    if(pOt_rngchk) {
#line 244 "cocx.mod"
      pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x3E8L],&pOt__str_td[0x21]))));
#line 244 "cocx.mod"
    }
#line 244 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x410L],&pOt__str_td[0x10]))));
#line 246 "cocx.mod"
  break;
#line 246 "cocx.mod"
  case 13:
#line 246 "cocx.mod"
  case 14:
#line 246 "cocx.mod"
  break;
  case 15:
#line 247 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x1]))));
  break;
#line 248 "cocx.mod"
  case 16:
#line 248 "cocx.mod"
  case 17:
#line 248 "cocx.mod"
  case 18:
#line 248 "cocx.mod"
  case 19:
  break;
#line 249 "cocx.mod"
  case 20:
#line 249 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x428L],&pOt__str_td[0x16]))));
  break;
#line 250 "cocx.mod"
  case 21:
#line 250 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x444L],&pOt__str_td[0x9]))));
  break;
#line 251 "cocx.mod"
  case 22:
#line 251 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x454L],&pOt__str_td[0x9]))));
  break;
#line 252 "cocx.mod"
  case 23:
#line 252 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x464L],&pOt__str_td[0x9]))));
  break;
#line 253 "cocx.mod"
  case 24:
#line 253 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x474L],&pOt__str_td[0x1B]))));
  break;
#line 254 "cocx.mod"
  case 25:
#line 254 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x494L],&pOt__str_td[0x1B]))));
  break;
#line 255 "cocx.mod"
  case 26:
#line 255 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x4B4L],&pOt__str_td[0x16]))));
  break;
#line 256 "cocx.mod"
  case 27:
#line 256 "cocx.mod"
  break;
  case 28:
  break;
#line 258 "cocx.mod"
  case 29:
    if(pOt_rngchk) {
#line 259 "cocx.mod"
      pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x4D0L],&pOt__str_td[0x2B]))));
    } else {
#line 260 "cocx.mod"
      pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x500L],&pOt__str_td[0x16]))));
#line 262 "cocx.mod"
    }
#line 262 "cocx.mod"
  break;
#line 262 "cocx.mod"
  case 30:
#line 262 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x51CL],&pOt__str_td[0x1D]))));
#line 264 "cocx.mod"
  break;
#line 264 "cocx.mod"
  default:;
#line 264 "cocx.mod"
    pOt__halt(__FILE__,__LINE__,0x10);
#line 264 "cocx.mod"
  }
#line 264 "cocx.mod"

#line 264 "cocx.mod"
pOt__Epilogue:;
#line 264 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 264 "cocx.mod"
}
#line 264 "cocx.mod"

#line 264 "cocx.mod"

#line 269 "cocx.mod"

#line 269 "cocx.mod"

#line 269 "cocx.mod"
extern void pOt_StPar1Sfx_COCX
#line 269 "cocx.mod"
#if pOt__ANSI_C
#line 269 "cocx.mod"
  (struct pOt__tag_3_COCT *pOt_x, pOt_INTEGER pOt_fctno, pOt_BOOLEAN pOt_rngchk)
#line 269 "cocx.mod"
#else
#line 269 "cocx.mod"
  (pOt_x, pOt_fctno, pOt_rngchk)
#line 269 "cocx.mod"
  struct pOt__tag_3_COCT *pOt_x;
#line 269 "cocx.mod"
  pOt_INTEGER pOt_fctno;
#line 269 "cocx.mod"
  pOt_BOOLEAN pOt_rngchk;
#line 269 "cocx.mod"

#line 269 "cocx.mod"
#endif
#line 269 "cocx.mod"
{
#line 269 "cocx.mod"
  pOt_INTEGER pOt_np;
#line 269 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 269 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 269 "cocx.mod"

#line 269 "cocx.mod"
  switch(pOt_fctno) {
#line 269 "cocx.mod"
  case 0:
  break;
#line 270 "cocx.mod"
  case 1:
#line 270 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x540L],&pOt__str_td[0x10]))));
#line 270 "cocx.mod"
    pOt_CTDName_COCN((struct pOt__tag_2_COCT*)((*pOt_x).pOt_typ),(pOt_INTEGER)(pOt_cslen_COCQ),&pOt_np);
  break;
#line 271 "cocx.mod"
  case 2:
#line 271 "cocx.mod"
  break;
  case 3:
#line 272 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
#line 274 "cocx.mod"
    pOt_CTDenoter_COCN((struct pOt__tag_2_COCT*)((*pOt_x).pOt_typ),(pOt_INTEGER)(pOt_np),&pOt_np);
    if(((unsigned long)0!=((unsigned long)1<<pOt__rngchk_se(__FILE__,__LINE__, (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_form)&(pOt_SET)0x70L))) {
#line 275 "cocx.mod"
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x558L],&pOt__str_td[0xA]))),(pOt_INTEGER)(pOt_np),&pOt_np);
    } else if(((unsigned long)0!=((unsigned long)1<<pOt__rngchk_se(__FILE__,__LINE__, (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_form)&(pOt_SET)0x180L))) {
#line 276 "cocx.mod"
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x568L],&pOt__str_td[0xB]))),(pOt_INTEGER)(pOt_np),&pOt_np);
#line 278 "cocx.mod"
    }
#line 278 "cocx.mod"
  break;
#line 278 "cocx.mod"
  case 4:
#line 278 "cocx.mod"
  case 5:
#line 278 "cocx.mod"
  case 6:
#line 278 "cocx.mod"
  break;
  case 7:
#line 279 "cocx.mod"
    if(((unsigned long)0!=((unsigned long)1<<pOt__rngchk_se(__FILE__,__LINE__, (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_form)&(pOt_SET)0x38000L))) {
#line 281 "cocx.mod"
      pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x578L],&pOt__str_td[0x16]))));
    } else {
#line 282 "cocx.mod"
      pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x8L],&pOt__str_td[0x1]))));
#line 284 "cocx.mod"
    }
#line 284 "cocx.mod"
  break;
#line 284 "cocx.mod"
  case 8:
#line 284 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x8L],&pOt__str_td[0x1]))));
  break;
#line 285 "cocx.mod"
  case 9:
#line 285 "cocx.mod"
    if(((unsigned long)0!=((unsigned long)1<<pOt__rngchk_se(__FILE__,__LINE__, (*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_form)&(pOt_SET)0x38000L))) {
#line 287 "cocx.mod"
      pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x594L],&pOt__str_td[0x15]))));
#line 289 "cocx.mod"
    }
#line 289 "cocx.mod"
  break;
#line 289 "cocx.mod"
  case 10:
#line 289 "cocx.mod"
  case 11:
#line 289 "cocx.mod"
  break;
  case 12:
#line 290 "cocx.mod"
    if(pOt_rngchk) {
#line 290 "cocx.mod"
      pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x8L],&pOt__str_td[0x1]))));
    }
#line 291 "cocx.mod"
  break;
#line 291 "cocx.mod"
  case 13:
#line 291 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
    pOt_CTDenoter_COCN((struct pOt__tag_2_COCT*)((*pOt_x).pOt_typ),(pOt_INTEGER)(pOt_np),&pOt_np);
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x8L],&pOt__str_td[0x1]))),(pOt_INTEGER)(pOt_np),&pOt_np);
#line 295 "cocx.mod"
    if(pOt_rngchk) {
#line 295 "cocx.mod"
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x5B0L],&pOt__str_td[0xC]))),(pOt_INTEGER)(pOt_np),&pOt_np);
      switch((*((struct pOt__tag_2_COCT*)pOt__nilchk(__FILE__,__LINE__,(*pOt_x).pOt_typ))).pOt_form) {
#line 296 "cocx.mod"
      case 5:
#line 296 "cocx.mod"
        pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x5C4L],&pOt__str_td[0x2]))),(pOt_INTEGER)(pOt_np),&pOt_np);
      break;
#line 297 "cocx.mod"
      case 6:
#line 297 "cocx.mod"
        pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x5CCL],&pOt__str_td[0x1]))),(pOt_INTEGER)(pOt_np),&pOt_np);
      break;
#line 298 "cocx.mod"
      case 8:
#line 298 "cocx.mod"
        pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x5D4L],&pOt__str_td[0x1]))),(pOt_INTEGER)(pOt_np),&pOt_np);
      break;
#line 299 "cocx.mod"
      default:;
#line 299 "cocx.mod"
        pOt__halt(__FILE__,__LINE__,0x10);
#line 299 "cocx.mod"
      }
#line 299 "cocx.mod"
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x5DCL],&pOt__str_td[0x13]))),(pOt_INTEGER)(pOt_np),&pOt_np);
#line 301 "cocx.mod"
    } else {
#line 301 "cocx.mod"
      pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x1]))),(pOt_INTEGER)(pOt_np),&pOt_np);
#line 303 "cocx.mod"
    }
#line 303 "cocx.mod"
  break;
#line 303 "cocx.mod"
  case 14:
#line 303 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x0L],&pOt__str_td[0x1]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
    pOt_CTDenoter_COCN((struct pOt__tag_2_COCT*)((*pOt_x).pOt_typ),(pOt_INTEGER)(pOt_np),&pOt_np);
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x148L],&pOt__str_td[0x2]))),(pOt_INTEGER)(pOt_np),&pOt_np);
#line 307 "cocx.mod"
  break;
#line 307 "cocx.mod"
  case 15:
  break;
#line 308 "cocx.mod"
  case 16:
#line 308 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x5F4L],&pOt__str_td[0x3]))));
  break;
#line 309 "cocx.mod"
  case 17:
#line 309 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x5FCL],&pOt__str_td[0x3]))));
  break;
#line 310 "cocx.mod"
  case 18:
#line 310 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x604L],&pOt__str_td[0x16]))));
  break;
#line 311 "cocx.mod"
  case 19:
#line 311 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x620L],&pOt__str_td[0x17]))));
  break;
#line 312 "cocx.mod"
  case 20:
#line 312 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x208L],&pOt__str_td[0x1]))));
  break;
#line 313 "cocx.mod"
  case 21:
#line 313 "cocx.mod"
  case 22:
#line 313 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1E0L],&pOt__str_td[0x1]))));
  break;
#line 314 "cocx.mod"
  case 23:
#line 314 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1E0L],&pOt__str_td[0x1]))));
#line 314 "cocx.mod"
    pOt_CTSize_COCN((struct pOt__tag_2_COCT*)((*pOt_x).pOt_typ),(pOt_INTEGER)(pOt_cslen_COCQ),&pOt_np);
#line 314 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x63CL],&pOt__str_td[0x3]))));
  break;
#line 315 "cocx.mod"
  case 24:
#line 315 "cocx.mod"
  case 25:
#line 315 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x644L],&pOt__str_td[0x14]))));
  break;
#line 316 "cocx.mod"
  case 26:
#line 316 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0xCCL],&pOt__str_td[0x2]))));
    if(pOt_rngchk) {
#line 317 "cocx.mod"
      pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x660L],&pOt__str_td[0x25]))));
    } else {
#line 318 "cocx.mod"
      pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x68CL],&pOt__str_td[0x5]))));
#line 320 "cocx.mod"
    }
#line 320 "cocx.mod"
  break;
#line 320 "cocx.mod"
  case 27:
#line 320 "cocx.mod"
    pOt_Prepend_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x140L],&pOt__str_td[0x2]))),(pOt_INTEGER)((*pOt_x).pOt_qoffs),&pOt_np);
#line 320 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x148L],&pOt__str_td[0x2]))));
  break;
#line 321 "cocx.mod"
  case 28:
#line 321 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x698L],&pOt__str_td[0x2]))));
#line 321 "cocx.mod"
    pOt_CTDenoter_COCN((struct pOt__tag_2_COCT*)((*pOt_x).pOt_typ),(pOt_INTEGER)(pOt_cslen_COCQ),&pOt_np);
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x6A0L],&pOt__str_td[0x1E]))));
  break;
#line 323 "cocx.mod"
  case 29:
#line 323 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x6C4L],&pOt__str_td[0xD]))));
  break;
#line 324 "cocx.mod"
  case 30:
#line 324 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x6D8L],&pOt__str_td[0x15]))));
#line 326 "cocx.mod"
  break;
#line 326 "cocx.mod"
  default:;
#line 326 "cocx.mod"
    pOt__halt(__FILE__,__LINE__,0x10);
#line 326 "cocx.mod"
  }
#line 326 "cocx.mod"

#line 326 "cocx.mod"
pOt__Epilogue:;
#line 326 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 326 "cocx.mod"
}
#line 326 "cocx.mod"

#line 326 "cocx.mod"

#line 331 "cocx.mod"

#line 331 "cocx.mod"

#line 331 "cocx.mod"
extern void pOt_StPar2Sfx_COCX
#line 331 "cocx.mod"
#if pOt__ANSI_C
#line 331 "cocx.mod"
  (struct pOt__tag_3_COCT *pOt_x, pOt_INTEGER pOt_fctno, pOt_BOOLEAN pOt_rngchk)
#line 331 "cocx.mod"
#else
#line 331 "cocx.mod"
  (pOt_x, pOt_fctno, pOt_rngchk)
#line 331 "cocx.mod"
  struct pOt__tag_3_COCT *pOt_x;
#line 331 "cocx.mod"
  pOt_INTEGER pOt_fctno;
#line 331 "cocx.mod"
  pOt_BOOLEAN pOt_rngchk;
#line 331 "cocx.mod"

#line 331 "cocx.mod"
#endif
#line 331 "cocx.mod"
{
#line 331 "cocx.mod"
  pOt_INTEGER pOt_np;
#line 331 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 331 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 331 "cocx.mod"

#line 331 "cocx.mod"
  switch(pOt_fctno) {
#line 331 "cocx.mod"
  case 16:
#line 331 "cocx.mod"
  case 17:
  break;
#line 332 "cocx.mod"
  case 18:
#line 332 "cocx.mod"
  case 19:
#line 332 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x8L],&pOt__str_td[0x1]))));
  break;
#line 333 "cocx.mod"
  case 20:
  case 21:
#line 334 "cocx.mod"
  case 22:
#line 334 "cocx.mod"
  case 23:
#line 334 "cocx.mod"
  break;
#line 334 "cocx.mod"
  case 24:
#line 334 "cocx.mod"
  case 25:
#line 334 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x1E0L],&pOt__str_td[0x1]))));
#line 334 "cocx.mod"
    pOt_CTSize_COCN((struct pOt__tag_2_COCT*)((*pOt_x).pOt_typ),(pOt_INTEGER)(pOt_cslen_COCQ),&pOt_np);
  break;
#line 335 "cocx.mod"
  case 26:
#line 335 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x50L],&pOt__str_td[0x2]))));
  break;
#line 336 "cocx.mod"
  case 27:
#line 336 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x8L],&pOt__str_td[0x1]))));
  break;
#line 337 "cocx.mod"
  case 28:
#line 337 "cocx.mod"
  case 29:
  break;
#line 338 "cocx.mod"
  case 30:
#line 338 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x150L],&pOt__str_td[0x2]))));
#line 340 "cocx.mod"
  break;
#line 340 "cocx.mod"
  default:;
#line 340 "cocx.mod"
    pOt__halt(__FILE__,__LINE__,0x10);
#line 340 "cocx.mod"
  }
#line 340 "cocx.mod"

#line 340 "cocx.mod"
pOt__Epilogue:;
#line 340 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 340 "cocx.mod"
}
#line 340 "cocx.mod"

#line 340 "cocx.mod"

#line 344 "cocx.mod"

#line 344 "cocx.mod"

#line 344 "cocx.mod"
extern void pOt_StPar3Sfx_COCX
#line 344 "cocx.mod"
#if pOt__ANSI_C
#line 344 "cocx.mod"
  (struct pOt__tag_3_COCT *pOt_x, pOt_INTEGER pOt_fctno, pOt_BOOLEAN pOt_rngchk)
#line 344 "cocx.mod"
#else
#line 344 "cocx.mod"
  (pOt_x, pOt_fctno, pOt_rngchk)
#line 344 "cocx.mod"
  struct pOt__tag_3_COCT *pOt_x;
#line 344 "cocx.mod"
  pOt_INTEGER pOt_fctno;
#line 344 "cocx.mod"
  pOt_BOOLEAN pOt_rngchk;
#line 344 "cocx.mod"

#line 344 "cocx.mod"
#endif
#line 344 "cocx.mod"
{
#line 344 "cocx.mod"
  pOt_INTEGER pOt_np;
#line 344 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 344 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 344 "cocx.mod"

#line 344 "cocx.mod"
  switch(pOt_fctno) {
  case 30:
  break;
  default:;
#line 347 "cocx.mod"
    pOt__halt(__FILE__,__LINE__,0x10);
#line 347 "cocx.mod"
  }
#line 347 "cocx.mod"

#line 347 "cocx.mod"
pOt__Epilogue:;
#line 347 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 347 "cocx.mod"
}
#line 347 "cocx.mod"

#line 347 "cocx.mod"

#line 350 "cocx.mod"

#line 350 "cocx.mod"

#line 350 "cocx.mod"
extern void pOt_StFakeSfx_COCX
#line 350 "cocx.mod"
#if pOt__ANSI_C
#line 350 "cocx.mod"
  (pOt_INTEGER pOt_fctno, pOt_BOOLEAN pOt_rngchk)
#line 350 "cocx.mod"
#else
#line 350 "cocx.mod"
  (pOt_fctno, pOt_rngchk)
#line 350 "cocx.mod"
  pOt_INTEGER pOt_fctno;
#line 350 "cocx.mod"
  pOt_BOOLEAN pOt_rngchk;
#line 350 "cocx.mod"

#line 350 "cocx.mod"
#endif
#line 350 "cocx.mod"
{
#line 350 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 350 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 350 "cocx.mod"

#line 350 "cocx.mod"
  switch(pOt_fctno) {
  case 16:
#line 351 "cocx.mod"
  case 17:
#line 351 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x6F4L],&pOt__str_td[0x1]))));
  break;
#line 352 "cocx.mod"
  case 20:
#line 352 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x6FCL],&pOt__str_td[0x1]))));
#line 354 "cocx.mod"
  break;
#line 354 "cocx.mod"
  default:;
#line 354 "cocx.mod"
    pOt__halt(__FILE__,__LINE__,0x10);
#line 354 "cocx.mod"
  }
#line 354 "cocx.mod"

#line 354 "cocx.mod"
pOt__Epilogue:;
#line 354 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 354 "cocx.mod"
}
#line 354 "cocx.mod"

#line 354 "cocx.mod"

#line 357 "cocx.mod"

#line 357 "cocx.mod"

#line 357 "cocx.mod"
extern void pOt_StFctSfx_COCX
#line 357 "cocx.mod"
#if pOt__ANSI_C
#line 357 "cocx.mod"
  (pOt_INTEGER pOt_fctno, pOt_BOOLEAN pOt_rngchk)
#line 357 "cocx.mod"
#else
#line 357 "cocx.mod"
  (pOt_fctno, pOt_rngchk)
#line 357 "cocx.mod"
  pOt_INTEGER pOt_fctno;
#line 357 "cocx.mod"
  pOt_BOOLEAN pOt_rngchk;
#line 357 "cocx.mod"

#line 357 "cocx.mod"
#endif
#line 357 "cocx.mod"
{
#line 357 "cocx.mod"
  struct {void*next;} pOt__gc_ptrs;
#line 357 "cocx.mod"
  pOt__gc_ptrs.next = pOt__gc_root;
#line 357 "cocx.mod"

#line 357 "cocx.mod"
  if((((pOt_fctno==((pOt_INTEGER)(10))))||((pOt_fctno==((pOt_INTEGER)(11)))))) {
#line 359 "cocx.mod"
  } else if(( pOt_fctno==((pOt_INTEGER)(20)))) {
#line 359 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x704L],&pOt__str_td[0x9]))));
  } else {
#line 360 "cocx.mod"
    pOt_Append_COCQ(pOt__dup_arr(__FILE__,__LINE__,(pOt__ArrTypDsc**)&(*pOt__set_str_td(&pOt__strcon_buf[0x8L],&pOt__str_td[0x1]))));
#line 362 "cocx.mod"
  }
#line 362 "cocx.mod"

#line 362 "cocx.mod"
pOt__Epilogue:;
#line 362 "cocx.mod"
  pOt__gc_root=(struct pOt__tag_gc_node*)pOt__gc_ptrs.next;
#line 362 "cocx.mod"
}
#line 362 "cocx.mod"

#line 362 "cocx.mod"
void pOt_COCX__body()
#line 364 "cocx.mod"
{
#line 364 "cocx.mod"
  static int pOt_COCX__loaded=0;
#line 364 "cocx.mod"
  if(!pOt_COCX__loaded){
#line 364 "cocx.mod"
    pOt_COCX__loaded=1;
#line 364 "cocx.mod"

#line 364 "cocx.mod"
    pOt_Strings__body();
#line 364 "cocx.mod"
    pOt_COCT__body();
#line 364 "cocx.mod"
    pOt_COCQ__body();
#line 364 "cocx.mod"
    pOt_COCN__body();
#line 364 "cocx.mod"
    pOt_COCJ__body();
#line 364 "cocx.mod"

#line 364 "cocx.mod"
    pOt__gc_ptrs.next=pOt__gc_root;
#line 364 "cocx.mod"
    pOt__gc_root=(struct pOt__tag_gc_node*)&pOt__gc_strs;
#line 364 "cocx.mod"

#line 364 "cocx.mod"

#line 364 "cocx.mod"

#line 364 "cocx.mod"
  pOt__Epilogue:;
#line 364 "cocx.mod"
  }
#line 364 "cocx.mod"
}
#line 364 "cocx.mod"
